### ISSUE TITLE
Bug：程序无法正常启动

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#1]
我 fork 了这个项目并且尝试启动，但是很可惜没有启动成功。

I don't know whether it is my fault ...

## 双终端开启

如果使用开启两个终端启动服务的话，`pnpm dev:lib` 命令可以正常启动以及运行，但是 `pnpm demo` 就没那么好运了。
![Terminal](https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/issue/valaxy-bug-1-5b95c6.png)

其实最开始运行 `pnpm demo` 它会提醒我找不到指令 `nodemon`，全局安装才能看到下一个错误。
![Nodemon not found](https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/issue/valaxy-bug-2-fa4cab.png)

## 单终端开启

在没有全局安装 `nodemon` 之前程序无法启动，安装后正常。

如果需要全局安装 `nodemon` 才能启动希望能在 `README.md` 稍作提示。

**Comment by YunYouJun** [comment]
I have added nodemon to dependencies for demo.
