### ISSUE TITLE
首页加载目录以及评论和文章自动滑动问题

### ISSUE THREAD

**Issue by Masle1** [YunYouJun/valaxy#10]
1. 在查看非第一页文章时，有时候打开文章会很慢（或者说完全打不开）。这个时候返回到选择文章的页面会发现目录以及评论在首页加载了
![Screenshot_20220424_180928_com microsoft emmx](https://user-images.githubusercontent.com/80967408/164971575-ae4e6c24-d27b-4d03-952b-1a711bf2f44f.jpg)
![Screenshot_20220424_180924_com microsoft emmx](https://user-images.githubusercontent.com/80967408/164971596-99ae2133-cc8d-402d-adaf-27b984f4fd57.jpg)

2. 在打开文章后，不会在文章开头开始阅读。而是加载你打开该文章时的滑动进度
注：第二个估计小云知道这个情况，但是第一个bug应该是未知的🙃

**Comment by YunYouJun** [comment]
第二个属于特性的一种，一些 PJAX 同样存在该效果。可以专门再加一层逻辑回到顶部，但这可能不是现在的首要任务。

第一个问题似乎无法复现，能否提供更详细的复现手段，或录制视频，

**Comment by Masle1** [comment]
https://user-images.githubusercontent.com/80967408/164980774-f279f5c7-8d97-4e62-8d00-891d57fa081f.mp4

触发前提是文章页面有几率会打不开。(第一页文章的出现几率较小，我在第二页文章是打开时经常出现)
打不开时，返回上一级，就会多出来个目录和评论区。

**Comment by YunYouJun** [comment]
> 触发前提是文章页面有几率会打不开。

是随机吗？

**Comment by YunYouJun** [comment]
成功复现，还在排查。

**Comment by YunYouJun** [comment]
破案了，是 `markdown-it-attrs` 的 `{}` 语法与 hexo 语法 `{% %}` 冲突导致。
我将移除 `{% %}` 的内容，在 Valaxy 中拥有更为优雅的替代，同时会在控制台检测并提示用户移除 `{% %}` 语法。
