### ISSUE TITLE
bug: build vite-ssg error document is not defined

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#104]
![image](https://user-images.githubusercontent.com/49724027/182305026-08fe34ec-6c38-42e7-b8fe-0056e327b1c2.png)

steps
```sh
pnpm  create valaxy
pnpm build
```

**Comment by Rotten-LKZ** [comment]
It means you must set a fixed URL like `https://example.com/` for `config.url` .

**Comment by YunYouJun** [comment]
`config.url` is a URL can be visited in network. Otherwise, '/' makes no sense for RSS.
