### ISSUE TITLE
bug: theme pnpm demo needs to refresh the page for the first time

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#105]
The page opened after theme pnpm demo is blank, you need to refresh the page once

![image](https://user-images.githubusercontent.com/49724027/182316388-3d3956a2-c643-46a6-b37d-8471aea391a0.png)

**Comment by YunYouJun** [comment]
Can't reproduce. We need more information.

**Comment by YunYouJun** [comment]
Close without more information. Perhaps it has been fixed in the new version.
