### ISSUE TITLE
bug: Lots of APIs missing HMR updates

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#106]
Sphere of influence

- useFrontmatter (.md update invalid)
- useConfig (needs to be refreshed)
- useThemeConfig (reboot required)
- usePostList (reboot required)
- useCategory (reboot required)
- useTag (reboot required)

**Comment by YunYouJun** [comment]
Now, it works. Will released in `v0.13.9`.


https://user-images.githubusercontent.com/25154432/214910461-f1419edf-9bc9-47e5-8bbb-368e3f6d2046.mov
