### ISSUE TITLE
feat: better creation of valve projects

### ISSUE THREAD

**Issue by hairyf** [YunYouJun/valaxy#107]
From creating a project, I think more options can be provided for the user to use
This has the benefit of reducing the tediousness of dealing with build projects, which is convenient

- provide theme selection
```sh
pnpm create valaxy

> select your theme (default: yun)
> [...enter search]
> xxx [link]
> aaa [link]
```

- select config file type
```sh
> config file type

> javascript
> typescript
> json
> yml
```

or more...

**Comment by Rotten-LKZ** [comment]
I think it okay that this starter just supports `.ts` file.
1. `.ts` file has good type support, which you can easily check what can be configured
2. `.json` file is not proper to be config file because it has lots of limits
3. Using `.ts` or `.js` means you can extract config options to be a individual var or write some simple code like loops to make configuring more convenient

**Comment by YunYouJun** [comment]
Providing theme selection is possible, but it means more template maintenance, or forcing theme developers to provide configuration templates in some form. Their complexity is now unnecessary.

Same with configuration files.

**Comment by TuiMao233** [comment]
There may indeed be a problem that requires extra work on `select config file type`, but I think `select your theme` can directly read the 'package. json - repository' field in the theme, which will not force the theme developer to provide a configuration template in some form

**Comment by YunYouJun** [comment]
The default configuration file for a theme may be different.

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/valaxy/blob/615f0c5a89503f2ddfa5807b7db9c75fff023961/packages/create-valaxy/src/theme.ts#L33

```ts
const starterTheme = {
  name: 'starter',
  display: `Starter`,
  repo: 'https://github.com/valaxyjs/valaxy-theme-starter',
}
```

Now, we use `degit` to clone theme template repo, so feel free to add theme templates.

**Comment by YunYouJun** [comment]
Also welcome a pr for Theme Gallery.

- https://valaxy.site/themes/gallery
