### ISSUE TITLE
bug: dependency exception when the topic turns to the user

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#108]
step.1: anywhere in the subject

```js
import isNumber from 'lodash/isNumber'

isNumber(1)
```

step.2: user installs and uses the theme

```js
pnpm add valaxy-theme-xxx
```

```json
{
  "theme": "xxx"
}
```

step.3: start the valaxy app

```sh
pnpm valaxy
```

![image](https://user-images.githubusercontent.com/49724027/182537612-d8f3c86c-7174-48f6-a2e3-729e38dc45b7.png)

**Comment by YunYouJun** [comment]
Add it to `vite.optimizeDeps.include` will works.
