### ISSUE TITLE
bug: some .md syntax styles are missing

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#109]
![image](https://user-images.githubusercontent.com/49724027/182551873-0e909969-d1ea-4ec8-9d4d-72847f2c9777.png)

![image](https://user-images.githubusercontent.com/49724027/182552069-2b7269f3-6f38-41b4-920d-5c88e3225fc8.png)

![image](https://user-images.githubusercontent.com/49724027/182818396-41a96d7f-fa24-4038-9eab-36bdc44181b6.png)

**Comment by Rotten-LKZ** [comment]
It seems to be working normally in theme press. Did you open `Inspect` to check if those was rendered?
![theme press](https://user-images.githubusercontent.com/54099603/188295463-e49b8299-77e5-440a-908a-2ce2839d1b99.png)

**Comment by TuiMao233** [comment]
Style does not exist in custom theme

**Comment by YunYouJun** [comment]
Markdown CSS can be set by theme.

This is https://github.com/YunYouJun/valaxy/blob/f3ab87f7a97bb0447e2d2175533e206220f80bf5/packages/valaxy-theme-press/styles/markdown.scss customed by theme-press.

**Comment by TuiMao233** [comment]
This looks good, but I think a documentation description is needed
