### ISSUE TITLE
安装过程报 [ERR_REQUIRE_ESM] 错误

### ISSUE THREAD

**Issue by Sknp1006** [YunYouJun/valaxy#11]
环境
系统版本：**Ubuntu 20.04.4 LTS x86**
Node版本：**v16.9.0**
NPM版本：**7.21.1**
V8版本：**9.3.345.16**
pnpm版本：**7.0.0**

具体问题不知该如何描述，现象是无法通过 `pnpm create valaxy` 初始化项目
![image](https://user-images.githubusercontent.com/41496773/166877917-26e5b3cb-5444-4b21-8b5f-8cb91fa8cb14.png)

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/valaxy/commit/dafbc5e418a30f41da0419bf880d8619a8d0f02d.

Downgrade execa to `5`.

Will be released in `v0.3.1`.

Thanks for your feedback.
