### ISSUE TITLE
feat: the exact location of excerpt can be specified

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#110]
as the title

case:

```md

- ...
- ...

<!-- more:start -->

content...

<!-- more:end -->

```

**Comment by YunYouJun** [comment]
I think this feature should be requested in [gray-matter](https://github.com/jonschlinkert/gray-matter).

https://github.com/YunYouJun/valaxy/blob/11f0e862369b0e57901f1bc6bd66ae21fc7df93b/packages/valaxy/node/rss.ts#L68
