### ISSUE TITLE
feat: Support post overlap with categories

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#111]

**Comment by YunYouJun** [comment]
Need more description, I can't understand what you want directly from the title.

**Comment by TuiMao233** [comment]
> Need more description, I can't understand what you want directly from the title.

If it is a four-level classification, an exception will occur when there is a three-level classification

**Comment by YunYouJun** [comment]
Any examples and screenshots?

**Comment by TuiMao233** [comment]
It can be understood so simply

**Comment by TuiMao233** [comment]
If there is an article classified as A>B, add an article classified as A>B>C, and valaxy does not support

**Comment by YunYouJun** [comment]
Now, it works. 
![image](https://user-images.githubusercontent.com/25154432/215283690-02927157-b05b-41e3-b09a-a1e41558d78f.png)
