### ISSUE TITLE
dropdown menu be covered on mobile

### ISSUE THREAD

**Issue by Sepush** [YunYouJun/valaxy#114]
![image](https://user-images.githubusercontent.com/39197136/187077757-8c3494cb-3400-4e31-a8c0-e3038000d981.png)

**Comment by YunYouJun** [comment]
I will fix asap. Or are you interested in creating a PR?

**Comment by Rotten-LKZ** [comment]
> I will fix asap. Or are you interested in creating a PR?

I solved this problem in #115
