### ISSUE TITLE
使用文档不够完善，希望新增更换字体功能

### ISSUE THREAD

**Issue by vlinux** [YunYouJun/valaxy#123]
我在浏览官方文档的时候发现，配置文档很简洁明了，但是在我的初次使用过程中，尽管他非常丝滑，当我把Md文件按照Valaxy相关格式编辑好后移动到指定的post目录，他可以瞬间更新生成好文章供我查看，这一点，很牛，因为他少了很多CI的构建时间，或者说他是自动构建的，不过我还是困惑，我究竟应该怎样把它部署在Github？
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/73208462/201275990-167d6d38-ed20-4f1d-8658-b7f23b235113.png">
我看到您在文档中这样提出，使用github的这个分支gh-pages，上传repo，但这样的话，我如果新增一个文章该怎么新增呢？在本地新增，然后npm run build出静态文件dist目录，将这个目录上传到github吗？那我是不是每次新增文章都要执行 npm run build && cd dist && git push? 
可以有更简单的方法吗？又或者我部署的方法理解有误？
还有一个我希望新增更换字体的方式，和valaxy专属的CLI命令，像hexo那样，甚至更好

**Comment by Rotten-LKZ** [comment]
1. 有关于部署到 `GitHub Pages` 之后更新文章，只需要使用 `git` 将文章的修改、增加、删除或者其他配置的更改等任何内容变更提交到对应仓库，`GitHub Actions` 将根据 `.github/workflows/gh-pages.yml` 自动更新部署页面。
2. 至于字体，应该属于主题方面的内容，主要取决于主题有没有提供修改字体的配置项。

**Comment by vlinux** [comment]
辛苦了 云游君


在 2022年11月19日 ***@***.***> 写道：


有关于部署到 GitHub Pages 之后更新文章，只需要使用 git 将文章的修改、增加、删除或者其他配置的更改等任何内容变更提交到对应仓库，GitHub Actions 将根据 .github/workflows/gh-pages.yml 自动更新部署页面。 至于字体，应该属于主题方面的内容，主要取决于主题有没有提供修改字体的配置项。

**Comment by YunYouJun** [comment]
已补充 Cli 文档与部署文档。

**Comment by YunYouJun** [comment]
已补充如何自定义样式与自定义字体文档。

https://valaxy.site/guide/custom/styles
