### ISSUE TITLE
能否支持自定义页脚

### ISSUE THREAD

**Issue by copurxia** [YunYouJun/valaxy#127]
貌似没有support的配置，又拍云又到期了

**Comment by YunYouJun** [comment]
支持自定义页脚，我将会补充文档。

**Comment by YunYouJun** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/25154432/204104325-9dc04ee2-1995-4974-a5a7-2bde0df6bf56.png">

可参见 https://github.com/YunYouJun/valaxy/blob/main/demo/yun/components/ 。
