### ISSUE TITLE
文档没有友联添加方式，希望出个HEXO迁移valaxy文档，或者typecho迁移valaxy文档。辛苦！

### ISSUE THREAD

**Issue by vlinux** [YunYouJun/valaxy#129]

**Comment by YunYouJun** [comment]
已补充 Hexo 迁移文档：https://valaxy.site/migration/hexo

**Comment by YunYouJun** [comment]
已补充 valaxy-theme-yun 自定义友链方式文档：https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-theme-yun/docs/zh-CN
