### ISSUE TITLE
valaxy有没有支持全局搜索和评论的功能

### ISSUE THREAD

**Issue by vlinux** [YunYouJun/valaxy#130]

**Comment by Rotten-LKZ** [comment]
https://github.com/YunYouJun/valaxy/blob/352d3f8b7cbaa0400fd9a9a7a17f8b6e066bd512/demo/yun/valaxy.config.ts#L103-L110
https://github.com/YunYouJun/valaxy/blob/352d3f8b7cbaa0400fd9a9a7a17f8b6e066bd512/demo/yun/valaxy.config.ts#L205-L214

**Comment by YunYouJun** [comment]
algolia 和 waline 需要参考各自服务自行申请相关密钥和部署。

Valaxy 封装了两个简单的插件 [valaxy-addon-waline](https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-waline) 与 [valaxy-addon-algolia](https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-algolia)，可参见对应 README。

纯静态的搜索插件正在计划制作中。

**Comment by YunYouJun** [comment]
纯静态的离线搜索（基于 [fuse.js](https://fusejs.io/)）已被实现。

> https://valaxy.site/guide/third-party#%E6%9C%AC%E5%9C%B0%E6%90%9C%E7%B4%A2%EF%BC%88%E5%9F%BA%E4%BA%8E-fuse-js%EF%BC%89
