### ISSUE TITLE
re-add features of hexo-theme-yun

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#131]
- [x] Cloud animation
- [x] busuanzi support
- [x] LeanCloud Visitor
- [x] post-card transparency
- [x] Live time
- [x] Custom footer
- [x] Word counter & read time

**Comment by YunYouJun** [comment]
Got it. They are in todo list.

**Comment by YunYouJun** [comment]
The transparency of `post-card` will not be an option.
Now, we can custom styles directly.

- busuanzi
- LeanCloud Visitor
- Word Counter
- Read Time
- Live Time

They will be addons.

- Custom Footer had been supported. See https://github.com/YunYouJun/valaxy/issues/127.

**Comment by YunYouJun** [comment]
I implement `live_time` by an addon `valaxy-addon-components`(Common Components).

<img width="371" alt="image" src="https://user-images.githubusercontent.com/25154432/213927928-4aee0240-2c67-4b7e-9edb-6ed487cd906f.png">

Usage I'll add in the README.

**Comment by YunYouJun** [comment]
Statistics had been added in `v0.14.17`.

![H)PTL07CU0LORM7H }FQ6LJ](https://user-images.githubusercontent.com/25154432/226171654-0fa20099-21dc-462f-8893-0393ebb3da40.png)

```ts
// site.config.ts

export default {
  statistics: { enable: true }
}
```

Almost all yun theme features are supported, and I'll close the issue.
