### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by logicwang** [YunYouJun/valaxy#134]
老哥你好，我想问一下，girls里面的json能不能自己改啊

**Comment by neila-a** [comment]
你指的是`pages`文件夹下的吗？`pages`文件夹下的所有文件都可以改。
~我把girls直接删了~

**Comment by logicwang** [comment]
> 你指的是`pages`文件夹下的吗？`pages`文件夹下的所有文件都可以改。 ~我把girls直接删了~

我看他这个都是引入进来的。。。 @

**Comment by YunYouJun** [comment]
你是说自定义吗？

可以参考这种方式：

https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-theme-yun/docs/zh-CN#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5

**Comment by logicwang** [comment]
好的，谢谢老板
