### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by zhoubin-me** [YunYouJun/valaxy#138]
To fix, change `COPY .npmrc package.json ./` to `COPY _npmrc package.json ./`
Add `RUN mkdir dist` before `RUN pnpm build`

```dockerfile
FROM node:16-alpine as build-stage

WORKDIR /app
RUN corepack enable

COPY .npmrc package.json ./
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install

COPY . .
RUN pnpm build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

**Comment by YunYouJun** [comment]
> Add RUN mkdir dist before RUN pnpm build

This problem had been fixed.

---

Why change `COPY .npmrc package.json` ./ to `COPY _npmrc package.json ./`

It doesn't work?

**Comment by YunYouJun** [comment]
Without more feedback, I will close the issue.
