### ISSUE TITLE
bug: 执行 npm run build 出错

### ISSUE THREAD

**Issue by Seanium** [YunYouJun/valaxy#139]
## bug
经测试，在本地和 Github actions 执行 `npm run build` ，均会出现以下两处错误，导致部署不成功。本地执行的报错信息如下。
## 第1个error
![image](https://user-images.githubusercontent.com/10975821/209762937-0f44978f-7f26-4439-ac87-a53faddababd.png)
## 第2个error
![image](https://user-images.githubusercontent.com/10975821/209763008-a07995cc-3ed1-4390-a198-26afda255d0e.png)

**Comment by YunYouJun** [comment]
第二个错误，是因为仅仅执行 rss 时，dist 目录未创建导致。已添加默认值修复。

**Comment by YunYouJun** [comment]
问题一仍然无法复现，能否提供可复现仓库？

**Comment by YunYouJun** [comment]
测试由于未配置 `addonWaline` 配置所导致。增加了是否使用插件的判断后解决。Released in v0.12.0.
