### ISSUE TITLE
A 404 error is returned if the file name has Chinese characters

### ISSUE THREAD

**Issue by Chenilove** [YunYouJun/valaxy#145]
Error occurred while migrating from hexo. 
I won't write the file name with Chinese next time.

**Comment by YunYouJun** [comment]
The file name will be the default url.
We always do not recommend you to use Chinese as the markdown name.
You can write the Chinese title in frontmatter of md.

```md
---
title: 你好
---
```

---

In the future, valaxy will consider transpile Chinese names, but this will not be a priority.
