### ISSUE TITLE
0.12.1 build时 出戳

### ISSUE THREAD

**Issue by NKDark** [YunYouJun/valaxy#147]
![QQ截图20230112212725](https://user-images.githubusercontent.com/22477622/212079213-1c8bbf2f-1a7d-44bb-a397-369fcd039614.jpg)
在 dev 预览时正常，github action build时出错
而后于本地build时也一样
```shell
# local
$ node -v
v18.13.0
$ yarn -v
1.22.19
```
# **[gist](https://gist.github.com/NKDark/64e03521d6041e2a6dfa722aa1a63375)**

**Comment by YunYouJun** [comment]
未配置对应插件

https://github.com/YunYouJun/valaxy/blob/c403a05c06a2259c5b38e1598d1710cd664f31a8/demo/yun/valaxy.config.ts#L211-L213

**Comment by YunYouJun** [comment]
将会提供容错处理。

**Comment by NKDark** [comment]
成了 谢谢云鸽鸽

**Comment by YunYouJun** [comment]
Thank you for your feedback.

Default fault tolerance was added in https://github.com/YunYouJun/valaxy/commit/0e01a58c11de3365fb5e385d5d58dbc3f7802164.

Released in v0.12.2.
