### ISSUE TITLE
如何在 valaxy-addon-busuanzi 发布之前在 Valaxy 中使用不算子？

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#149]
如题

**Comment by YunYouJun** [comment]
自定义全局页脚效果：
![image_2023-01-16_02-24-07](https://user-images.githubusercontent.com/25154432/212560286-0e14415e-d563-4681-ab17-e3f9756bbe9e.png)

自定义文章信息展示：
![image](https://user-images.githubusercontent.com/25154432/212560272-2bf0976f-0afa-4347-94e9-15c7c835ea4f.png)

自定义方式见文档：

https://valaxy.site/guide/custom/components

---

考虑到自定义加入 busuanzi 的方式非常简单，以及用户可能有自定义不蒜子统计样式布局的需求，暂时不需要也不会发布 `valaxy-addon-busuanzi` 插件。
