### ISSUE TITLE
Underlines of <a> position error

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#15]
When there is a picture in \<a\>, the underline is in the wrong position.

![Bug capture](https://cdn.jsdelivr.net/gh/Rotten-LKZ/cdn@main/images/issue/valaxy-tag-a-line-82c424.png)

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/valaxy/commit/96e1d84b09ce55585cf3a1c5b7f3596290e2c2e2.
