### ISSUE TITLE
Bug: TOC layout is still shown if I set toc: false on frontmatter

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#154]
TOC layout is still shown if I set toc: false on frontmatter.

![image](https://user-images.githubusercontent.com/54099603/212627404-aa5169ef-8960-4ea8-bf08-457bdb1606a8.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/54099603/212627333-779d00e1-3f0d-4481-8611-55c9c6b222fd.png)

However, this may be a feature, not a bug. If this is a feature, then the TOC area is in space and I think we can try to put something to the area.

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/212759298-98d88726-8ffb-4846-844c-442137e105d6.png)

`aside: false` to hide aside.

`toc: false` to hide TOC.
