### ISSUE TITLE
Bug: overlay won't be hidden after changing page

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#155]
When it is on desktop screen (the screen width is over 768px), the sidebar keeps showing in articles' pages. However, it doesn't be shown in the index page. So if I jump from the index page to an article page, the overlay over my screen won't disappear.

![image](https://user-images.githubusercontent.com/54099603/212628625-e01a1661-e972-40ce-b0aa-ae0b447620b2.png)

**Comment by YunYouJun** [comment]
I'm a little confused. What is an index page? More example pictures are needed.

**Comment by Rotten-LKZ** [comment]
![Animation](https://user-images.githubusercontent.com/54099603/212841873-663b86a0-eef9-4673-87df-3aaa7f3d5238.gif)

**Comment by Rotten-LKZ** [comment]
After I click the button in the upper left corner of the homepage, the sidebar expands and the layer appears.
![image](https://user-images.githubusercontent.com/54099603/212842623-893c4915-a8af-4819-90a3-0856114fc046.png)
Then I went to page *archives* (or other pages like *tags*, *categories*). Because the screen is larger than 768px, the sidebar will always fixed on the left, but the covered layer will not be hidden.
![image](https://user-images.githubusercontent.com/54099603/212843001-61465f86-2cb8-4120-afbc-6aa0e5b33e76.png)
