### ISSUE TITLE
feat(theme-yun): support notice

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#159]

**Comment by YunYouJun** [comment]
Can you take a screenshot?

**Comment by Big-Cake-jpg** [comment]
> Can you take a screenshot?

https://yun.yunyoujun.cn/guide/config.html#公告

![image](https://user-images.githubusercontent.com/76810494/213603030-54eb3f7a-ebee-4732-8835-67930d3be4e0.jpeg)
