### ISSUE TITLE
bug: need to support dockerfile code block

### ISSUE THREAD

**Issue by Sknp1006** [YunYouJun/valaxy#160]
Here is the error:
![image](https://user-images.githubusercontent.com/41496773/213391135-827725db-036c-48c2-85cd-25d2b6637a2b.png)

In Hexo:
![image](https://user-images.githubusercontent.com/41496773/213391081-fbd438cc-925a-4ef0-af7a-8675ad323680.png)

The Source:
![image](https://user-images.githubusercontent.com/41496773/213391770-088b5bd8-3fcd-4dc2-aadd-75dc31aa5530.png)

The hexo blog url: https://sknplz.xyz/2021/11/23/paddle-compose-a-word-recognizer/
:-)

**Comment by YunYouJun** [comment]
I had fallback it to `txt`. Just wait a new version of shiki. https://github.com/shikijs/shiki/pull/410

**Comment by esoubiran-aneo** [comment]
fix in #138

**Comment by YunYouJun** [comment]
It works now from last week!

Example: https://yun.valaxy.site/posts/code
Issue: https://github.com/shikijs/shiki/issues/458
