### ISSUE TITLE
Hope to add sidebar auto-scroll in valaxy-theme-yun

### ISSUE THREAD

**Issue by Seanium** [YunYouJun/valaxy#164]
On the post page, let the sidebar catalogue follow the current reading progress and scroll automatically, instead of being fixed.

**Comment by YunYouJun** [comment]
I'm a little confused.
The current toc title will follow the scroll.

**Comment by Seanium** [comment]
The precondition is when the sidebar has a scroll bar. The current toc title will follow the scroll, but toc itself will not scroll with the page scrolls.

![image](https://user-images.githubusercontent.com/10975821/214629665-fc4cac40-f0e2-40b3-a471-1f4a6c9ddea0.png)
![image](https://user-images.githubusercontent.com/10975821/214630500-6e5f381e-f5c3-49ac-85e3-aee53c63aafb.png)

Take yuque as an example, it always keeps the current toc title shown on the screen, due to the auto scrolling of sidebar.

![image](https://user-images.githubusercontent.com/10975821/214630695-9c74f9ff-d973-465f-b122-6758f472af93.png)
![image](https://user-images.githubusercontent.com/10975821/214629186-65e860b9-3a1e-4b0f-8b08-7af56558ef49.png)

**Comment by Seanium** [comment]
In other words, when I scroll down the passage, I hope the current title in toc can always be visible on the screen automatically and synchronously.

**Comment by Seanium** [comment]
https://crazywong.com/posts/css-basic-review/
This hexo theme has the same effect as yuque.

**Comment by YunYouJun** [comment]
OK, I got it.

**Comment by YunYouJun** [comment]
Done, released in v0.13.7.
