### ISSUE TITLE
project

### ISSUE THREAD

**Issue by ricardowangyf** [YunYouJun/valaxy#166]
why i cant enter the page?
![image](https://user-images.githubusercontent.com/81006817/215274455-2f6aa324-92b8-4606-8d37-b3a289ea7522.png)

**Comment by Ricardowangyf** [comment]
wait for so many times ,but i still cant enter the papge

**Comment by YunYouJun** [comment]
Please provide a minimal reproducible repo.

**Comment by Ricardowangyf** [comment]
ok thank you every much 
and i have another question 
how i cant enter the girls page and how can i edit it?

**Comment by Ricardowangyf** [comment]
now i add the girls page 
![image](https://user-images.githubusercontent.com/81006817/215277327-b9a34c0f-496e-422d-ac76-86046bc64f4d.png)
but , i  cant edit the page , can i change the page?

**Comment by YunYouJun** [comment]
See

https://github.com/YunYouJun/valaxy/blob/7482b248ae1fef2b6c3948abdbaaea48d9fd228b/demo/yun/valaxy.config.ts#L42-L47

**Comment by Ricardowangyf** [comment]
i addit 
![image](https://user-images.githubusercontent.com/81006817/215300902-551775c5-9f15-4c02-9aac-b20ff2bc7020.png)
my mean its , how can i edit the page ?
![image](https://user-images.githubusercontent.com/81006817/215300918-cec43668-4711-48f6-85d0-566e0b43941a.png)

**Comment by ricardowangyf** [comment]
![image](https://user-images.githubusercontent.com/81006817/215314690-7c686139-943a-4571-b810-5b0a79eed38d.png)
i change it ,this its my code 
but the css its different
![image](https://user-images.githubusercontent.com/81006817/215314698-868a6bf7-8feb-40ff-bb53-90b8c5d578a0.png)

**Comment by YunYouJun** [comment]
Please provide a your minimal reproducible repo. So i can test it.

**Comment by ricardowangyf** [comment]
https://github.com/ricardowangyf/valaxy-blog/blob/master/pages/girls/index.md

**Comment by ricardowangyf** [comment]
https://github.com/ricardowangyf/valaxy-blog/blob/master/pages/girls/index.md

**Comment by ricardowangyf** [comment]
sorry i mistake ，this its my code 

> ---
title: Lovely Girls
links:
  - url: https://www.yunyoujun.cn
    avatar: https://www.yunyoujun.cn/images/avatar.jpg
    blog: 原神
    desc: 宵宫
    color: "#0078e7"
  - url: https://zh.moegirl.org.cn/%E5%BE%A1%E5%9D%82%E7%BE%8E%E7%90%B4
    avatar: https://img2.baidu.com/it/u=2173215309,1270192997&fm=253&fmt=auto&app=120&f=JPEG?w=800&h=801
    name: 御坂美琴
    blog: 御坂美琴
    desc: 某科学的超电磁炮
    email: i@valaxy.site
    color: "#6058d9"

random: true
---

<YunLinks :links="frontmatter.links" :random="frontmatter.random" />

**Comment by YunYouJun** [comment]
It looks like you've mixed links and girls.

**Comment by YunYouJun** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/25154432/215527668-fd46219c-eaba-4943-a043-7f11c61ee409.png">

This indent is error.

**Comment by ricardowangyf** [comment]
sorry, I forgot to reply to your message
![image](https://user-images.githubusercontent.com/81006817/216041730-4546e6b8-d12f-4da9-9326-4750c25d2a5f.png)
![image](https://user-images.githubusercontent.com/81006817/216041850-9bd084c0-73a0-4161-b437-19a1b120e703.png)
could you please give me the format of the girls page?

**Comment by YunYouJun** [comment]
```md
---
title: Lovely Girls
date: 2019-01-07 11:17:35
updated: 2019-01-07 11:17:35
icon: i-ri-women-line
girls:
  - name: C.C.
    anilist_id: 1111
    douban_id: 2043155
    from: CODE GEASS
    avatar: https://s4.anilist.co/file/anilistcdn/character/medium/b1111-hNdvOW5ZNCCH.png
  - name: 黑雪姬
    anilist_id: 46305
    douban_id: 6869375
    from: 加速世界
    avatar: https://s4.anilist.co/file/anilistcdn/character/medium/b46305-CiZOEqz5u1mk.png
random: false
---

<YunGirls :girls="frontmatter.girls" :random="frontmatter.random" />
```

**Comment by ricardowangyf** [comment]
ok i got it ,thank you every much 

and i have another question 

![image](https://user-images.githubusercontent.com/81006817/216314860-a5f9cda2-3502-44a2-a2e7-523d759be56d.png)
![image](https://user-images.githubusercontent.com/81006817/216314954-15c07a84-8b76-4c33-94a5-acdc95bf4432.png)


this background and head portrait 

how should I modify it? 

I don't see relevant content in your document

**Comment by YunYouJun** [comment]
Docs will be written. Please see it previously.

https://github.com/YunYouJun/valaxy/blob/b230cc2d5a2e65038fd5532a5d164c3ec8529c56/packages/valaxy-theme-yun/types/index.d.ts#L45

https://github.com/YunYouJun/valaxy/blob/b230cc2d5a2e65038fd5532a5d164c3ec8529c56/packages/valaxy-theme-yun/types/index.d.ts#L7-L22

**Comment by ricardowangyf** [comment]
thank you every much
