### ISSUE TITLE
希望能不显示首页

### ISSUE THREAD

**Issue by Tohrusky** [YunYouJun/valaxy#168]
```
  themeConfig: {
    bg_image: {
      enable: true,
      url: 'https://api.vvhan.com/api/bing',
      opacity: 1,
    },

    banner: {
      enable: false,
      title: ''
    },
```
~~```bg_image```只能设置白天下的背景图，夜间模式还是默认的背景~~       [找到了](https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy-theme-yun/types/index.d.ts)

```banner```设置```false```似乎并没有效果（个人期望能直接显示下面的文章）

> 很喜欢☁️君的valaxy，祝valaxy越来越好，早日超越hexo

**Comment by YunYouJun** [comment]
Thanks.

`banner` 的逻辑将会进行校验，预计今晚修复。
