### ISSUE TITLE
Algolia search doesn't work

### ISSUE THREAD

**Issue by Seanium** [YunYouJun/valaxy#169]
see https://k-on.site/
When I click the search button, it doesn't respond.
![图片](https://user-images.githubusercontent.com/10975821/216645863-c99652cb-a840-4e85-b4c4-90210f433742.png)

**Comment by Seanium** [comment]
See repository [here](https://github.com/Seanium/Seanium.github.io). Is there a problem with my configuration?

**Comment by YunYouJun** [comment]
I will check it later.

**Comment by YunYouJun** [comment]
OK. Just upgrade `valaxy-addon-algolia` to `v0.0.3`.
