### ISSUE TITLE
bug: addon unable to set valaxy parameter

### ISSUE THREAD

**Issue by hairyf** [YunYouJun/valaxy#171]
由于 defineAddon 参数变更，resolveAddonConfig 中 index.ts 变得不在适用于更改 valaxy 参数。

![68d074f7298e5a4f33de71f58198d79](https://user-images.githubusercontent.com/49724027/218040148-497e60b1-5d97-4e8c-84a5-ed8ad80913ae.png)

建议 addon 包可在目录设置 valaxy.config.ts

**Comment by YunYouJun** [comment]
我认为 addon 不应该可以修改 valaxy.config.ts，这当用户自己设置 valaxy.config 时会产生困扰。

存在必须修改 valaxy.config 的 addon 吗？我认为那应该在 README 中告诉用户如何设置，而不是 addon 修改 valaxy.config，同时 valaxy.config 又加载了 addon，这产生了一个循环依赖的关系。

**Comment by TuiMao233** [comment]
我可以认可 addon 不修改 valaxy.config 的理念，事实上这对我不重要。

重要的是 valaxy.config 可以对不同的功能进行组合，而不是全部由 theme 承包所有工作。

我所看重是 valaxy.config 的多样性，正是因为多样性，所以 valaxy 才不可能做的十全十美，
所以才会需要第三方功能的加持，使得 valaxy 使用起来更加方便和快捷。

例如用户希望能够自定义图标，如果用户使用的 theme 没有支持，它能做的只有自己添加代码。

**Comment by YunYouJun** [comment]
我对`不能满足大多数要求`这一点存疑。Valaxy 支持 Vue 与 Vite 的插件，以借助已有的生态完成大部分需求。
对于开发者来说，Vue/Vite 的插件应该已经足以满足大部分功能的实现。

譬如自定义图标，unocss 的 preset-icons 或 [unplugin-icons](https://github.com/antfu/unplugin-icons) 已可以满足用户的大部分自定义需求。

我们要做的是寻找其无法解决的痛点，再思考其最佳解决办法。

> 在项目的初期，提供更复杂的 API 和混乱的加载机制，会让项目的可维护性变得更加糟糕。

**Comment by TuiMao233** [comment]
> 譬如自定义图标，unocss 的 preset-icons 或 [unplugin-icons](https://github.com/antfu/unplugin-icons) 已可以满足用户的大部分自定义需求。

这让我感觉目前 valaxy 是更面向于程序员的框架，如果我是前端小白，对 unocss 或者其他你所用的框架根本不了解（这没什么可笑的，不了解 unocss 的人，甚至前端可太多了）

**Comment by TuiMao233** [comment]
> 在项目的初期，提供更复杂的 API 和混乱的加载机制，会让项目的可维护性变得更加糟糕。

我可以认可这个观点，但我感觉现在所做的是只在把糟糕的可维护性转嫁到 user/theme 上，这在 theme 和 user 群体在增加的时候会越来越明显。

**Comment by YunYouJun** [comment]
> 这让我感觉目前 valaxy 是更面向于程序员的框架，如果我是前端小白，对 unocss 或者其他你所用的框架根本不了解（这没什么可笑的，不了解 unocss 的人，甚至前端可太多了）

静态博客框架本身确实是更偏向于开发者的框架，对于小白来说，如果想要易用性，可能会更倾向于 Wordpress 等动态博客框架。
小白用户可能确实并不了解相关可使用的插件，与此同时，他们往往也并不存在如开发者一样更深度的定制需求。
此外，我们也可以在文档中补充可参考的示例，使用户可以更快速地获取最佳实现方案。
帮助用户学习了解前端已有的插件工具，这份经验对于用户开发自己的其他项目也是有益的。

而提供一个其他插件可以实现的功能，随着定制需求不断增加，可能会导致不得不重新实现一遍相似的功能，类似的重复造轮子是不必要的。（此时，addon 相比用户配置第三方插件的便捷性未必是划算的。）

> 我可以认可这个观点，但我感觉现在所做的是只在把糟糕的可维护性转嫁到 user/theme 上，这在 theme 和 user 群体在增加的时候会越来越明显。

用户配置 addon 与配置第三方插件（在有文档示例时）的成本是接近的，维护工作则等价于转嫁给了第三方插件。
当用户需要的自定义功能不断增多时，他已经几乎是一名开发者了，使用不经过 addon 的方式实现自己的功能可能更为顺手。

目前可能存在一些 Vue/Vite 插件和现有的 addon 无法实现的功能，我们只需要先找到这部分的痛点，抛出来寻找最佳解决方案即可。如果此时增加 API 是必要的，valaxy 仍然可以继续增加。

**Comment by TuiMao233** [comment]
> 当用户需要的自定义功能不断增多时，他已经几乎是一名开发者了，使用不经过 addon 的方式实现自己的功能可能更为顺手。

你说的很对，但如果我是开发者，我想我应该会自定义开发一个 addon，而不是去修改我现有的博客中的 valaxy.config.ts。

这样的确是会有重复造轮子的情况发生，但这带来的收益我认为更加可观，我更希望 valaxy 的生态会更加庞大，你说 Vue/Vite 能够实现，这是确实的，但具有一定门槛是不可否认的。

我很喜欢 hexo 的插件设计，你可以简单想象一下，

如果你需要文章或站点字数及阅读时间统计，你只需要安装 hexo-symbols-count-time 插件

> 你可以说统计只要在 extendsMd 上用 fs.read 添加读取文章的各种信息，但我相信绝大多数的只会沮丧的放弃这个功能

如果你想要同步 qiniu 图片，你只需要安装 hexo-qiniu-sync 插件

hexo 的插件生态非常完善，这不单单可以让 theme 开发人员更方便的添加功能，还可以让用户可以随心所欲的利用插件魔改自己的主题。

**Comment by TuiMao233** [comment]
目前 valaxy-theme-hairy（我的主题上）valaxy.config 代码工作量是明显还是很多的。

主要原因还是因为 valaxy 新版没有一个很好的插件系统，无法对 valaxy.config 的配置进行有效抽离。

只能一股脑的将功能全部塞到 theme 的 valaxy.config 里了，这也是为什么我很讨厌让所有工作都交给 valaxy/theme 的原因。

![image](https://user-images.githubusercontent.com/49724027/220008204-1b7bc6d5-6bb0-4b3d-a104-dbd4ea988e7f.png)

**Comment by TuiMao233** [comment]
如果你认为这根本不算什么痛点，那我觉得这个 iss 可以在此进行关闭了，如果你觉得的确如此，那可以接着往下看。

> 我们要做的是寻找其无法解决的痛点，再思考其最佳解决办法。

按照我的想法（不一定对

最简单的：
- addon 直接支持 valaxy 参数修改

看起来更合理的：
- addon 更换为 plugin 的命名
- plugin 支持修改 valaxy 参数

更麻烦的：
- addon 原封不动
- 新增 plugin 支持修改 valaxy 参数

其他的：
- 想不到

**Comment by YunYouJun** [comment]
由于 valaxy addon 此前也合并了 `valaxy.config.ts`，我想我们可以停止此处的讨论了。

https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy-addon-lightgallery/valaxy.config.ts
