### ISSUE TITLE
文章内不显示updated日期

### ISSUE THREAD

**Issue by Tohrusky** [YunYouJun/valaxy#178]
```
---
title: test
date: 2023-02-13
updated: 2023-02-14
toc: true
categories:
  - test
---
```
如题，已经填写了updated日期，但文章内并无显示

希望能在开头显示
> 文章内容上次编辑时间于 xxx 天前，请注意文章的时效性
> 共 xxx 字，全部阅读完预计需要 xx 秒。 文章篇幅 适中/()/()，可以放心阅读/()/()

**Comment by YunYouJun** [comment]
Done. You can set `time_warning` in front-matter.

默认超过 30 天时才显示。

```md
---
time_warning: true
---
```

You also can custom difference.

```md
---
time_warning: 3600000
---
```
