### ISSUE TITLE
站点访问 404、rss 本地与 github action 生成不符

### ISSUE THREAD

**Issue by guowei-gong** [YunYouJun/valaxy#179]
# 问题列表
## 问题一
通过 github page 部署了网站，自定义域名，文章都可以正常访问。但是复制粘贴文章地址，在浏览器开启一个新页面，粘贴文章地址，页面 404。我通过文本对比工具，可以肯定它们的链接地址一模一样，通过自定义域名访问首页后，点击文章可以访问，**直接访问文章（未访问自定义域名的 index.html 首页），会 404。这个 404 页面并不是主题的 404 页面，而是 github page 的 404 页面**。
### 复现
1. 访问 `gongguowei.com`
2. 任意点击一篇文章
3. 复制文章的地址（直接通过地址栏或复制文章结尾的文章地址）
4. 浏览器打开一个新窗口
5. 粘贴刚才的文章地址，复现
### 我的尝试
我尝试寻找是否有人和我遇见同样的情况，看到其中一个 2015 年的讨论（远古讨论），他们认为与 github page 的仓库有关，如果这个仓库是你的用户名，那么始终解析的是 `main` 分支，其他仓库才会解析 `gh-pages` 分支。我目前使用的仓库是我的用户名命名的才哭，我已经修改了仓库 -> Settings -> Pages 下的 Branch，如下图。这会是引起这个问题的原因吗？我想下一步尝试直接部署到 `main` 分支试试看。

![image](https://user-images.githubusercontent.com/62499904/218695578-e9349abb-ddff-414c-9110-3679a49d9eae.png)

## 问题二
rss 本地生成 `atom.xml` 与我的预期一致，通过 github action 生成，与本地生成不一致，例如文章不是最新的。
本地生成的 `./dist/atom.xml` 如下：
![image](https://user-images.githubusercontent.com/62499904/218692552-8e95e7c1-da7e-4ba2-9df1-7d14ef7bb636.png)

github action 生成的如下，是过去的文章：
![image](https://user-images.githubusercontent.com/62499904/218692840-118f0728-655b-4d55-824d-e7877d4794a3.png)

### 我的尝试
我想我可以直接在本地编译后，手动上传到仓库，而不是通过 github action，尽管 github action 中执行的命名与我本地终端一致，并且 github action log 没有出现任何异常。

**Comment by guowei-gong** [comment]
针对问题一，我今天将静态生成的网页部署到 github page 默认 main 分支，并在 Settings 中设置了 main，仍然会出现一样的问题。

**Comment by guowei-gong** [comment]
针对问题一。**目前我使用 hugo 生成的静态页面，不存在这种问题**。

**Comment by guowei-gong** [comment]
Here is the static page generated by hugo.
![image](https://user-images.githubusercontent.com/62499904/218968457-f6a66758-d356-4b83-ae28-ea640e88f3d6.png)

To access the article, the address bar is where the red arrow points, not the article in the `post` folder generated by the other framework before.

**Comment by YunYouJun** [comment]
希望提供一个可复现链接与最小仓库。

**Comment by YunYouJun** [comment]
问题二：我认为你可能没有设置 `updated` 参数，在 github actions 国外机器上执行时的时间戳是国外时间，因此可能产生偏差。可以通过为每篇文章设置指定的 updated 参数解决。

问题一的 404 问题，可以检查下我的博客是否存在该问题（ yunyoujun.cn ），使用 valaxy 加 cloudflare pages 构建。

**Comment by YunYouJun** [comment]
如果问题已得到解决，我将关闭该 Issue。
