### ISSUE TITLE
About `defineSiteConfig` property `author.avatar`.

### ISSUE THREAD

**Issue by JobinJia** [YunYouJun/valaxy#183]
I haven't static url for `author.avatar`.  Can i use `import avatar from './assets/xxx.png' to set `auhtor.avatar` ? 
Example:
```ts
import avatar from './assets/avatar.png'
export default defineSiteConfig({
   author: {
     name: 'My Name',
     avatar: avatar
   }
}) 

```

**Comment by YunYouJun** [comment]
You can use `/xxx/yyy.jpg`.

And place `/xxx/yyy.jpg` in `public` folder.

**Comment by JobinJia** [comment]
I tried it, But it didn't work. 
Here is a simple [repo](https://stackblitz.com/edit/valaxy-fbawjh?file=pages%2Fpublic%2Fcat.svg,valaxy.config.ts)

**Comment by Rotten-LKZ** [comment]
It works well in my local computer when I set `avatar: '/cat.svg'` and put `cat.svg` in `public` folder. I think this problem may be caused by StackBlitz.

**Comment by YunYouJun** [comment]
You should create a new dir `public` with the same level as `pages`.

```bash
- public
- pages
```

And not use relative path. you should use absolute path.

If you have a file placed in `public`, like `public/avatar.png`.

And set it in `author.avatar: '/avatar.png'`.
