### ISSUE TITLE
feat: 移动端页面优化

### ISSUE THREAD

**Issue by Sknp1006** [YunYouJun/valaxy#188]
问题1：
类别与标签文字太长导致换行
![f354177726ff1eec1fe0646f43d6c4d0](https://user-images.githubusercontent.com/41496773/220224705-00e83775-07f2-48c2-889c-ee2eb5141493.jpg)
![69f971285c388ffc01662ef43c337a27](https://user-images.githubusercontent.com/41496773/220224708-f3036660-1137-4227-b032-54f2153f5eae.jpg)
问题2：
部分文字超出了屏幕
![微信图片_20230221092556](https://user-images.githubusercontent.com/41496773/220224740-3222dac3-3072-4836-a929-fd968e6de1e2.jpg)

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/220735570-c86aca89-4908-4ec5-9236-2b1c221263fd.png)

How about this?

**Comment by Sknp1006** [comment]
That's fine.
