### ISSUE TITLE
如何让首页列表 按文章更新时间(updated)排序？

### ISSUE THREAD

**Issue by hqw567** [YunYouJun/valaxy#190]
1. 如何让首页列表 按文章更新时间(updated)排序？
2. 是否考虑取消 手机端的  # 号 标识改变 （不要改变手机端的地址栏，否则会引起标题栏的抖动）

![image](https://user-images.githubusercontent.com/74847198/220831972-e7dd6bb2-c75b-46dd-a308-f2f4ff82d1cd.png)

https://user-images.githubusercontent.com/74847198/220832562-600e9220-c1d5-4c0d-900c-864480d093c0.mp4

**Comment by YunYouJun** [comment]
默认即按照 `updated` 排序。（可能存在边界情况造成了你的困惑，需要提供一个可复现案例以帮助我们定位问题。）

---

是否考虑取消 手机端的 # 号 标识改变？

标题栏的抖动是指顶部的标题出现与消失吗？这与 # 有关吗？
需要提供手机浏览器与复现方式。
也许存在移除 # 的其他解决方案。

**Comment by hqw567** [comment]
> 默认即按照 `updated` 排序。（可能存在边界情况造成了你的困惑，需要提供一个可复现案例以帮助我们定位问题。）
> 
> 是否考虑取消 手机端的 # 号 标识改变？
> 
> 标题栏的抖动是指顶部的标题出现与消失吗？这与 # 有关吗？ 需要提供手机浏览器与复现方式。 也许存在移除 # 的其他解决方案。

在Alook、百度手机浏览器中，有卡动的问题

https://user-images.githubusercontent.com/74847198/221725094-e4e7bfb7-e699-4a94-bd6d-0aa2aa760d4e.mp4
