### ISSUE TITLE
[問題] 如何取用 `unocssPresets` 設定？

### ISSUE THREAD

**Issue by kuohuanhuan** [YunYouJun/valaxy#191]
// 等等補上

**Comment by kuohuanhuan** [comment]
已解決。

參考：<https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy/node/types.ts>

**Comment by YunYouJun** [comment]
Thanks. Now, I updaed the docs. https://github.com/YunYouJun/valaxy/commit/7fdf3bb69a1a10c6cadcb1192a624a24b33f312b
