### ISSUE TITLE
bug: 当设置 FrontMatter 的 hide 属性时，文章不会渲染。

### ISSUE THREAD

**Issue by fanghsiu** [YunYouJun/valaxy#192]
![image](https://user-images.githubusercontent.com/79410512/222438134-ec1ae2b4-53dc-45f3-95d4-5e7c4ec7e71a.png)

根据文档 https://valaxy.site/guide/post 描述，无论 `hide` 值为什么，文章都会渲染并且可以直接访问链接。但在实际使用过程中，文章都不会渲染，导致无法查看。

这是我的仓库 https://github.com/fanghsiu/fanghsiu.github.io ，通过 GitHub Actions 部署在 gh-pages 分支上。我在 pages/posts 下有两个测试文件 hide-true.md 和 hide-index.md，`hide` 值分别设为 `true` 和 `index`。直接查看 gh-pages 分支，可以看到并没有生成相对应的文件。
![image](https://user-images.githubusercontent.com/79410512/222443891-e3d11954-3bd0-4357-8039-63b2ebfaedbe.png)
![image](https://user-images.githubusercontent.com/79410512/222444362-d474c7f6-459d-4b7e-b00a-60d98ca7a713.png)

**Comment by YunYouJun** [comment]
感谢反馈，已修复。
