### ISSUE TITLE
feat: layout options for albums and galleries

### ISSUE THREAD

**Issue by Yuumi0221** [YunYouJun/valaxy#198]
希望可以增加相册的内置页面模板，可以将[hexo-theme-yun](https://github.com/YunYouJun/hexo-theme-yun)的相册迁移过来

**Comment by Yuumi0221** [comment]
还有烟花点击特效也希望可以加回来，很可爱！

**Comment by YunYouJun** [comment]
> 还有烟花点击特效也希望可以加回来，很可爱！

可以分成两个 Issue，会分别关联对应的进度。
