### ISSUE TITLE
feat: Fireworks click effect

### ISSUE THREAD

**Issue by Yuumi0221** [YunYouJun/valaxy#199]
希望可以加入鼠标点击特效[Anime.js Fireworks canvas demo](https://codepen.io/juliangarnier/pen/gmOwJX)，用户可以在config.ts里自行设置开关和颜色。

**Comment by YunYouJun** [comment]
Feature added in https://github.com/YunYouJun/valaxy/commit/d84d03fb11a890589eb478044ef176e73332d81d.

```ts
// theme.config.ts
// ...
  fireworks: {
    enable: true,
    // 不设置 colors 选项，或通过 hex/rgba 颜色数值设置（透明度随机）
    colors: ['#66A7DD', '#3E83E1', '#214EC2']
  }
// ...
```
