### ISSUE TITLE
Bug: not overwrite the default config

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#20]
![valaxy.config.ts](https://user-images.githubusercontent.com/54099603/176988932-9caaccaf-1f68-4810-a5ae-a194b598bda9.png)

I configured the sponsor item in `valaxy.config.ts`. Although the result is effective, it seems to be merged with the sponsorship of the default configuration.

![resullt](https://user-images.githubusercontent.com/54099603/176988987-d7cd6da9-5146-44a1-ab23-22aed5f73696.png)

**Comment by YunYouJun** [comment]
> Will concat array values (if default property is defined)
> defu remarks: https://github.com/unjs/defu#remarks
