### ISSUE TITLE
请问在本地写好文章后需要每次提交嘛？

### ISSUE THREAD

**Issue by mewhz** [YunYouJun/valaxy#200]
刚刚从hexo转过来，我看到您这里使用了GitHub的actions功能自动构建了 gh-pages分支，那请问我每次写好文章都需要使用 git push命令把仓库推送一下，然后Actions再自动构建嘛？有没有类似于 hexo 中 hexo d -g 可以直接提交的命令呀。
感谢您的回复~

**Comment by YunYouJun** [comment]
`git push` 后交由 GitHub Actions 自动构建，我认为这是一个更好的实践。
一来可以备份你的文章内容，二来部署环境一致且无需占用本地的 build 时间。

---

也可通过自己本地部署，`npm i gh-pages`，`package.json` 添加缩写脚本：

```json
"scripts": {
  "deploy": "npm run build && gh-pages -d dist"
}
```

部署执行 `npm run deploy` 即可。（不过还是最推荐第一种方案）

**Comment by mewhz** [comment]
> `git push` 后交由 GitHub Actions 自动构建，我认为这是一个更好的实践。 一来可以备份你的文章内容，二来部署环境一致且无需占用本地的 build 时间。
> 
> 也可通过自己本地部署，`npm i gh-pages`，`package.json` 添加缩写脚本：
> 
> ```json
> "scripts": {
>   "deploy": "npm run build && gh-pages -d dist"
> }
> ```
> 
> 部署执行 `npm run deploy` 即可。（不过还是最推荐第一种方案）

好的，非常感谢您的建议，我决定继续使用 git push 的方法来进行提交，可能是刚从 hexo 转过来的缘故，有些设置还不是很习惯。
