### ISSUE TITLE
[功能建议] 建议归档页不统计已隐藏文章的计数

### ISSUE THREAD

**Issue by akiting01** [YunYouJun/valaxy#202]
作者，你好！ヾ(Ő∀Ő๑)ﾉ
在编写博客页面时，有一个可选的 `隐藏` 属性（即 `FrontMatter` 中的 `hide` 属性设置为 `all` ）。选择后文章渲染但不在主页以及归档等其他页面显示，但查看归档等相关页面时，仍会统计其计数，这与 `隐藏页面` 这一设计理念不合。故希望可以修改此处判断逻辑。

框架版本：0.14.17
主题：yun
主题版本：0.14.17

**Comment by YunYouJun** [comment]
将在下个版本修复，顺带一提如果 `hide: index`，则只会在首页隐藏，但归档页仍然显示，所以会正常统计。

**Comment by akiting01** [comment]
好的，了解！
