### ISSUE TITLE
当md文件过大时，会报错[plugin:vite:vue] Element is missing end tag.

### ISSUE THREAD

**Issue by xuegao-tzx** [YunYouJun/valaxy#204]
如图所示：
`[plugin:vite:vue] Element is missing end tag.`
<img width="463" alt="图片" src="https://user-images.githubusercontent.com/86029709/229348019-8e07d4ee-7d45-4ab3-82b4-f403b4b2aaf3.png">
<img width="1049" alt="图片" src="https://user-images.githubusercontent.com/86029709/229348114-070dd52a-1841-4d61-b075-9c862a79214d.png">
<img width="899" alt="图片" src="https://user-images.githubusercontent.com/86029709/229348154-c39ee402-1a17-4d00-b520-fc430d167975.png">

**Comment by xuegao-tzx** [comment]
同样的md文件在hexo中是正常的

**Comment by YunYouJun** [comment]
请提供源文件内容。

**Comment by xuegao-tzx** [comment]
> 请提供源文件内容。

已加您好友，望通过一下，我给您私发

**Comment by YunYouJun** [comment]
和文件过大无关，文章中存在多处未闭合的标签。如 `<type>`/`<name>` 等，须使用反引号 ` 将标签括起来。

hexo 可以是因为 hexo 不支持直接嵌入 vue 组件，而 valaxy 支持在 md 中渲染 Vue 组件，同时依赖于 Vue 的编译（Vue 不支持未闭合组件的渲染），此外不闭合无法区分究竟是一个组件还是文本以何种方式渲染，应当使用更标准的写法。
