### ISSUE TITLE
bug: 更新 0.14.24 后出现禁忌的三重标题

### ISSUE THREAD

**Issue by Yuumi0221** [YunYouJun/valaxy#206]
更新 0.14.24 后，使用数组表示博客标题会出现三重标题，边栏的页面图标也出现了三次！
![禁忌的三重标题](https://user-images.githubusercontent.com/59047663/229525481-7b7cf8dd-5f97-45c2-8869-3342cbd7f42a.png)

测试发现注释掉 addonWaline 和 addonComponents 后可恢复正常（注释掉一个少一重），已在 [demo](https://stackblitz.com/edit/valaxy-vehang?file=valaxy.config.ts) 复现。

**Comment by YunYouJun** [comment]
Fixed in `v0.14.25`.
