### ISSUE TITLE
bug: social 无法被覆盖，配置变得异常

### ISSUE THREAD

**Issue by hairyf** [YunYouJun/valaxy#208]
配置：

![image](https://user-images.githubusercontent.com/49724027/230295556-ab29c04c-d975-44a2-a601-7645852831e1.png)

结果：

![image](https://user-images.githubusercontent.com/49724027/230295608-38fbf307-083c-43e4-9d86-75c53b1f2e6d.png)

与 yun siteCofng 合并 social

期望：

demo/valaxy.config.ts 中数组配置应该覆盖默认配置，或者说不应该存在默认的 siteConfig 配置

复现：

https://github.com/TuiMao233/valaxy-theme-hairy/tree/next

**Comment by YunYouJun** [comment]
目前并不存在默认的 social 配置。

**Comment by TuiMao233** [comment]
那应该怎么解释这个情况，目前 social 有两份，另一位是 yun siteConfig 的，一份是我配置的，如何解释 yun siteCofng 中 social 会和用户配置并存

**Comment by TuiMao233** [comment]
知道问题了，site.config.ts 配置与 valaxy.config.ts 配置合并导致，如果这是合理的，可以关闭掉这个问题

**Comment by YunYouJun** [comment]
`site.config.ts` 与 `valaxy.config.ts` 中的 siteConfig 只保留一份。

目前你是只在用户目录进行配置对吗？那样的话，我认为是合理的。

**Comment by hairyf** [comment]
并不是，我在 valaxy.config.ts 中定义 siteConfig，后 social 与 site.config.ts 合并
> 再此重新打开这个问题

**Comment by YunYouJun** [comment]
valaxy.config.ts 中的 `siteConfig` 与 `site.config.ts` 的作用时相同的，只需要有一处存在。

目前的策略会将 `site.config.ts` 中的配置合并进 `valaxy.config.ts` 中的 `siteConfig` 中。
