### ISSUE TITLE
Bug: pages generation

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#21]
Accessing the /links page means accessing /links html. Accessing /about means accessing /about html. Accessing /post/xxx means accessing /post/xxx html.
However, I want /xxx/xxx/index,html. In this way, almost all servers can support access pages without `HTML` suffix.

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/valaxy/commit/4ec69fc2d805283f3e92561502e11f7ceee1cfa0.
