### ISSUE TITLE
Can't customize Waline's Emoji sets

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#211]
Just like the title, the emoji sets cannot be customize because this:
![image](https://user-images.githubusercontent.com/76810494/233754235-514ade71-ee0e-4227-aa00-e7131edd05f1.png)

**Comment by YunYouJun** [comment]
Now, you can custom types.

```ts
/**
 * Get emojis cdn path
 * @param cdn
 * @param types
 * @returns
 */
export function getEmojis(cdn = '//unpkg.com/', types = ['bilibili', 'qq', 'weibo']) {
  return types.map(type => `${cdn}@waline/emojis/${type}/`)
}
```

**Comment by fanghsiu** [comment]
@YunYouJun 这不是一个有效的修复，没有提供 types 的设置入口。
应在`types/index.ts`添加该接口，同时在`components/WalineClient.vue`使用此函数时添加该参数。

为什么不使用 waline 的 emoji 选项来配置，而是再写一个函数 ?

**Comment by YunYouJun** [comment]
应当仍然可以通过 emoji 选项进行配置。函数只是为了方便默认配置。
