### ISSUE TITLE
PWA compatibility

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#212]
ref: https://github.com/Big-Cake-jpg/big-cake-jpg.github.io/commit/f57d29fb6707ffd34b3bae994c31f23b4194adfd

**Comment by YunYouJun** [comment]
The method of your usage is wrong, you can refer to the document.

https://valaxy.site/guide/third-party/vite-vue#%25E4%25BD%25BF%25E7%2594%25A8-vite-plugin-pwa
