### ISSUE TITLE
是否能降低对markdown的语法检查严格程度？

### ISSUE THREAD

**Issue by dbinfun** [YunYouJun/valaxy#214]
当markdown书写不规范时`valaxy`会报错,

如下面这个markdown文件

```markdown
<key>
```

当一个标签只有前半部分时,会报错`[plugin:vite:vue] Element is missing end tag.`

虽然可以通过转义的方式解决：

```markdown
\<key\>
```

然而其在HEXO 下会被直接解析为以下html

```html
<key></key>
```

**Comment by YunYouJun** [comment]
这是由于走了一遍 Vue 的渲染，因此可以在文章中直接插入 Vue 组件。
而 Hexo 不支持插入组件，所以没有做这个限制。

暂时没有想到别的更好的办法，除非 @vitejs/plugin-vue 关闭对 Vue 组件的闭合标签检查。
