### ISSUE TITLE
build 阶段：posts 目录下的文件或文件夹，含有中文名时，会导致直接访问其URL时，返回 404 

### ISSUE THREAD

**Issue by zmxlt** [YunYouJun/valaxy#215]
复现
1. 在 posts 目录下创建 `测试.md` 文件。
2. npm run build
3. 在 dist 目录下，开启一个 http-server
4. 访问主页，点击文章， 此时正常访问文章， 其 url 为 `http://192.168.100.192:8080/posts/%E6%B5%8B%E8%AF%95` 
5. 复制 url ，直接使用此 url 访问， 返回 404

原因： 

在 build 阶段， 含有中文的文件，会进行编码，生成 `./posts/%E6%B5%8B%E8%AF%95.html` 的文件。

浏览器访问带有编码的URL 会自动进行解码， 请求解码后的文件。

直接访问带有编码 url `./post/%E6%B5%8B%E8%AF%95.html`  时，实际上是访问解码后的 url 路径 ，即 `./测试.html`， 服务器上只有 `./post/%E6%B5%8B%E8%AF%95.html` 文件，

 因此无法找到文件， 返回 404

**Comment by dbinfun** [comment]
不知道是不是路由的问题，如果使用nginx做反向代理，在网络较慢的情况下(某些资源还未加载完毕)，直接点击文章也会出现404的情况。

**Comment by YunYouJun** [comment]
> 不知道是不是路由的问题，如果使用nginx做反向代理，在网络较慢的情况下(某些资源还未加载完毕)，直接点击文章也会出现404的情况。

意思是网络不慢就可以正常访问了？

**Comment by dbinfun** [comment]
> > 不知道是不是路由的问题，如果使用nginx做反向代理，在网络较慢的情况下(某些资源还未加载完毕)，直接点击文章也会出现404的情况。
> 
> 意思是网络不慢就可以正常访问了？

是的，使用nginx的时候，如果网速较慢，部分资源未加载完毕，点击博客会直接向nginx请求对应的链接，所以会返回404，我这里有一个例子[https://dbin.site/](https://dbin.site) ，在所有资源加载完毕后，点击任意一篇文章可以正常进入，如果没有加载完毕直接点击文章可能会404，但是，即便正常进入文章，如果刷新当前文章也会返回404，edge浏览器版本112.0.1722.68,nginx版本 nginx/1.14.0 (Ubuntu)

**Comment by zmxlt** [comment]
> 本地构建测试无法复现。规则应该是访问到了 ./posts/%E6%B5%8B%E8%AF%95.html 。

是， 我描述里省略了 `./posts/` 

直接访问 `https://domain/posts/%E6%B5%8B%E8%AF%95.html` 无法访问

**Comment by YunYouJun** [comment]
@zmxlt 描述一下后续，可以关 issue 了。

**Comment by zmxlt** [comment]
解决方案： 在 `blog/pages/` 目录下 添加 `404.md`  可解决此问题。

问题原因： 找不到中文名称的 HTML 文件

此方案能解决问题的说明：

1. 含有中文名的路径，确实找不到，服务器接到含有中文编码的url，会进行解码还原
2. 虽然找不到，但此时服务器上有个 404.html，所以服务器默认会返回了 404.html
3. 404.html 获取后，开始加载资源，可以看到 app-xxx.js 和 404-xxx.js 被加载了
4. 因为是单页面，所以又会触发前端路由
5. 进行前端路由查询匹配， 此时数据从 测试-xxx.js 中获取
6. 最后又正常显示

**Comment by mirari** [comment]
现在默认就存在404.md
但是页面部署到github pages后，打开中文地址会先瞬间显示404页面，再跳转到正常内容。
在network里可以看到第一次请求还是返回了404，这个结果码会导致google adsense等分析工具认为页面跳转失败了，不知道还有没有更好的解决办法

**Comment by z-xl-t** [comment]
个人层面最好的解决办法是不用中文命名文件 （确信）

另一个方法，等一个有缘开发者来贡献解决，支持在渲染生成阶段，同时生成不被编码的 中文名.html 文件。这样就能确保在访问静态服务器时找到对应文件了。

**Comment by YunYouJun** [comment]
https://yun.valaxy.site/posts/中文post测试

测试一下这个中文链接，之前我记得修复了，现在应该是不闪的。

**Comment by mirari** [comment]
这个链接我昨天试了也是正常的，自己的项目本地部署打开也是正常的，但是部署到Github Pages上就会404，。

现在已经全部改成英文名了

**Comment by YunYouJun** [comment]
可能是 github pages 的规则不一样 ། – _ – །

**Comment by lkyu-ly** [comment]
我的post中含有大量中文名称的md（实在不会起英文名就摆烂了）使用vercel从github克隆构建，不存在404问题
