### ISSUE TITLE
feat: `valaxy-addon-lightgallery` 支持所有页面

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#217]
作为一个图像预览 Addon，`valaxy-addon-lightgallery` 应该是可用于 `layout: post` 的文章页面的，而不仅限于 album 画廊页面。

如果为了一个文章里的图像预览要修改许多文章页面的 layout 属性，我认为是不合适的。

**Comment by YunYouJun** [comment]
没错，它其实是支持所有页面的，只需要插入对应组件即可 `<VAGallery :photos="photos" />`。

**Comment by YunYouJun** [comment]
我添加了如何在文章中直接使用。

If you are interested in translating into English, welcome PR!

https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-lightgallery#%E5%9C%A8%E6%96%87%E7%AB%A0%E4%B8%AD%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8
