### ISSUE TITLE
bug: 启用 fuse 本地搜索后友链页面的页面漂移

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#218]
### 问题描述 Description

在移动端布局下，进入到友链页面并点击搜索按钮会发现原本为一栏排列的友链变成了多栏排列，这可能会导致 PageSpeed Insights 中与 CLS 有关的项目出现问题。

### 运行环境 Environment

浏览器 Browser：Microsoft Edge / Safari on iOS

操作系统 Operating System: Windows 11 Insider Preview Canary 25352 / iOS 16.5 Beta

Node.js: v16.0

Valaxy: 0.14.28

主题 Theme: Yun 0.14.28

部署方式 Deploy on: Cloudflare Pages

### 附件

https://user-images.githubusercontent.com/76810494/235440142-e6433e1d-d418-453b-9562-84a802d2567e.MOV

**Comment by YunYouJun** [comment]
无法复现，是否有最小可复现仓库代码？

**Comment by Big-Cake-jpg** [comment]
> 无法复现，是否有最小可复现仓库代码？

https://github.com/Big-Cake-jpg/big-cake-jpg.github.io

**Comment by YunYouJun** [comment]
It seems works well now.
