### ISSUE TITLE
Bug:在Windows(10 和11) 下生成RSS不兼容

### ISSUE THREAD

**Issue by dbinfun** [YunYouJun/valaxy#227]
相同代码和相同node环境在Ubuntu上可正常生成RSS，但在Windows上生成的RSS信息中缺少文章信息。

版本和环境信息:

- valaxy:`0.14.28`
- node: `16.17.1`
- npm: `9.6.6`
- pnpm:`8.5.0`
- windows: `Win11 22H2 22621.1702` 执行策略:`RemoteSigned`

**Comment by YunYouJun** [comment]
该问题由 windows 路径风格引起，通过转换为 posix 路径风格解决。

> https://nodejs.org/api/path.html

Released in v0.14.30.
