### ISSUE TITLE
Broken layout with toc

### ISSUE THREAD

**Issue by Mister-Hope** [YunYouJun/valaxy#233]
### Describe the bug

![image](https://github.com/YunYouJun/valaxy/assets/33315834/17264e69-2710-46b2-b1a2-becf7cf7d85a)

Toc items are covered by navbar. testing width 1140px

### Reproduction

https://valaxy.site/guide/why

### System Info

```Shell
Not needed
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Fixed.
