### ISSUE TITLE
Gap in navbar link and its dropdown item

### ISSUE THREAD

**Issue by Mister-Hope** [YunYouJun/valaxy#235]
### Describe the bug

When moving very slowly from dropdownlink to it's pop menu on pc, the dropdown menu will be hidden because of gaps between 2 elements. See video below

https://github.com/YunYouJun/valaxy/assets/33315834/4407d37b-838c-4352-a639-69005df2ad54

### Reproduction

https://valaxy.site/guide/third-party

### System Info

```Shell
Not needed
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Fixed.
