### ISSUE TITLE
侧边文章目录太长会展示不全 

### ISSUE THREAD

**Issue by dbinfun** [YunYouJun/valaxy#238]
### Describe the bug

[#142 ](https://github.com/YunYouJun/valaxy/issues/142) 有人提到这个问题，但好像并未修复该问题
侧边文章目录太长展示不全，我写了一篇目录很长的文章，目录不会出现滚动条，发现云游君[做猪呢，最重要的是开心](https://yunyoujun.cn/posts/2020-summary) 这篇文章也出现了这个问题

### Reproduction

https://yunyoujun.cn/posts/2020-summary

### System Info

```Shell
`Win11`, `Chrome 114.0.5735.110`
```

### Used Package Manager

pnpm

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
感谢反馈，已修复。
