### ISSUE TITLE
Failed to resolve package valaxy-theme-yun/package.json

### ISSUE THREAD

**Issue by mewhz** [YunYouJun/valaxy#239]
重新创建一个 valaxy 项目
依次输入：
pnpm create valaxy
![image](https://github.com/YunYouJun/valaxy/assets/48837161/faa8e213-47fa-41e9-baf9-680f5c784535)
![image](https://github.com/YunYouJun/valaxy/assets/48837161/3915dd34-2318-4473-868a-9ae7068114f4)
![image](https://github.com/YunYouJun/valaxy/assets/48837161/ef676908-f8e0-4d91-b55f-7ae8e3cf245e)
切换到博客目录，输入：valaxy 命令
虽然能成功运行，但是会报错
![image](https://github.com/YunYouJun/valaxy/assets/48837161/bfdda82f-2ece-4f1e-a261-9011347d1d61)
再次切换到 posts 目录，输入：valaxy new "hello" 命令，会直接报错，且不会创建新的 .md 文件
![image](https://github.com/YunYouJun/valaxy/assets/48837161/fa025fdc-11d4-41c3-af81-2310224ef898)
![image](https://github.com/YunYouJun/valaxy/assets/48837161/5e51b97a-39b0-469f-ae90-8f6261d3732c)

**Comment by mewhz** [comment]
好的，非常感谢您，在根目录执行后确实成功创建了文件，但是依然有报错。请问这个报错的原因是什么呀？

**Comment by YunYouJun** [comment]
截图看一下这时候是什么报错？

**Comment by mewhz** [comment]
> 截图看一下这时候是什么报错？

您好，还是这样的报错，但是博客的 md 文件会正常创建
![image](https://github.com/YunYouJun/valaxy/assets/48837161/3e9b3d3d-05f3-4f37-a2a9-ae7d8e92caa5)

**Comment by YunYouJun** [comment]
I will fix it in this weekend.

**Comment by YunYouJun** [comment]
![image](https://github.com/YunYouJun/valaxy/assets/25154432/ed14a005-2b37-4d9c-88a2-61c3508fe74c)

Now, it works well. `v0.14.37`.
