### ISSUE TITLE
How to move friend links to footer?

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#242]
Just like the title.

I want to write a Vue Template named `FooterLink.vue` and insert it to `YunFooter.vue` to add dynamic and random friend links and keep the contents in footer, but I have less Vue.js basic.

Can you help me to achieve it? Thank you very much.

The effect is as the images showing below.

Exist footer:
![image](https://github.com/YunYouJun/valaxy/assets/76810494/66fd3b7b-4f5b-4015-a3cc-1f1ee58933a1)

Result:
![image](https://github.com/YunYouJun/valaxy/assets/76810494/885a179b-77c0-4443-b5f9-02bdcb4962f6)

**Comment by YunYouJun** [comment]
Insert it like this. So easy.

https://github.com/YunYouJun/yunyoujun.github.io/blob/valaxy/components/YunFooter.vue

**Comment by Big-Cake-jpg** [comment]
> Insert it like this. So easy.
> 
> 
> 
> https://github.com/YunYouJun/yunyoujun.github.io/blob/valaxy/components/YunFooter.vue

I actually know how to insert components. The only problem is that I can't write the template source file `FooterLink.vue`.

**Comment by YunYouJun** [comment]
I don't understand your question. Just put `FooterLink.vue` in the components folder.

**Comment by Big-Cake-jpg** [comment]
> I don't understand your question. Just put `FooterLink.vue` in the components folder.

I mean that can you give me an example of `FooterLink.vue` file (code)? Because I don't have any Vue basic.

---

我的意思是说，可以向我展示一份 `FooterLink.vue` 的示例代码吗？因为我没有 Vue 基础，无法自行编写 Vue Component。

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/yunyoujun.github.io/blob/valaxy/components/CdnLogo.vue

Like this, and send your request to ChatGPT.

**Comment by iam0range** [comment]
ok
