### ISSUE TITLE
Valaxy文章中Waline无法正确渲染Markdown语法

### ISSUE THREAD

**Issue by Gatsby0108** [YunYouJun/valaxy#243]
### Describe the bug

在waline评论区中，标题、有序、无序列表等markdown语法似乎不能得到正确的渲染，而在waline的后台管理控制台中是可以正确渲染这些语法的。这一点在云游君的个人网站以及其他一些采用valaxy的网站评论区也有体现。

![image](https://github.com/YunYouJun/valaxy/assets/80799614/60d48355-d145-4b23-9f9c-6430a31b89b8)

### Reproduction

https://www.yunyoujun.cn/posts/home-firework-red-bag

### System Info

```Shell
`Windows NT 11.0`, `Chrome114.0`
```

### Used Package Manager

pnpm

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/valaxy/commit/08304841ccfb331dc7994f2a1ea7ddd9543959c0
