### ISSUE TITLE
请问文章更新时间是否可以自定义？

### ISSUE THREAD

**Issue by mewhz** [YunYouJun/valaxy#245]
最近更新文章的时候，发现有的时候修改了一些小小的语法错误或其他问题，但是不想显示修改时间；
或者有一些当天写完的文章，然后提交后又做了一点改动，就会出现当天发布当天修改的情况。
请问这种情况是否可以支持自定义文章的更新时间
![image](https://github.com/YunYouJun/valaxy/assets/48837161/6d63d98a-f985-4643-8276-3347fac402a1)
![image](https://github.com/YunYouJun/valaxy/assets/48837161/d59ed776-3862-48ac-876a-1bbebb8f6ea7)

**Comment by YunYouJun** [comment]
```bash
updated: xxxx
```

**Comment by mewhz** [comment]
> ```shell
> updated: xxxx
> ```

谢谢您，请问有这种文章页设置的所有参数列表吗？

**Comment by YunYouJun** [comment]
可参见 https://valaxy.site/guide/page

目前没有在文字中一一列出来，更多参数可参见类型：

- https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy/types/posts.ts#L27
- https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy/types/posts.ts#L144
