### ISSUE TITLE
[BUG] Fireworks click position error when zoom in Safari

### ISSUE THREAD

**Issue by Tohrusky** [YunYouJun/valaxy#247]
### Describe the bug

https://github.com/YunYouJun/valaxy/issues/199
小云小云，抄作业时突然发现Safari缩放时，烟花定位会错误！苹果真是太坏了！
<img width="390" alt="image" src="https://github.com/YunYouJun/valaxy/assets/65994850/0a263b98-9f6f-41d1-bd44-77b87988e275">

### Reproduction

挂上组件，打开macOS Safari / iOS 套壳Safari浏览器，启动烟花🎆！

### System Info

```Shell
Safari
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
复现了，TODO。

**Comment by YunYouJun** [comment]
不过试了下，Chrome 倒是没问题。

**Comment by Tohrusky** [comment]
确实，所以说苹果实在是太坏了！iOS强制用Safari

**Comment by YunYouJun** [comment]
已修复，顺带抽了个 fireworks 的包。

https://www.npmjs.com/package/@explosions/fireworks

**Comment by Tohrusky** [comment]
好耶，这下更方便抄力🤤
