### ISSUE TITLE
[功能建议] 可以追加文章密码访问和相册密码访问功能吗

### ISSUE THREAD

**Issue by blackgold-saw** [YunYouJun/valaxy#248]
云游君你好！

首先感谢大佬让我一个前端小白也成功建立起自己的博客。
之前我一直用的hexo-yun，最近才迁移到valaxy。
请问原来hexo里有的【文章密码访问】和【相册密码访问】功能是还没有搬到valaxy里吗？
如果可以的话请追加一下这两个功能。

框架版本：0.14.45
主题：yun
主题版本：0.14.45

**Comment by YunYouJun** [comment]
这部分功能还没有添加，这周末加上（

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/valaxy/assets/25154432/882a41f8-1dea-4759-897d-92f1cf04df05

功能已添加，文章和相册作为文章内容可以复用加密功能。
后续还有个想法是，提供加密区块组件，加密文章中部分内容。

**Comment by YunYouJun** [comment]
Released in `v0.14.46`.
