### ISSUE TITLE
Twikoo部署到云端评论区是白的

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#252]
### Describe the bug

Twikoo部署到云端评论区是白的，本地测试没有问题
![控制台图片](https://github.com/YunYouJun/valaxy/assets/103258286/1bf79d36-34ac-4230-a70a-a9535177eb65)

### Reproduction

Twikoo部署到云端评论区是白的，本地测试没有问题

### System Info

```Shell
Chrome，手机浏览器
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
感谢反馈，已在 v0.14.59 中修复。

**Comment by MengNianxiaoyao** [comment]
> 感谢反馈，已在 v0.14.59 中修复。

还没发版本对吗？目前npm版本还在0.14.48

**Comment by YunYouJun** [comment]
之前的版本有点小问题，目前发到了 `0.14.53`。
