### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#253]
### Describe the bug

使用0.14.53版本，编译ssg阶段报错
![image](https://github.com/YunYouJun/valaxy/assets/103258286/4b484cdf-5c29-4a1c-9d8e-fa617953c279)

### Reproduction

编译ssg阶段报错

### System Info

```Shell
win
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MengNianxiaoyao** [comment]
发现问题所在，addons我有些是不使用的，所以没有安装

**Comment by YunYouJun** [comment]
Will fix it asap.

**Comment by YunYouJun** [comment]
Fixed it in 0.14.54.
