### ISSUE TITLE
can't init valaxy white "pnpm create valaxy" in a created repo

### ISSUE THREAD

**Issue by LoTwT** [YunYouJun/valaxy#254]
### reproduction steps

- reinit a created repo
- delete all previous files
- `pnpm create valaxy`
- input infos af following

<img width="1493" alt="image" src="https://github.com/YunYouJun/valaxy/assets/50254496/3f13de8d-d072-4493-bc20-c98e909d04f8">

- try to output system info and it doesn't work

<img width="1263" alt="image" src="https://github.com/YunYouJun/valaxy/assets/50254496/2eb3558e-a026-4ff8-a5c7-a174e2a39b5e">

### also

I don't want to add `name` in the `package.json`, but it's required in the create scripts. Can it be optional?

### Reproduction

see above

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.14 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/Library/Caches/fnm_multishells/74036_1691985767185/bin/node
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/74036_1691985767185/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Thanks for your feedback, the new cli `v0.15.0` had been released.
