### ISSUE TITLE
编译完成后发现twikoo发送键有问题

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#255]
### Describe the bug

![image](https://github.com/YunYouJun/valaxy/assets/103258286/5d3f1a64-a726-4b6f-b6e9-81932014cec5)
编译后会参杂此css样式，导致twikoo输入文字后发送键背景颜色变为透明

### Reproduction

在`index.scss`中覆写关于此部分的样式解决

### System Info

```Shell
win
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MengNianxiaoyao** [comment]
![image](https://github.com/YunYouJun/valaxy/assets/103258286/7729319d-4904-44dc-87c5-bdb3ce30463a)
如图，覆写解决

**Comment by MengNianxiaoyao** [comment]
然而在编译后的文件里找此样式代码找不到，不编译直接运行dev网页访问，此样式也是不存在且不存在上述情况（即按钮正常）。但编译后运行serve，网页访问却是存在此样式，问题也是存在。

**Comment by MengNianxiaoyao** [comment]
上面的问题图片是我覆写css样式解决问题后的截图，实际css样式`background-color`并没被取消也生效

**Comment by YunYouJun** [comment]
Fixed.

See https://unocss.dev/guide/style-reset#tailwind-compat .
