### ISSUE TITLE
Integration for `vanilla-lazyload`

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#256]
### Clear and concise description of the problem

To optimize the speed of the site, I think we can add [`vanilla-lazyload`](https://github.com/verlok/vanilla-lazyload) to defer loading of the images.

This will greatly improve loading speed of the site on slow network connections and you may also get higher `PageSpeed Insights` scores.

### Suggested solution

Intergrate with `vanilla-lazyload` package for images or iframe.

https://github.com/verlok/vanilla-lazyload

### Alternative

Use native `loading="lazy"`.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
Some details need to be discussed.

For users, will they want to control some images to lazyload or not?
We should enable lazyload or not by default.

Lazyload should be global? Or uses use `<LazyImage />` by manual.

**Comment by YunYouJun** [comment]
I prefer to use native `loading="lazy"`.

**Comment by Big-Cake-jpg** [comment]
> Some details need to be discussed.
> 
> 
> 
> For users, will they want to control some images to lazyload or not?
> 
> We should enable lazyload or not by default.
> 
> 
> 
> Lazyload should be global? Or users use `<LazyImage />` by manual.

For Markdown source files preview and migration purposes, I think we shouldn't use Vue Components to make images lazyload.

Lazyload can hugely improve page loading time, so I think users will definitely enable global images lazyload. Here is a blog example using Hexo & hexo-theme-icarus, with self-integrated `vanilla-lazyload` to make images lazyload.

Because `vanilla-lazyload` required us to import another JavaScript file, so I think it should be disabled by default.

**Comment by Big-Cake-jpg** [comment]
> I prefer to use native `loading="lazy"`.
> 
> 
> 
> Like this:
> 
> 
> 
> https://github.com/YunYouJun/hexo-theme-yun/blob/742e37e5f59a654abc189fd8ceb1358ff547de68/docs/guide/config.md?plain=1#L1153

`loading="lazy"` seems no effect on desktop browsers like Chrome / Edge. So I prefer to use `vanilla-lazyload`, it also has a npm package for Valaxy to install, import and develop.

**Comment by YunYouJun** [comment]
Markdown It plugin [markdown-it-image-lazy-loading](https://github.com/ruanyf/markdown-it-image-lazy-loading) can be used directly.

`loading="lazy"` is introduced by chrome. https://web.dev/browser-level-image-lazy-loading/
Why do you think it doesn't work? Perhaps it's the illusion that images are less preloaded.

**Comment by YunYouJun** [comment]
Maybe we also can use [markdown-it-image-figures](https://github.com/Antonio-Laguna/markdown-it-image-figures) + vanilla-lazyload.

**Comment by YunYouJun** [comment]
OK, i think we can enable `loading="lazy"` by default, and allow users to enable `vanilla-lazyload` by manual.

**Comment by YunYouJun** [comment]
Do you want to try to realize this PR? I can provide some technical support on the development.

Or I'm going to do it this weekend.

**Comment by Big-Cake-jpg** [comment]
> Do you want to try to realize this PR? I can provide some technical support on the development.
> 
> Or I'm going to do it this weekend.

Humm, maybe I can try, but I don't have enough time to do this, and I have less Vue development experience. I'm in senior high now, haha.

> loading="lazy" is introduced by chrome. https://web.dev/browser-level-image-lazy-loading/
> Why do you think it doesn't work? Perhaps it's the illusion that images are less preloaded.

Well, when I scroll the webpage on my Windows PC, I found that the images have already loaded, I've checked the DevTools waterfall. In this way, I don't want to use `loading="lazy"`.

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/valaxy/pull/266
