### ISSUE TITLE
自定义代码高亮配置无效

### ISSUE THREAD

**Issue by dbinfun** [YunYouJun/valaxy#257]
### Describe the bug

在`valaxy.config.ts`中按照[shiki](https://github.com/shikijs/shiki/blob/main/docs/themes.md#all-themes)提供的主题添加如下配置:
```ts
markdown:{
      theme:{
        light: 'material-theme-lighter',
        dark: 'material-theme-darker'
      }
    }
```
发现两种模式都仍然是暗色主题，有变化，但是变化不大，配置不生效。

### Reproduction

无

### System Info

```Shell
valaxy: `0.14.54`
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dbinfun** [comment]
@YunYouJun 自定义代码高亮无论如何配置代码背景色都是黑色吗？我配置如下：
```js
markdown:{
      theme:{
        light: 'github-light',
        dark: 'solarized-dark'
      }
    }
```
虽然高亮样式随着夜间和日间变化,但是在日间模式下，代码背景没有因为我设置`light`为`github-light`而改变(期望为白色背景，实际为黑色背景)

valaxy 和yun主题版本皆为`0.14.56`

**Comment by YunYouJun** [comment]
<img width="697" alt="截屏2023-09-06 23 59 08" src="https://github.com/YunYouJun/valaxy/assets/25154432/d81dd0fa-f9db-474f-a8db-8d6c9cc881a2">

Fixed in `0.14.57`.
