### ISSUE TITLE
如何在文章中优雅地插入图片？How to insert images gracefully in the posts?

### ISSUE THREAD

**Issue by mirari** [YunYouJun/valaxy#259]
优雅是指含有图片的markdown文章，在编辑器与网页中可以获得一致的浏览效果。

hexo也存在这样的痛点，就是无法在Typora等第三方编辑器中实现所见即所得。
```
{% asset_img 1.jpg %}
```
像这样的写法在编辑器中无法直观地看到图片。
而且兼容性不佳，比如现在迁移就遇到了不得不逐个修改图片引用语法的问题。
另外，通常我会更习惯将剪贴板中的图片通过Typora直接粘贴。
此时Typora会自动将图片保存到同目录或文章同名目录下，并生成`![foo](bar/1.png)`这样的语法。
这样的好处是markdown文件本身兼容性最佳，不管是Typora还是IDE都可以直接正常展示图片，但偏偏在编译后无法正常显示。

虽然可以将图片放到public目录下作为静态文件。但图片与文章的相对路径在编译打包后会改变。也就是说要么网页能正常展示，要么编辑器能正常展示，两者无法兼得。而且这样图片与文章位置太远，操作移动时也会比较麻烦。

所以我现在的做法是被迫在文章写完后，用正则替换将所有markdown图片语法替换成html语法。
```
!\[.*\]\((.*)\)
```
```
<div><img src="$1"></div>
```

好处是编辑器与网页都能正常展示了。
缺点是如果想在不支持html的阅读器上展示，还得再批量将图片转换为markdown语法。

不知道能否在编译层面将markdown中的图片相对路径处理为网页编译后的静态文件路径，这样就可以确保以markdown语法保存的图片可以在各端浏览效果一致了。

**Comment by z-xl-t** [comment]
假设你的博文为 test.md

现在你可以创建一个 test 文件夹， 博文重命名为 index.md, 图片放在这个文件夹里。

然后使用相对路径引用图片。这是我目前的做法。

![image](https://github.com/YunYouJun/valaxy/assets/25658690/dc4183a4-1171-4fc7-8d51-cda8710a1d9d)

**Comment by mirari** [comment]
非常感谢，已经全部修改成这种形式了。
这种方式更低耦合，迁移时整个目录一起挪走就行。

**Comment by YunYouJun** [comment]
> 假设你的博文为 test.md
> 
> 现在你可以创建一个 test 文件夹， 博文重命名为 index.md, 图片放在这个文件夹里。
> 
> 然后使用相对路径引用图片。这是我目前的做法。
> 
> ![image](https://user-images.githubusercontent.com/25658690/265197975-dc4183a4-1171-4fc7-8d51-cda8710a1d9d.png)

确实，感觉这种结构最合理。

@z-xl-t 来补个最佳实践文档？

**Comment by YunYouJun** [comment]
OK，加上了。Issue 就先关了。

https://github.com/YunYouJun/valaxy/commit/26bc1085cdeabeebff6a37d54f719d9a33ccfa04#diff-c742b547e9cf1f763fa82d6e8d8bec93f0e203e30c2e095acc3318a35f95bcd1

**Comment by z-xl-t** [comment]
好，我进行补充。
