### ISSUE TITLE
feature: collapse for code 实现代码框折叠

### ISSUE THREAD

**Issue by YunYouJun** [YunYouJun/valaxy#262]
### Discussed in https://github.com/YunYouJun/valaxy/discussions/261

@mengnianxiaoyao

<div type='discussions-op-text'>

<sup>Originally posted by **MengNianxiaoyao** September  4, 2023</sup>
当代码框内代码过多时，代码框高度就会很大，导致文章长度过长，影响阅读体验。需要能调节代码框高度的设置来控制代码框进行折叠，但我没找到关于此项的主题设置。</div>

**Comment by YunYouJun** [comment]
<details open>
  <summary>Click me</summary>

  ```js
  function logSomething(something) {
    console.log('Something', something);
  }
  ```
</details>

Try use:

```md
<details open>
  <summary>Click me</summary>

  ```js
  function logSomething(something) {
    console.log('Something', something);
  }
  ```
</details>
```

**Comment by YunYouJun** [comment]
We will add this feature to enable for all code block.

**Comment by MengNianxiaoyao** [comment]
Maybe it's better to set the height to fold.

**Comment by YunYouJun** [comment]
It confused me. What is the height?

**Comment by MengNianxiaoyao** [comment]
For example, the height is 150px.When the height exceeds this limit, the excess part is folded。

**Comment by YunYouJun** [comment]
You have a point. Let's judge by the number of lines.
However, the full folding function seems to be needed.

**Comment by MengNianxiaoyao** [comment]
It can be like the `butterfly` theme

**Comment by YunYouJun** [comment]
> It can be like the `butterfly` theme

Just give me a screenshot example, thanks.

**Comment by MengNianxiaoyao** [comment]
> > It can be like the `butterfly` theme
> 
> Just give me a screenshot example, thanks.

screenshot: 
![gif](https://cdn.jsdelivr.net/gh/jerryc127/CDN@m2/img/hexo-theme-butterfly-docs-highlight-heigh-limit.gif)
![image](https://github.com/YunYouJun/valaxy/assets/103258286/4701c3c7-23ed-439d-bc38-04b074521430)

**Comment by YunYouJun** [comment]
Do you want to try creating a pr for this?
I can provide some technical support.
Or I'll implement it later.

**Comment by MengNianxiaoyao** [comment]
Just add this function later, I'm not in a hurry.

**Comment by YunYouJun** [comment]
#284
