### ISSUE TITLE
带Hash锚点的链接打开时不会跳转 Links with Hash anchors will not jump when opened

### ISSUE THREAD

**Issue by mirari** [YunYouJun/valaxy#263]
### Describe the bug

在浏览器中直接打开带锚点的链接，
[中文锚点](https://mirari.cc/posts/2023-08-29-sharing_my_home_decoration_experience_recommendations_and_notes#%E6%99%BA%E8%83%BD%E5%BC%80%E5%85%B3)

可以看到页面曾试图定位到锚点但又闪了一下回到了顶部。
但是章节目录长度超过1页时，章节的滚动条会正常跳转到锚点。

官方例子也是如此：
[https://yun.valaxy.site/posts/long-toc#list-title6](https://yun.valaxy.site/posts/long-toc#list-title6)
打开时滚动条仍然在最顶部。

### Reproduction

直接打开

### System Info

```Shell
System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 95.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    pnpm: 8.7.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mirari** [comment]
我在`node_modules/valaxy/client/composables/outline/anchor.ts`的onMounted回调里添加了
```
    requestAnimationFrame(() => {
      document.querySelector(
        decodeURIComponent(location.hash),
      )?.scrollIntoView()
    })
```
以后可以正常展示了，但我感觉这应该不是妥善的写法。
如果要在onMounted回调里统一添加什么操作的话，建议的写法是如何的？

**Comment by YunYouJun** [comment]
感谢反馈，应该是个 BUG，之后修复。

---

> 如果要在onMounted回调里统一添加什么操作的话，建议的写法是如何的？

是指给所有的 post 页面添加 onMounted 吗？那可以创建 layouts/post.vue，然后引入 valaxy-theme-yun 的 post.vue 继承并覆盖，随后添加 onMounted。

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/valaxy/commit/538445aee2494844df97af6091bb0c7be7f9af05.
Released in `v0.14.58`.
