### ISSUE TITLE
Refer to the title in the same markdown

### ISSUE THREAD

**Issue by IAMIBM** [YunYouJun/valaxy#268]
### Describe the bug

markdown example
## 123

[456](#456)

## 456

When I click on [456](#456) under the title 123, the webpage can not automatically scroll to the title 456

### Reproduction

N/A

### System Info

```Shell
valaxy version：0.14.56
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Works well, just upgrade your valaxy version.
