### ISSUE TITLE
[BUG]返回顶部按钮失灵

### ISSUE THREAD

**Issue by blackgold-saw** [YunYouJun/valaxy#269]
### Describe the bug

更新到最新版之后，返回顶部按钮失灵。

框架版本：0.14.59
主题：yun
主题版本：0.14.59

### Reproduction

--

### System Info

```Shell
--
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Fixed in `v0.14.60`.
