### ISSUE TITLE
Bugs: toc layout is still exist when I set toc: false in frontmatter

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#27]
The text has been disappeared correctly, but the layout is still here.

![toc layout](https://user-images.githubusercontent.com/54099603/177483617-c890d964-8263-45f6-a422-1b6e4147692f.png)

**Comment by YunYouJun** [comment]
use `toc` to control Table of Contents

use `aside` to control right sidebar (maybe in dev)
