### ISSUE TITLE
Waline option `imageUploader` not available

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#272]
### Describe the bug

`imageUploader` option in Waline allow users to upload images to external services like [去不图床](https://7bu.top) or self-hosted cloud storage, instead of directly encode the image to base64 URL.

While this option is available in the config file `valaxy.config.ts`, the addon seems like not working and still use base64 URL to upload images.

![image](https://github.com/YunYouJun/valaxy/assets/76810494/4d221834-645a-4202-9d3e-129df45f23e5)
![image](https://github.com/YunYouJun/valaxy/assets/76810494/49694d34-29b6-440f-8d0c-324b56f589b3)

### Reproduction

https://github.com/Big-Cake-jpg/big-cake-jpg.github.io

### System Info

```Shell
System:
    OS: Windows 10 10.0.23555
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.69 GB / 7.91 GB
  Binaries:
    Node: 20.4.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - D:\nodejs\npm.CMD
    pnpm: 8.6.10 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.23555.1000.0), Chromium (117.0.2045.47)
    Internet Explorer: 11.0.23555.1000
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Release valaxy-addon-waline `v0.1.1` with `waline@2.15.8`.

**Comment by Big-Cake-jpg** [comment]
UPDATE: looks like the option is still unavailable, do you know a fix?

**Comment by YunYouJun** [comment]
由于该函数使用 browser api，不可在 node 中执行配置，请使用客户端的方式进行配置。

例如，新建 `components/YunWaline.vue` 并覆盖（测试可行）：

```vue
<script lang="ts" setup>
import type { WalineInitOptions } from '@waline/client'
import consola from 'consola'

const customOptions: WalineInitOptions = {
  serverURL: 'https://waline.yunyoujun.cn',
  pageview: true,
  comment: true,

  imageUploader: (file) => {
    consola.info('Upload file: ', file)

    const formData = new FormData()
    const headers = new Headers()

    formData.append('file', file)
    headers.append('Authorization', '!{API TOKEN}')
    headers.append('Accept', 'application/json')

    return fetch('!{API URL}', {
      method: 'POST',
      headers,
      body: formData,
    })
      .then(resp => resp.json())
      .then(resp => resp.data.links.url)
  },
}
</script>

<template>
  <WalineClient w="full" :options="customOptions" />
</template>
```
