### ISSUE TITLE
【Bug】最新版文章使用封面会造成首页文章标题显示不清

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#274]
### Describe the bug

![image](https://github.com/YunYouJun/valaxy/assets/103258286/64c7c5de-0f2b-42bf-96fa-9c852d2650fd)

### Reproduction

依旧如此

### System Info

```Shell
win
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
能否提供摘要内容，以方便快速复现。

**Comment by YunYouJun** [comment]
明白问题了。

**Comment by MengNianxiaoyao** [comment]
我也发现了，`justify-center`垂直居中逼成这样的
