### ISSUE TITLE
Bug: 从有多级分类的文章点击【分类】按钮无法正常跳转至相应分类页面

### ISSUE THREAD

**Issue by blackgold-saw** [YunYouJun/valaxy#276]
### Describe the bug

从有多级分类的文章详细页面中，点击【分类】按钮，无法正常跳转至相应分类页面。
只能跳转到最下层的分类页面，此时分类页面会显示“暂无日志”。
![01](https://github.com/YunYouJun/valaxy/assets/127463150/b717a983-59a5-4fdc-97d9-5667518110be)
![02](https://github.com/YunYouJun/valaxy/assets/127463150/bcb869c1-0a83-4b8a-9cfd-0bd8de69ea34)

### Reproduction

--

### System Info

```Shell
框架版本：0.15.6
主题：yun
主题版本：0.15.6
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by remnantsaint** [comment]
我也有这个问题，不知道如何解决

**Comment by YunYouJun** [comment]
这个问题应当已经被修复。
