### ISSUE TITLE
Developing an AI Summarization Valaxy Addon - API Support Needed

### ISSUE THREAD

**Issue by Okysu** [YunYouJun/valaxy#278]
I am considering developing a Valaxy Addon for AI summarization, but I am unsure if Valaxy has any relevant APIs to support the following operations:
- Retrieving the content of an article
- Inserting a piece of HTML at the top of each article page to display the summary

If there are APIs available for these operations, could you please provide the corresponding usage examples? Thank you.

我正在考虑编写一款AI摘要的Valaxy Addon，但是不清楚Valaxy是否有相关API可以支持以下操作：
- 获取文章的内容
- 在每一个文章页面顶部插入一段HTML以显示摘要

如果有这样的相关API的话，能否提供相应的使用样咧，谢谢。

**Comment by YunYouJun** [comment]
- 可通过 extendMd 获取 Markdown Path，随后通过 fs 读取文章原始内容。

https://valaxy.site/themes/write#apis

- 插入显示摘要，则可通过为 `excerpt` 设置摘要信息，随后覆盖布局插槽模板实现。 

我将稍后提供更加复杂的示例。

**Comment by YunYouJun** [comment]
![image](https://github.com/YunYouJun/valaxy/assets/25154432/d658fa44-0f60-4ff6-95c6-b73ab2e770d2)

我为 valaxy-theme-yun 简单添加了一个插槽，直接展示 excerpt 内容。
![image](https://github.com/YunYouJun/valaxy/assets/25154432/de2ce357-9ebc-4662-b10a-05ac8b33cb2c)

> 可以从主题层面适配，用户也可以通过自定义覆盖 `ValaxyMd.vue` 组件实现类似效果

```VUE
<script lang="ts" setup>
import { useFrontmatter } from 'valaxy'
import { useI18n } from 'vue-i18n'

const fm = useFrontmatter()
const { t } = useI18n()
</script>

<template>
  <div class="ai-generated-excerpt rounded-lg bg-$va-c-bg-alt p-4">
    <div font="black" flex items-center>
      <div mr-1 i-ri-robot-2-line />
      <div>
        {{ t('excerpt.ai') }}
      </div>
    </div>
    <div op="90" mt-1>
      {{ fm.excerpt }}
    </div>
  </div>
</template>
```

因此 AI 摘要的工作可以转为一个简单的 Node 脚本工具：

- node fs 读取 markdown 内容
- 使用 `gray-matter` 解析 frontmatter
  - 当用户设置了 `excerpt_type: ai` 且 `excerpt` 字段不存在时，则添加 excerpt 内容
- 用户添加至 `package.json` `scripts`，`npm run ai:generate` 执行皆可

**Comment by YunYouJun** [comment]
基于此方案，几乎不需要 Valaxy 的特定 API，它的好处时，摘要插件其实可以做成任意框架下的 markdown 文章摘要生成，只需要适配不同框架的目录结构。

当然，也可以通过封装 valaxy addon 来让用户更加便捷，譬如提供默认 AI 摘要预览组件，可直接插入，新建在 `components` 文件夹下即可。
以及在 valaxy build 之前，自动执行 AI 摘要生成操作。
valaxy 可以提供 addon 的 pre 钩子，还在设计，之后补充进文档。

**Comment by YunYouJun** [comment]
增加了新的钩子。可以在构建之前或之后等时机执行。

https://valaxy.site/guide/custom/hooks

https://valaxy.site/addons/write#%25E4%25BD%25BF%25E7%2594%25A8%25E7%2594%259F%25E5%2591%25BD%25E5%2591%25A8%25E6%259C%259F%25E9%2592%25A9%25E5%25AD%2590
