### ISSUE TITLE
feat & bug: 希望文章过期警告能全局禁用，且目前填写false无效

### ISSUE THREAD

**Issue by qtqz** [YunYouJun/valaxy#281]
文章开头的
> 本文最后更新于xxx前，文中所描述的信息可能已发生改变。

无法全局禁用，希望能在主题配置里添加一个选项来禁用。而且，默认的1个月时间过期太短了，不如默认1年。

而且现在你在文章的frontmatter里设置time_warning: false也是无效的

**Comment by qtqz** [comment]
主题配置里一个选项同时决定是否禁用和默认过期时间(填true/false/时间)，会不会更好些

**Comment by YunYouJun** [comment]
![image](https://github.com/YunYouJun/valaxy/assets/25154432/b7fcdf42-9665-44e0-9f2a-36a0f03a5738)

可以通过设置全局 FrontMatter 来全局启用或禁用。

- time_warning 默认不开启
- 时间修改为 180 天
