### ISSUE TITLE
Code Copy Button Failed

### ISSUE THREAD

**Issue by YunYouJun** [YunYouJun/valaxy#291]
### Describe the bug

![image](https://github.com/YunYouJun/valaxy/assets/25154432/bb1a5fc7-caa3-4ec5-a346-c474d00d429e)

### Reproduction

Click Copy Button

### System Info

```Shell
all
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yixiaojiu** [comment]
This is my problem, when implementing code folding, there is a problem with the position of DOM insertion, I will fix it later.

**Comment by YunYouJun** [comment]
close by #292
