### ISSUE TITLE
[功能建议] 追番列表

### ISSUE THREAD

**Issue by Yuumi0221** [YunYouJun/valaxy#296]
### Clear and concise description of the problem

希望valaxy可以增加一个追番列表插件，用于展示bilibili或者bangumi的番剧收藏

### Suggested solution

目前有两种方式：
1. 【建议】参考[hexo-bilibili-bangumi](https://github.com/HCLonely/hexo-bilibili-bangumi)，开发基于valaxy框架的追番列表
2. 参考[Bilibili-Bangumi-JS](https://github.com/hans362/Bilibili-Bangumi-JS)，通过部署在Vercel来引入至博客（可惜这个项目例子仅支持b站，不支持bangumi，不太方便使用，所以还是来提了功能建议）

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by MengNianxiaoyao** [comment]
> hexo-bilibili-bangumi 我没怎么用过这个插件，这个插件相比 [Bilibili-Bangumi-JS](https://github.com/hans362/Bilibili-Bangumi-JS) 的静态之处，是每次更新列表的话，需要重新生成部署一遍吗？

是的

**Comment by yixiaojiu** [comment]
[Bilibili-Bangumi-JS](https://github.com/hans362/Bilibili-Bangumi-JS) 看起来不错，我想写个插件实现它。

**Comment by yixiaojiu** [comment]
[yixiaojiu/bilibili-bangumi-component](https://github.com/yixiaojiu/bilibili-bangumi-component)，借鉴 [Bilibili-Bangumi-JS](https://github.com/hans362/Bilibili-Bangumi-JS)，用 WebComponent 写了个组件可以用于任何前端项目，支持 BiliBili 与 Bangumi

**Comment by YunYouJun** [comment]
> [yixiaojiu/bilibili-bangumi-component](https://github.com/yixiaojiu/bilibili-bangumi-component)，借鉴 [Bilibili-Bangumi-JS](https://github.com/hans362/Bilibili-Bangumi-JS)，用 WebComponent 写了个组件可以用于任何前端项目，支持 BiliBili 与 Bangumi

Cool！

我正在尝试开发 [valaxy-addon-bangumi](https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-bangumi)，但直接使用你的通用依赖我认为是更好的选择。
你能将你的包作为依赖，进行一些更适合 valaxy 用户的简单封装，制作为 valaxy-addon-bangumi 吗？

**Comment by YunYouJun** [comment]
我猜想在你的 bilibili-bangumi-component 内应该存在一个对 bangumi api 的简易封装，而我此前也制作过一个 bangumi 的 api 封装，它位于 girid 项目中。

https://github.com/YunYouJun/girid/tree/main/packages/bangumi-api

它包含了 bangumi 公开的所有 API 封装，如动画、人物搜索等。

如果你有兴趣，我们可以将 bangumi-api 剥离出来，作为一个单独的仓库与 npm 包发布。

我想，https://github.com/bangumi 应该会很乐于接受这个仓库。

**Comment by YunYouJun** [comment]
valaxy-addon-bangumi depend on bilibili-bangumi-component.

Thanks for work of @yixiaojiu .

Example: https://yun.valaxy.site/bangumi/
