### ISSUE TITLE
英文 bold 字体难看 

### ISSUE THREAD

**Issue by zhoubin-me** [YunYouJun/valaxy#297]
Similar to this issue:
https://github.com/valaxyjs/valaxy-theme-starter/issues/11

Tried to change the font according to https://github.com/valaxyjs/valaxy-theme-starter/commit/ce33d46b8161dd4d9be09047e34d8e284e73d487

But doesn't really work for English Bold

**Comment by zhoubin-me** [comment]
奇怪在linux上又显示正常

**Comment by YunYouJun** [comment]
用的是这个：https://github.com/YunYouJun/valaxy/blob/ab0efd5dd7c5d15055d46788211c5842b67a36b9/packages/valaxy/client/styles/vars.scss#L19

**Comment by YunYouJun** [comment]
能截图看下你那边效果吗？

**Comment by YunYouJun** [comment]
It seems works well.
