### ISSUE TITLE
The default layout uses layouts/default.vue instead of ValleyMain.vue

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#30]
The default layout uses layouts/default.vue instead of ValleyMain.vue

Should be consistent with [vite-plugin-vue-layouts#overview - default](https://github.com/JohnCampionJr/vite-plugin-vue-layouts#overview)

**Comment by TuiMao233** [comment]
![image](https://user-images.githubusercontent.com/49724027/178104271-2d91afac-bab8-4ac2-9b02-dfc9412a0f1e.png)

**Comment by TuiMao233** [comment]
It seems that in custom themes, only `.md` will have this problem

**Comment by YunYouJun** [comment]
https://user-images.githubusercontent.com/25154432/178110022-3f86f35d-5a10-4811-a736-fe5868e379f8.mov

emm, it works well.

Try new structure.

**Comment by TuiMao233** [comment]
The new structure does not have this problem.
