### ISSUE TITLE
404页面显示错误

### ISSUE THREAD

**Issue by lkyu-ly** [YunYouJun/valaxy#302]
### Describe the bug

404页面显示错误，在自己的站点和大佬的博客上访问都出现显示问题，切换主流浏览器均如下图所示：
![Clip_231213_2103](https://github.com/YunYouJun/valaxy/assets/67578466/af968a8b-9edc-4391-b573-e843d252449f)

### Reproduction

https://yunyoujun.cn/404.html

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 3.63 GB / 15.73 GB
  Binaries:
    Node: 20.7.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.61)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Closed in https://github.com/YunYouJun/valaxy/commit/fa470be207ed223ea56dfb0ec6810764c11a46b2.
