### ISSUE TITLE
[Bug]netlify部署报错

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#307]
### Describe the bug

0.16.0版本部署报错
![image](https://github.com/YunYouJun/valaxy/assets/103258286/6b804fc8-8bd3-4ac5-b439-65e9a6b6bd1e)

### Reproduction

依旧如此

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MengNianxiaoyao** [comment]
vercel部署也是报错

**Comment by YunYouJun** [comment]
我这边测试部署成功，能否提供可复现仓库。

**Comment by MengNianxiaoyao** [comment]
> 我这边测试部署成功，能否提供可复现仓库。

已自行修复，大概率是npm缓存引起
