### ISSUE TITLE
访问或刷新主页面变成下载页面

### ISSUE THREAD

**Issue by MeetLTY** [YunYouJun/valaxy#309]
### Describe the bug

valaxy：v0.16.1

运行命令`npm run build`后，会生成一个无文件名的 .html 文件。当访问或刷新部署在 github pages 的站点主页面时，变成下载页面，无法直接输入域名访问。可打开文章页面再点击主页按钮进入。

示例网址 
https://t.fanghsiu.tk
https://t.fanghsiu.tk/posts/hello-valaxy

### Reproduction

https://github.com/MeetLTY/valaxy-test

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 6.78 GB / 15.87 GB
  Binaries:
    Node: 18.18.2 - D:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.1 - D:\Programs\nodejs\node_global\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

npm

### Validations

- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Related with https://github.com/YunYouJun/valaxy/discussions/170

**Comment by YunYouJun** [comment]
I left a comment here. https://github.com/JohnCampionJr/vite-plugin-vue-layouts/pull/132/files#r1435846602

I will downgrade vite-plugin-vue-layouts until it works.
