### ISSUE TITLE
双评论支持

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#310]
### Clear and concise description of the problem

在评论界面添加切换评论按钮来切换评论系统界面，用以支持同时使用了两个评论系统的博客

### Suggested solution

像hexo的butterfly主题一样
![](https://jsd.012700.xyz/gh/jerryc127/CDN/img/hexo-theme-butterfly-docs-double-comments.png)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
可以提供一些相关 API 配置格式的参考吗？

**Comment by YunYouJun** [comment]
Closed by #357
