### ISSUE TITLE
The fence code between two pictures cannot be displayed

### ISSUE THREAD

**Issue by IAMIBM** [YunYouJun/valaxy#315]
### Describe the bug

The fence code between two pictures cannot be displayed on the Google Chrome browser.
The content of the markdown is as follows.
===========================================================
<img src='./files/image-3.png' alt="image" style="float:left; margin-right:8192px;">  

```bash
123
456
789
```

<img src='./files/image-4.png' alt="image" style="float:left; margin-right:8192px;">  
===========================================================

![image](https://github.com/YunYouJun/valaxy/assets/43950866/916cbb11-8d69-4a68-9bb8-9afa526661a2)
</br>
</br>
![image](https://github.com/YunYouJun/valaxy/assets/43950866/24256bc6-9ffc-4b99-8ef7-75384099dbbf)  
![image](https://github.com/YunYouJun/valaxy/assets/43950866/e531c0de-76a2-41ce-9764-f0306c0244b3)

### Reproduction

N/A

### System Info

```Shell
valxy 0.16.3
pnpm 8.14.0
git 2.14.3
firefox 115.6.0esr
chrome 120.0.6099.131
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
This is a very interesting case.

After you remove the `float: left` of the image, it should display normally.

**Comment by YunYouJun** [comment]
I recommend you use the grammar of markdown: `![image](https://xxx)` to display image.

**Comment by YunYouJun** [comment]
If you want to align left img tag, you can write like this:

```html
<img src='https://yunyoujun.cn/images/avatar.jpg' alt="image" class="m-unset!">  
```

`m-unset!` will unset default margin. (align center)

---

Because float behaves differently in chrome and firefox. I think it might be a browser bug.
I don‘t have some solutions at the framework level.
