### ISSUE TITLE
feat: client redirects at vue router level

### ISSUE THREAD

**Issue by yixiaojiu** [YunYouJun/valaxy#328]
### Clear and concise description of the problem

related pr https://github.com/YunYouJun/valaxy/pull/314

### Suggested solution

1. Since [VueRouter can configure redirection in `RouteRecordRaw`](https://router.vuejs.org/guide/essentials/redirect-and-alias.html), I want to push redirection rules in this variable. https://github.com/YunYouJun/valaxy/blob/df2c16f1cf38e04fdda30b35f2534cf2d64379fa/packages/valaxy/client/main.ts#L4

2. Redirect configuration may have a broken change. How about this?
```ts
export default defineSiteConfig({
  redirects: {
    runtime: true,
    rules: [
      {
        from: '/foo',
        to: '/about',
      },
    ],
  },
});
```

3. For configure redirection in frontmatter, is there any way to get all markdowns' frontmatter while resolving options?  If not, how about  add a functions to do that.
 https://github.com/YunYouJun/valaxy/blob/df2c16f1cf38e04fdda30b35f2534cf2d64379fa/packages/valaxy/node/options.ts#L163-L164

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
It's always better to take advantage of the vue router's existing features. We can align the api as much as possible.

We can get all markdown frontmatter in `extendRoute`.

Refer here:

https://github.com/YunYouJun/valaxy/blob/df2c16f1cf38e04fdda30b35f2534cf2d64379fa/packages/valaxy/node/plugins/vueRouter.ts#L52

**Comment by yixiaojiu** [comment]
Ok, thank you for your answer.
