### ISSUE TITLE
github pages部署使用错误的文件路径不会进入框架的404界面，而是进入github的404界面

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#333]
### Describe the bug

![Clip_2024-01-31_12-27-43](https://github.com/YunYouJun/valaxy/assets/103258286/1d65f360-fc5f-40e0-a891-a3ddf73252e7)

### Reproduction

依旧如此

### System Info

```Shell
chrome
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MengNianxiaoyao** [comment]
vercel和cloudflare以及netlify都没此问题

**Comment by MengNianxiaoyao** [comment]
解决进入github的404界面后，出现以下情况
![Clip_2024-01-31_13-18-58](https://github.com/YunYouJun/valaxy/assets/103258286/f3a62cca-849a-4299-84b6-36b9e555b619)
以及404界面一直加载

**Comment by YunYouJun** [comment]
是否有在线仓库地址？

**Comment by MengNianxiaoyao** [comment]
> 是否有在线仓库地址？

demo-blog.mnxy.eu.org，这个是github pages部署的

同代码vercel部署的是blog.mnxy.eu.org

**Comment by YunYouJun** [comment]
修改了什么？

![image](https://github.com/YunYouJun/valaxy/assets/25154432/2d21cb74-d74f-45f8-96a9-3f231822fcc8)

**Comment by MengNianxiaoyao** [comment]
> 修改了什么？
> 
> ![image](https://github.com/YunYouJun/valaxy/assets/25154432/2d21cb74-d74f-45f8-96a9-3f231822fcc8)
> 

原先我加了`dirStyle: 'nested`，发现404界面是github的，后面就注释了

**Comment by YunYouJun** [comment]
github 只能识别 404.html 文件，而无法识别 `404/index.html`。

**Comment by YunYouJun** [comment]
看起来其他问题已经在 https://github.com/YunYouJun/valaxy/issues/338 解决了？
