### ISSUE TITLE
`yarn build:ssg` outputs SPA dist

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/valaxy#335]
### Describe the bug

When running `yarn build:ssg`, it doesn't output SSG files like tons of HTML documents.

In fact, it outputs SPA files.

This behavior could be very strange. GitHub Pages is working perfectly, while Netlify / Vercel / Cloudflare Pages are affected.

### Reproduction

https://github.com/Big-Cake-jpg/big-cake-jpg.github.io

### System Info

```Shell
System:
    OS: Windows 10 10.0.23615
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.55 GB / 7.91 GB
  Binaries:
    Node: 20.4.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - D:\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.23615.1000
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yixiaojiu** [comment]
<img width="976" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/41efdcb2-f5d1-471d-8fbd-489a47fe3e77">

It seems that you don't build successfully.

**Comment by YunYouJun** [comment]
clone 你的项目，似乎没有复现该问题。

![image](https://github.com/YunYouJun/valaxy/assets/25154432/4a3e2ece-3757-488f-a760-fff821fa54c2)

**Comment by Big-Cake-jpg** [comment]
> clone 你的项目，似乎没有复现该问题。
> 
> ![image](https://private-user-images.githubusercontent.com/25154432/302050588-4a3e2ece-3757-488f-a760-fff821fa54c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDgyMjgsIm5iZiI6MTcwNzAwNzkyOCwicGF0aCI6Ii8yNTE1NDQzMi8zMDIwNTA1ODgtNGEzZTJlY2UtMzc1Ny00ODhmLWE3NjAtZmZmODIxZmE1NGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDAwNTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MDZjMzFjNTBkYmEwYmZmMzIzODY4MGNmODVmMjFlMmFiNjkwYTEyM2MyOTcwZTBhMjNmMTRiMjlhNDRmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2NJjOzeqmrD9zs9kNFYADYL8Ne3pzpqQMyM_i6AkAWM)

那大概是因为依赖项的问题？我一会儿试试删掉 lockfile 和 node_modules 重装看看……

**Comment by Big-Cake-jpg** [comment]
重新安装所有依赖项之后问题解决。
