### ISSUE TITLE
【Bug】只要有更新，就会一直加载

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#338]
### Describe the bug

![Clip_2024-02-02_14-01-07](https://github.com/YunYouJun/valaxy/assets/103258286/906d081a-62b5-42ac-aa69-8bfdfa920dde)
如图，控制台显示，主题和框架都是最新版，vercel部署

### Reproduction

依旧如此

### System Info

```Shell
chrome
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yixiaojiu** [comment]
能放一个 vercel 部署后的链接吗

**Comment by MengNianxiaoyao** [comment]
> 能放一个 vercel 部署后的链接吗

blog.mnxy.eu.org

**Comment by yixiaojiu** [comment]
<img width="231" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/09f26675-5cdc-48a1-b2d9-74ec581763d1">

请缓存就能正常加载，构建的过程中有报错吗？

**Comment by yixiaojiu** [comment]
<img width="1123" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/9e8bb17a-27b3-4540-bf0e-80c13bba102a">

看起来好像是 Service Work 的缓存导致，没有获取最新的 html 文件

**Comment by MengNianxiaoyao** [comment]
> <img width="231" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/09f26675-5cdc-48a1-b2d9-74ec581763d1">
> 
> 请缓存就能正常加载，构建的过程中有报错吗？

没有

**Comment by yixiaojiu** [comment]
<img width="1027" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/a58a1541-4308-410a-bdd1-c0f770ac4b12">

更新一下 ServerWork，并清除一下 Storage 的缓存就可以正常工作了。

你要不要检查一下 PWA 的配置，可能是 pwa 的问题

**Comment by MengNianxiaoyao** [comment]
> <img width="1027" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/a58a1541-4308-410a-bdd1-c0f770ac4b12">
> 
> 更新一下 ServerWork，并清除一下 Storage 的缓存就可以正常工作了。
> 
> 你要不要检查一下 PWA 的配置，可能是 pwa 的问题

怎么更新serverwork和清除storage缓存？

**Comment by yixiaojiu** [comment]
打开开发者工具

<img width="1087" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/94dda7bf-fbea-45b1-bb22-71813787ba30">
<img width="1012" alt="image" src="https://github.com/YunYouJun/valaxy/assets/63455218/00d180d2-0f00-4c34-80ac-3ce2cc92b514">

然后刷新一下页面

**Comment by MengNianxiaoyao** [comment]
pwa设置没什么问题啊

**Comment by yixiaojiu** [comment]
这我就不知道了 :fearful:

**Comment by MengNianxiaoyao** [comment]
解决了，是`workbox`里的`globDirectory`配置出错了，导致`sw.js`里的各种文件路径前缀加了`dist/`

**Comment by MengNianxiaoyao** [comment]
![Clip_2024-02-02_20-06-03](https://github.com/YunYouJun/valaxy/assets/103258286/ee68e305-745b-46d5-8cb5-12d22e284b52)
这个不能出错，配置错了就一堆问题

**Comment by yixiaojiu** [comment]
:joy: :joy: :joy:
