### ISSUE TITLE
在vite.config.ts中配置了@vitejs/plugin-vue的isCustomElement后，出现报错

### ISSUE THREAD

**Issue by Sakurapole** [YunYouJun/valaxy#339]
### Describe the bug

无论是在哪一个vite.config.ts，或者是valaxy.config.ts中，只要配置了@vitejs/plugin-vue的isCustomElement：
![image](https://github.com/YunYouJun/valaxy/assets/35411164/a0f42b22-cf34-429e-b943-f892d08e7dfc)

就会报错：
![image](https://github.com/YunYouJun/valaxy/assets/35411164/e9a2ff78-3973-46e8-acc7-17cce4d246ce)

大致的报错：
![image](https://github.com/YunYouJun/valaxy/assets/35411164/695df0ca-c662-4f55-a2b8-51d1c6178dc4)
![image](https://github.com/YunYouJun/valaxy/assets/35411164/bdd82d43-40bf-4fba-b8bb-7ee8b0a702e5)
![image](https://github.com/YunYouJun/valaxy/assets/35411164/141a4857-9936-41a0-8daf-61fb3ae32140)
![image](https://github.com/YunYouJun/valaxy/assets/35411164/ceec079e-919d-4e6e-8332-41558d202a7f)

### Reproduction

https://codesandbox.io/p/github/Sakurapole/valaxy-theme-bug-demo/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls5ph27b00063j6hwkgr5mv5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls5ph27b00023j6hp5mc0u8y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls5ph27b00043j6h74r0xey3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls5ph27b00053j6hr30wwr93%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls5ph27b00023j6hp5mc0u8y%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls5ph27a00013j6hzwv47u64%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cls5ph27b00023j6hp5mc0u8y%2522%252C%2522activeTabId%2522%253A%2522cls5ph27a00013j6hzwv47u64%2522%257D%252C%2522cls5ph27b00053j6hr30wwr93%2522%253A%257B%2522id%2522%253A%2522cls5ph27b00053j6hr30wwr93%2522%252C%2522activeTabId%2522%253A%2522cls5pkgdf00o63j6hwec4cdk0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A4859%252C%2522id%2522%253A%2522cls5pkgdf00o63j6hwec4cdk0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cls5ph27b00043j6h74r0xey3%2522%253A%257B%2522id%2522%253A%2522cls5ph27b00043j6h74r0xey3%2522%252C%2522activeTabId%2522%253A%2522cls5ph3n5005j3j6ht3gwakrl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls5ph27b00033j6hz0u24dpl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cls5ph2v9002sddgh6w4fc69l%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cls5ph3n5005j3j6ht3gwakrl%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522cls5phw9e008f3j6h7g5lc9bt%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 11.97 GB / 39.86 GB
  Binaries:
    Node: 18.19.0 - D:\DeveloperTools\Scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: No HADOOP_CONF_DIR set.
Please specify it either in yarn-env.cmd or in the environment. - D:\DeveloperTools\hadoop-3.1.0\bin\yarn.CMD
    npm: 10.4.0 - D:\DeveloperTools\Scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 8.15.1 - D:\DeveloperTools\Scoop\apps\nvm\current\nodejs\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
`@vitejs/plugin-vue` 已经被 `valaxy` 集成，因此我们不需要重复加载两个插件。

你可以通过 `vue` 字段直接添加 `@vitejs/plugin-vue` 的相关配置。

**Comment by YunYouJun** [comment]
如果需要的话，你可以告诉我你最希望它出现在文档的什么位置，我将会添加相关的说明。

**Comment by Sakurapole** [comment]
> 如果需要的话，你可以告诉我你最希望它出现在文档的什么位置，我将会添加相关的说明。

ok，可以在这里加上默认集成的vite插件吗
![image](https://github.com/YunYouJun/valaxy/assets/35411164/9d84d58f-fedb-412f-856a-64f8bc0a61c9)
