### ISSUE TITLE
the type declaration of valaxy.config.ts should be more accurate

### ISSUE THREAD

**Issue by LoTwT** [YunYouJun/valaxy#34]
Using not only `UserConfig<ThemeUserConfig>` , but also `defineConfig`, it can't go to type declaration correctly ( hover property and use F12 in VS Code ).

**Comment by YunYouJun** [comment]
Check `latest` version. 

It seems works well. 

![image](https://user-images.githubusercontent.com/25154432/178110223-c1e194a5-93d0-4929-b91e-4982ea91c805.png)

**Comment by LoTwT** [comment]
> Check `latest` version.
> 
> It seems works well.
> 
> ![image](https://user-images.githubusercontent.com/25154432/178110223-c1e194a5-93d0-4929-b91e-4982ea91c805.png)
> 
> ```ts
> import { defineConfig } from 'valaxy'
> import type { ThemeConfig } from 'valaxy-theme-starter'
> 
> /**
>  * User Config
>  * do not use export const config to avoid defu conflict
>  */
> export default defineConfig<ThemeConfig>({})
> ```

When using `vite.config.ts`, I can use F12 to go to the dts file in VS Code but it failed with `valaxy.config.ts`. It troubles me.

Also, `themeConfig.pages` seems to be inferred like generics. When it's fed with `[]`, it's type may be `never[ ]`. I think it may be a particular type .

**Comment by TuiMao233** [comment]
In .d.ts analysis, the conditional judgment in `type-fest` is too long. If there is no special requirement, a simple `PartialDeep` can be directly implemented

![image](https://user-images.githubusercontent.com/49724027/178116188-23640147-fc22-4792-aac4-f53dd36a56b0.png)
![image](https://user-images.githubusercontent.com/49724027/178116224-fb71a9e4-91ec-4d23-adf5-03005c454fa9.png)

**Comment by YunYouJun** [comment]
I think it is fixed in `v0.7.8`.
