### ISSUE TITLE
使用最新版构建报错 0.18.0-beta.2

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#351]
### Describe the bug

![Clip_2024-02-14_22-17-22](https://github.com/YunYouJun/valaxy/assets/103258286/fe273f07-dc62-4b25-b4e0-a09b3668e760)

### Reproduction

依旧如此

### System Info

```Shell
pnpm
win
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Try new version, it works well:

- valaxy@0.18.0
- valaxy-theme-yun@0.18.0
- valaxy-addon-meting@0.0.5
