### ISSUE TITLE
/page/* 目录返回 HTTP 404 状态码

### ISSUE THREAD

**Issue by gxres042** [YunYouJun/valaxy#364]
### Describe the bug

用户访问 `/page/2` 这样的目录时，服务端会返回 HTTP 404 状态码，但是本地 dev 没有这个问题。
Vercel 已配置 rewrite 至 `index.html`

### Reproduction

最坏的情况就是不配置 Vercel 的 rewrite

Example: https://blog.gxres.net/page/2
打开 F12 Network 并刷新页面就能逮住

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 10.41 GB / 15.80 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Now, you can use `build.ssgForPagination` to generate static file for pagination.
