### ISSUE TITLE
bug: Using fuse to search for articles with folders resulted 404

### ISSUE THREAD

**Issue by qtqz** [YunYouJun/valaxy#366]
### Describe the bug

使用 fuse 搜索带有文件夹的文章导致404
1. 创建一篇带文件夹的文章
```
posts
├─ your-post
│  ├─ a.png
│  ├─ b.png
│  └─ index.md
```
2. 启用 fuse 搜索，别忘了`pnpm valaxy fuse`
```js
  search: {
    enable: true,
    type: 'fuse'
  },
  fuse: {
    options: {
      keys: ['title', 'tags', 'categories', 'excerpt', 'content', 'author'],
      ignoreLocation: true,
    },
  },
```
3. 搜索那个文章里的内容，点击搜索结果，会跳转到`http://localhost:4859/posts/your-post/index`，多了一个`/index`，导致404

### Reproduction

↑

### System Info

```Shell
0.18.5
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qtqz** [comment]
还有，fuse 很多选项没有用，比如`includeScore:true, includeMatches:true,`是主题没适配吗？

**Comment by YunYouJun** [comment]
可能是还没有适配。
