### ISSUE TITLE
bug: search causes layout shift and search shortcuts Invalid

### ISSUE THREAD

**Issue by qtqz** [YunYouJun/valaxy#368]
### Describe the bug

1. 启用搜索时，点击搜索按钮导致页面布局偏移，示例中能看到页面中间的黑线在闪动。

感觉是这玩意导致的，它也没起到应有的作用（启用后页面还是能滚动）

```ts
//YunFuseSearch.vue
const { lockBodyScroll, unlockBodyScroll } = useBodyScrollLock(searchContainer)
```

2. 搜索快捷键无效

```ts
//YunSearchTrigger.vue
const { Meta_K } = useMagicKeys()

watch(Meta_K, (val) => {
  if (val)
    togglePopup()
})
```
win+k 被系统占用，无法唤出搜索。先按 k 后按 win，会唤出搜索和开始菜单。为什么不用 ctrl+k 呢？

### Reproduction

https://www.yunyoujun.cn/

### System Info

```Shell
win10
valaxy0.18.5
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
`ctrl + k` 是浏览器的地址栏。

**Comment by qtqz** [comment]
> `ctrl + k` 是浏览器的地址栏。

可是你的 press 主题和 vue 文档都是这样……

**Comment by YunYouJun** [comment]
1. 已修复
2. 同时支持 Ctrl/Cmd + K

将在 v0.18.7/v0.19.0 中发布。
