### ISSUE TITLE
分页组件无法正常显示

### ISSUE THREAD

**Issue by heluo520** [YunYouJun/valaxy#371]
### Describe the bug

分页组件无法正常显示

### Reproduction

https://github.com/heluo520/blog-demo

### System Info

```Shell
没有诶
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yixiaojiu** [comment]
![image](https://github.com/YunYouJun/valaxy/assets/63455218/f11a7bde-6d11-4284-a126-090b2307db04)


![image](https://github.com/YunYouJun/valaxy/assets/63455218/1bbf01a2-8340-429c-8346-ac0c105717c5)

好像是颜色计算错误

**Comment by YunYouJun** [comment]
后续会考虑使用 ctrlcolor 计算色彩亮暗程度，再计算。
