### ISSUE TITLE
本地预览在加载 waline评论后无法正常打开文章页

### ISSUE THREAD

**Issue by zsbai** [YunYouJun/valaxy#373]
### Describe the bug

浏览器为Firefox 当前最新 124.0.1版本，当在`valaxy.config.ts`中添加waline的addons后，本地运行`pnpm run dev`可以正常打开主页，但无法正常加载文章，具体表现为点击任何一篇文章，网页上方的加载条会缓慢加载最后永远卡住。

已经尝试：清除本地浏览器缓存，更换浏览器为Edge，依旧可以复现问题。

已确定是 addons 相关配置引起的，注释 addons 相关配置恢复正常。

配置文件：
```
siteConfig: {
    // 启用评论
    comment: {
      enable: true
    },
  },
  // 设置 valaxy-addon-waline 配置项
  addons: [
    addonWaline({
      // Waline 配置项，参考 https://waline.js.org/reference/client/props.html
      serverURL: 'https://waline.xxxexample.com',
    }),
  ],
```
但是可以正常构建，构建后的静态网页也可以正常打开文章，浏览器控制台没有显示任何错误，终端也没有显示任何错误：
```
PS C:\Users\home\work\valaxy-blog> pnpm run dev

> valaxy-blog@0.0.0 dev C:\Users\home\work\valaxy-blog
> valaxy

(node:103068) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
o Resolve valaxy config...                                                                                    22:55:58
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
√ Resolve userValaxyConfig from C:/Users/home/work/valaxy-blog/valaxy.config.ts 1.41s                      22:55:59
√ Resolve siteConfig from C:/Users/home/work/valaxy-blog/site.config.ts 353.88ms                           22:55:59
√ Resolve valaxy.config.ts from theme(yun) 409.87ms                                                           22:56:00
√ Resolve addons from C:/Users/home/work/valaxy-blog
  └─ valaxy-addon-waline v0.1.2 https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-waline
√ valaxy: server ready                                                                                        22:56:01

  🌌 Valaxy  v0.18.5

  🪐 theme   > yun
  📁 C:\Users\home\work\valaxy-blog

  Preview    > http://localhost:4891/
  Network    > http://100.96.0.12:4891/

  shortcuts  > restart | open | qr | edit

```

### Reproduction

pnpm run dev

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 10.45 GB / 31.63 GB
  Binaries:
    Node: 21.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.3 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1
# 这里没有显示出来，实际使用浏览器为：
    Firefox: 124.0.1
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
确认是否为网络问题？可以打开控制台查看 Network，以及是否有可复现仓库？

**Comment by fanghsiu** [comment]
![image](https://github.com/YunYouJun/valaxy/assets/79410512/08ca27ef-909f-4aa3-a614-316764831214)

optimizeDeps 没有加载 @waline/client/component 组件的原因。
node_modules/.vite/_metadata.json 文件中没有 @waline/client/component 这一项也佐证了这点。
你可以在 valaxy.config.ts 添加以下配置解决此问题。
```
vite: {
  optimizeDeps: {
    include: ['@waline/client/component'],
  },
},
```
另外我发现以自定义组件使用 WalineClient.vue 时，不添加上面配置也不会有问题。所以你也可以将插件中的 WalineClient.vue 复制到 component 文件夹来解决此问题，效果如下。

![image](https://github.com/YunYouJun/valaxy/assets/79410512/21d41b3a-f234-40e6-b083-547095837c80)

至于为什么出现这样的问题，我不是专业的，不懂。

**Comment by YunYouJun** [comment]
看起来似乎是没有自动读取到组件的问题，我将在之后为 valaxy-addon-waline 添加相关适配。

**Comment by YunYouJun** [comment]
Related to https://github.com/YunYouJun/valaxy/issues/380
