### ISSUE TITLE
为 Valaxy RSS 添加跳转原文的链接

### ISSUE THREAD

**Issue by gxres042** [YunYouJun/valaxy#378]
### Clear and concise description of the problem

![image](https://github.com/YunYouJun/valaxy/assets/53113178/7f135a26-a400-48d6-bc7c-da7137b490f5)

以 [晓雨杂记](https://lihaoyu.cn) 为例，其 RSS 只输出了文章的一部分内容（摘要），如果访客想继续往下看，就得自己访问网站并找到相应的文章。

我认为可以在摘要后面添加一个包含文章链接的提示，让订阅 RSS 的访客能够快捷抵达对应文章页面、继续阅读文章。

### Suggested solution

修改 valaxy/node/modules/rss.ts 的 L118 `content` 一项即可。

### Alternative

我会在 valaxy/node/modules/rss.ts 的 L118 进行修改，并提起一个 Pull Request。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/valaxy/commit/2a0194dea557729412922afde5a50be1dedb97da
