### ISSUE TITLE
bug: SyntaxError: The requested module '...recaptcha-v3/dist/ReCaptcha.js?v=56f54889' does not provide an export named 'load'

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#380]
### Describe the bug

出现步骤：
1. 直接 `pnpm create valaxy` 使用最新版本 Valaxy 选择创建 Blog，并使用 pnpm
2. 安装好依赖之后再 `pnpm add valaxy-addon-waline` 添加 waline 插件
3. 直接在模板里面添加了以下配置：
```typescript
/**
 * User Config
 */
export default defineValaxyConfig<UserThemeConfig>({
  // ...
  addons: [
    addonWaline({ 
      serverURL: 'https://waline.rotcool.me' 
    }),
  ],
})
```
之后使用 `pnpm dev`，打开博客，主页可以正常打开，但是打开具体文章（应该是需要加载评论的页面）浏览器的 Console 就会出现以下报错：
![报错信息](https://github.com/YunYouJun/valaxy/assets/54099603/cf06f8cf-416a-406f-9657-3d1c2deb89a1)

### Reproduction

https://github.com/Rotten-LKZ/valaxy-blog-waline

### System Info

```Shell
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 AMD
  Memory: 3.20 GB / 15.31 GB
Binaries:
  Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
  npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  pnpm: 8.15.6 - C:\Program Files\nodejs\pnpm.CMD
Browsers:
  Edge: Chromium (123.0.2420.97)
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
将 `'@waline/client/component'` 添加至 optimizeDeps 中可解决改问题。

```ts
  vite: {
    optimizeDeps: {
      include: ['@waline/client/component']
    }
  }
```
