### ISSUE TITLE
Hexo 迁移后配置 Waline 发送的请求地址多了前缀 /api 导致请求失败

### ISSUE THREAD

**Issue by 674019130** [YunYouJun/valaxy#389]
### Describe the bug

Valaxy:
![374dea9e424c9afe6cdad746205eb18d](https://github.com/YunYouJun/valaxy/assets/26924933/acdd913a-b047-47bd-8bcb-3b5ba7355ffa)

Hexo:
![image](https://github.com/YunYouJun/valaxy/assets/26924933/f8cd6175-ea65-4434-83c0-af5612836f0c)

-------------------------------------------------

另，想请问如何更换主页的背景图片，查看源码（node_modules\.pnpm\valaxy@0.18.6_@babel+parser@7.24.5_@types+markdown-it@14.0.1_@types+node@20.12.7_@unhead+shar_qhm4uwb2fsrmt7m7yb7jyneeri\**node_modules\valaxy\types\config.ts**）没发现有这个配置项（不太懂前端，只能看到这里惹 T_T）

再另，我理解的 Valaxy 的自动部署是指 Valaxy-blog 项目代码发生更新（可能是推送行为）后，vercel 通过读项目内的脚本（或许是vercel.json）定向部署到 %userId%.github.io。
但是我没找到用以 **定向** 的配置项。

感谢您的时间。

### Reproduction

as description

### System Info

```Shell
JSON Config:
addons: [
    addonWaline({
      serverURL: 'https://vercel-waline-c111rx0gg-674019130.vercel.app/',
      pageview: true,
      comment: true
    }),
    addonLightGallery(),
  ],

$ pnpm -v
9.0.6

$ node -v
v20.12.2

由 Valaxy v0.18.6 驱动 | 主题 - Yun v0.18.6

如果需要更多的环境信息，请随时与我联系。
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 674019130** [comment]
发现似乎是 Waline 版本的问题，在尝试用 vercel 重新部署，但是 vercel 在 Node.js 的版本选择上好像有点问题，正在尝试。

**Comment by 674019130** [comment]
![image](https://github.com/YunYouJun/valaxy/assets/26924933/f21f1fd2-e51c-4bd0-8e08-5479612653c1)
升级后 @waline/server  v1.31.13，依然同样报错

**Comment by fanghsiu** [comment]
Waline 前端和服务端版本不统一的问题，访问 https://vercel-waline-c111rx0gg-674019130.vercel.app/ 可以看到与文章中显示的版本不一致，你应该重新升级部署你的 waline 。https://waline.js.org/advanced/faq.html#如何升级

关于自动部署 https://valaxy.site/guide/deploy#第三方部署

背景图在 valaxy.config.ts 配置。https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy-theme-yun/types/index.d.ts
```
  /**
   * @en Background image
   * @zh 背景图
   */
  bg_image: {
    /**
     * @en Enable background image
     */
    enable: boolean
    /**
     * @en Image url
     */
    url?: string
    /**
     * @en Image url when dark mode
     */
    dark?: string
    /**
     * @en Image opacity
     */
    opacity?: number
  }
```

**Comment by 674019130** [comment]
> Waline 前端和服务端版本不统一的问题，访问 https://vercel-waline-c111rx0gg-674019130.vercel.app/ 可以看到与文章中显示的版本不一致，你应该重新升级部署你的 waline 。[https://waline.js.org/advanced/faq.html#如何升级](https://waline.js.org/advanced/faq.html#%E5%A6%82%E4%BD%95%E5%8D%87%E7%BA%A7)
> 
> 关于自动部署 [https://valaxy.site/guide/deploy#第三方部署](https://valaxy.site/guide/deploy#%E7%AC%AC%E4%B8%89%E6%96%B9%E9%83%A8%E7%BD%B2)
> 
> 背景图在 valaxy.config.ts 配置。https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy-theme-yun/types/index.d.ts
> 
> ```
>   /**
>    * @en Background image
>    * @zh 背景图
>    */
>   bg_image: {
>     /**
>      * @en Enable background image
>      */
>     enable: boolean
>     /**
>      * @en Image url
>      */
>     url?: string
>     /**
>      * @en Image url when dark mode
>      */
>     dark?: string
>     /**
>      * @en Image opacity
>      */
>     opacity?: number
>   }
> ```

感谢您的时间，先说结论。vercel 在昨晚重新部署新版本后，**服务端地址变了**，将新地址同步到 `valaxy.config.ts` 中后 Waline 可以正常使用。
这可以归类为 Waline 版本问题，这个 issue 内包含了解决方案和升级 Waline 的相关信息。

----

关于自动部署，目前是卡在了 `npm run build` 出现死链这一步，正在尝试解决。 
discussion：https://github.com/YunYouJun/valaxy/discussions/390

------

关于背景图片，使用相对路径寻址，图片未能加载成功。暂时未找到原因。
最终使用图床链接解决。
