### ISSUE TITLE
Bugs: There is a disconnect between the plugin extension of the `valaxy` option and the actual configuration

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#39]
After the value is passed in the plugin, it will not actually take effect
![image](https://user-images.githubusercontent.com/49724027/178130516-d8ddb548-b808-477d-9adc-92a036ff7617.png)
![image](https://user-images.githubusercontent.com/49724027/178130536-542832a7-2f6d-4a7b-935f-3a8245516c7e.png)

In preset.ts, pluginOptions is not actually merged with theme-plugin's configuration，

pluginOptions is still independent，has nothing to do with `theme valaxy`

![image](https://user-images.githubusercontent.com/49724027/178130598-419c00f0-4341-44d0-8134-2580681cde6b.png)

**Comment by TuiMao233** [comment]
a solution，Read config again after ThemeConfig is called, and deeply merge pluginOptions：
![image](https://user-images.githubusercontent.com/49724027/178130926-46ddf4b8-51db-4d22-a0ca-aafba45ec0d0.png)

**Comment by YunYouJun** [comment]
`node/index.ts` is a standard vite plugin. We can not custom property here.

`extendMd` is in `vite.config.ts`:

```ts
import { defineConfig } from 'vite'
// import { VitePWA } from 'vite-plugin-pwa'

const safelist = [
  'i-ri-home-line',
]

export default defineConfig({
  valaxy: {
    unocss: {
      safelist,
    },
    extendMd(ctx) { console.log(ctx) }
  },
})
```

**Comment by TuiMao233** [comment]
Yes, no problem here, but how to add options in theme

**Comment by TuiMao233** [comment]
If it were me, developing the theme would not want to reveal too many options to the user, which would make it cumbersome for the user to use

**Comment by YunYouJun** [comment]
Ok, I see what you mean, I will fix it.

**Comment by YunYouJun** [comment]
> If it were me, developing the theme would not want to reveal too many options to the user, which would make it cumbersome for the user to use
> 
> If it's just a vite plugin, it's too restrictive in theme development

I think it's important to provide the user with all the apis to complete the functionality through the vite plugin.

`valaxy-theme-starter` provides a default setting if the theme developer doesn't want to control the API.
