### ISSUE TITLE
如何更改文章标题在「页面内部」和「文章列表」中的颜色？

### ISSUE THREAD

**Issue by 674019130** [YunYouJun/valaxy#391]
### Describe the bug

实际上不算 Bug，应该是想问下使用方式
https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy/types/posts.ts#L108

这个看备注是 title color，在`pages/posts/xx.md` 的 FrontMatter 里试了以下几种方式都没有生效

color: 'red'
color: '#FF8EB3'
color: 'rgb(255, 0, 255)'
color: '255, 0, 255'

### Reproduction

as description

### System Info

```Shell
  System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 2.37 GB / 15.67 GB
  Binaries:
    Node: 20.12.2 - E:\BlogCode\nodejs20.12.2\node.EXE
    npm: 10.5.0 - E:\BlogCode\nodejs20.12.2\npm.CMD
    pnpm: 9.0.6 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1

```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yixiaojiu** [comment]
yaml 里字符串好像不用加单引号，你试试这样写？

```yaml
color: red
```

**Comment by 674019130** [comment]
> yaml 里字符串好像不用加单引号，你试试这样写？
> 
> ```yaml
> color: red
> ```

在首页还是原来的颜色，但是点进去就是设置的颜色了！
但是内外颜色不一致也很奇怪，看来改外面的颜色要找别的地方
感谢！

**Comment by YunYouJun** [comment]
<img width="420" alt="image" src="https://github.com/YunYouJun/valaxy/assets/25154432/8422d990-5924-4b13-a001-2cce4f39885b">
<img width="479" alt="image" src="https://github.com/YunYouJun/valaxy/assets/25154432/03d6f9a3-f7b4-427b-b3c3-a0801ff0d58e">

Hey, 我计划提供一个两个的 frontmatter pageTitleClass 与 postTitleClass 以允许你自定义标题样式，而在未来弃用 `color` 属性。

- pageTtitleClass：页面内部的标题
- postTitleClass：帖子列表中的标题

如果你觉得可行，我将很快释出该 API。

**Comment by 674019130** [comment]
> <img alt="image" width="420" src="https://private-user-images.githubusercontent.com/25154432/344392912-8422d990-5924-4b13-a001-2cce4f39885b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTkyOTQsIm5iZiI6MTcxOTc1ODk5NCwicGF0aCI6Ii8yNTE1NDQzMi8zNDQzOTI5MTItODQyMmQ5OTAtNTkyNC00YjEzLWEwMDEtMmNjZTRmMzk4ODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE0NDk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhOTU0NDc0MWNjZjZlYjIyMzM1MmVhZTNmYzIxZmNhOGFiYmU0OGQwZTk1ZGVmMGU0MjFkNTI0ZTk5ODM0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QVd_c1Wu5kQT-L0SJxlN8VgSTbTf7tvQmMKfmL3E-SY"> <img alt="image" width="479" src="https://private-user-images.githubusercontent.com/25154432/344392917-03d6f9a3-f7b4-427b-b3c3-a0801ff0d58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTkyOTQsIm5iZiI6MTcxOTc1ODk5NCwicGF0aCI6Ii8yNTE1NDQzMi8zNDQzOTI5MTctMDNkNmY5YTMtZjdiNC00MjdiLWIzYzMtYTA4MDFmZjBkNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE0NDk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjViYmE5NDk5ZjdkMWRmYTNhNTFhOTkxMWJmNzkzNTZmZjkwMmVjMzQxYzFhZjkzZDNiYmUxNjcyMDM2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cCXFBgbfp6QTi7f93ATVyAYPS251aZzGagDDq3HjVSQ">
> Hey, 我计划提供两个新 frontmatter `pageTitleClass` 与 `postTitleClass` 以允许你自定义标题样式，而在未来弃用 `color` 属性。
> 
> * pageTtitleClass：页面内部的标题
> * postTitleClass：帖子列表中的标题
> 
> 如果你觉得可行，我将很快释出该 API。

请允许我确认一下：
> postTitleClass：帖子列表中的标题
是否指**访问博客时首页显示的标题（颜色）**。

如果是的话，的确解决了我的问题，感谢帮助！

我将在 API 释出后更新该 Issue，提供更完整的问题描述和解决方案。

**Comment by 674019130** [comment]
经验证，已在版本[v0.18.10](https://github.com/YunYouJun/valaxy/releases/tag/v0.18.10)中实现修改帖子标题颜色的功能，随后我将补充问题描述和解决方案。

**Comment by 674019130** [comment]
问题描述：
见 issue 标题和[点这里](https://github.com/YunYouJun/valaxy/issues/391#issue-2279632858)所提到的内容。

解决方案：
（详见官方教程：https://valaxy.site/guide/post）
- 使用版本 >= 0.18.10 的 valaxy 引擎和 valaxy-theme-yun
![image](https://github.com/YunYouJun/valaxy/assets/26924933/2ecfa02b-e26c-4aa3-b455-92b3128baf7f)
- 在 markdown 文件内的 FrontMatter 中使用 postTitleClass: 'text-#FF8EB3' 自定义标题样式
![image](https://github.com/YunYouJun/valaxy/assets/26924933/422b37bc-adb5-41cc-800e-97f80a71cb14)
