### ISSUE TITLE
[Feature Request] 增加 include 后编译 Markdown 标记

### ISSUE THREAD

**Issue by Huffer342-WSH** [YunYouJun/valaxy#393]
### Describe the bug

用 ```<!--@include: ./arrival-vector.md{8,}-->```包含文件后，包含进来的文件没有格式

markdown文件如下
![image](https://github.com/YunYouJun/valaxy/assets/78366424/3a0834d7-b1ad-441b-b351-1a40c5ec56ad)

网页效果如下
![image](https://github.com/YunYouJun/valaxy/assets/78366424/b0e10200-6530-4718-9307-f95d7eaac09d)

### Reproduction

none

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 3.47 GB / 15.71 GB
  Binaries:
    Node: 20.12.0 - E:\Program_Files\node-v20.12.0-win-x64\node.EXE
    npm: 10.5.0 - E:\Program_Files\node-v20.12.0-win-x64\npm.CMD   
    pnpm: 9.1.1 - E:\Program_Files\node-v20.12.0-win-x64\pnpm.CMD  
  Browsers:
    Edge: Chromium (124.0.2478.105)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
这里有个问题，也有就是想要 include 原始文本作为示例的需求。

如何区分用户想要原始文本还是编译的文本需要具体讨论下 @KazariEX 

我参考的是 VitePress，我发现它是只支持原始文本。

**Comment by KazariEX** [comment]
可以加一个关键字作区分，比如 import 或者 includeRaw 之类的

**Comment by YunYouJun** [comment]
include 可以先和 vitepress 保持一致。可以为编译后的内容添加新的关键字或标记。

How about `@include-compiled`?

**Comment by KazariEX** [comment]
没问题，就是觉得 ``@include`` 效果和预期不太一致。无论从 vitepress 文档的描述还是示例来看，都更容易让人认为包含的字符串应该是会被当做 Markdown 来处理的，否则 “包含 markdown 文件” 这个标题就很奇怪了，因为包含任何文本文件的效果都是一样的

**Comment by KazariEX** [comment]
我刚刚试了试 vitepress，它是会编译的呀（

**Comment by YunYouJun** [comment]
也许是我记错了。
