### ISSUE TITLE
文章页到达底部目录显示问题

### ISSUE THREAD

**Issue by furtherun** [YunYouJun/valaxy#395]
### Describe the bug

文章到达底部时，目录中应指示最后一条目录，即便最后一个章节的标题到不了锚点定位处。

Demo中[长目录测试](https://yun.valaxy.site/posts/long-toc#checkbox9)，当页面达到最底部，最后一个目录无法点亮。在文章也增加页脚、评论等把文章内容顶上去能解决这个问题，但应该不是本意。

反之，VitePress官方文档[frontmatter页面](https://vitepress.dev/zh/guide/frontmatter#alternative-frontmatter-formats)，文档最后的两个章节都不能达到锚点定位，但页面到最底部，目录标注的是最后一项。

相关代码中指出，“// page bottom - highlight last one”。

https://github.com/YunYouJun/valaxy/blob/82e7752e31a766a45dfc570661322e89b5e57754/packages/valaxy/client/composables/outline/anchor.ts#L49-L62

### Reproduction

https://yun.valaxy.site/posts/long-toc#checkbox8

### System Info

```Shell
System:
    OS: Windows 11 10.0.22635
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 5.51 GB / 15.82 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.53)
    Internet Explorer: 11.0.22621.3566
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Thanks! Now it's be fixed.
