### ISSUE TITLE
主页摘要内容有部分不渲染，代码语法在分级标题中大小有问题

### ISSUE THREAD

**Issue by MengNianxiaoyao** [YunYouJun/valaxy#400]
### Describe the bug

主页摘要内容有部分不渲染
![Clip_2024-06-29_14-01-02](https://github.com/YunYouJun/valaxy/assets/103258286/d9eccc08-2093-4733-a264-bd89746c5cca)
代码语法在分级标题中大小有问题
![Clip_2024-06-29_14-03-46](https://github.com/YunYouJun/valaxy/assets/103258286/2a6ae850-98fe-4133-940f-74fbe19fd1fd)

### Reproduction

依旧如此

### System Info

```Shell
pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
三级标题和四级标题的期望表现是？

---

是否有可复现文本示例？

**Comment by MengNianxiaoyao** [comment]
> 三级标题和四级标题的期望表现是？

在分级标题中，代码语法渲染的大小应该和同级标题差不多大，而不是缩水

> 是否有可复现文本示例？

https://demo-blog.mnxy.eu.org/posts/tech/ohook，主要还是容器部分不渲染

**Comment by YunYouJun** [comment]
需要提供一下原始 markdown 链接，检查一下摘要类型设置？

https://valaxy.site/guide/post#%E6%91%98%E8%A6%81

**Comment by MengNianxiaoyao** [comment]
摘要类型设置是`html`，这个一直都没变
摘要我是这样写的
```
::: tip
eu.org域名白嫖可看[永久免费域名白嫖——eu.org](https://blog.mnxy.eu.org/posts/tech/domain)
:::
<!-- more -->
```

**Comment by MengNianxiaoyao** [comment]
其他类型都能渲染，唯独`html`类型无法渲染

**Comment by MengNianxiaoyao** [comment]
示例站点也有这样的问题
![Clip_2024-06-29_22-40-07](https://github.com/YunYouJun/valaxy/assets/103258286/591ff7bd-a2d3-4460-ab6a-8350e1028930)

**Comment by YunYouJun** [comment]
奇怪，之后检查一下渲染的问题。

**Comment by YunYouJun** [comment]
<img width="1104" alt="image" src="https://github.com/YunYouJun/valaxy/assets/25154432/d1804f29-15e0-48de-b487-2e4351ea810e">

应该只是 ::: tip 等区块规则没有在 post list 的摘要中做渲染，因为逻辑比较重，首页的摘要预览只做了简单的 markdown 渲染。

**Comment by MengNianxiaoyao** [comment]
> <img width="1104" alt="image" src="https://github.com/YunYouJun/valaxy/assets/25154432/d1804f29-15e0-48de-b487-2e4351ea810e">
> 
> 应该只是 ::: tip 等区块规则没有在 post list 的摘要中做渲染，因为逻辑比较重，首页的摘要预览只做了简单的 markdown 渲染。

之前的版本是有做渲染的，不知道为什么给去掉了

**Comment by YunYouJun** [comment]
周末我会检查一下。

**Comment by YunYouJun** [comment]
<img width="479" alt="image" src="https://github.com/YunYouJun/valaxy/assets/25154432/67bb120e-241c-4e5e-ab20-68b97e86531e">

Size is fixed. Will release in v0.19.0

**Comment by YunYouJun** [comment]
<img width="961" alt="image" src="https://github.com/user-attachments/assets/f9034919-dc7c-491f-bc94-ba0a2f4b697e">

Now it works.
