### ISSUE TITLE
[bug] all transition effects related to .dark class switching are invalid

### ISSUE THREAD

**Issue by hairyf** [YunYouJun/valaxy#407]
### Describe the bug

including font color or other attributes, they are all invalid, whether using unocss (transition class) or styles

![GIF](https://github.com/YunYouJun/valaxy/assets/49724027/35cc6487-d874-4ad9-95f4-29586992939a)

### Reproduction

no need to copy, the demo is the same

### System Info

```Shell
--
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
This is the default behavior of [useDark](https://vueuse.org/core/useDark/).

See https://github.com/vueuse/vueuse/issues/3233

[Disable transitions on theme toggle](https://paco.me/writing/disable-theme-transitions)

I'll be thinking about how to expose `disableTransition` options.

**Comment by YunYouJun** [comment]
It's hard for me to get you to override composables on a thematic level. I think the most appropriate approach is to create your own custom `toggleDark` and pass `disableTransition: false` to `useDark`.

Because the buttons that switch themes and the functions that are executed are entirely up to you.

**Comment by WRXinYue** [comment]
For the implementation of this issue, I think it can be written like this, using the modification of the `valaxy-theme-starter` `StarterNav` component as an example:

```vue
<script lang="ts" setup>
// StarterNav.vue
import { isDark, toggleDark, useSiteConfig } from 'valaxy'
import { useThemeConfig } from '../composables'

const siteConfig = useSiteConfig()
const themeConfig = useThemeConfig()

function toggle() {
  // @ts-expect-error startViewTransition is not defined
  const transition = document.startViewTransition(() => {
    toggleDark()
  })

  const startColor = isDark.value ? '#1b1b1f' : '#fff'
  const endColor = isDark.value ? '#fff' : '#1b1b1f'

  transition.ready.then(() => {
    document.body.animate(
      [
        { backgroundColor: startColor },
        { backgroundColor: endColor },
      ],
      {
        duration: 1000,
        easing: 'ease-in',
      },
    )
  })
}
</script>

<template>
  <nav w="full" class="flex justify-between items-center py-10 font-bold">
    <RouterLink class="text-xl" to="/" :aria-label="siteConfig.title">
      <img
        class="inline-block mr-2"
        style="width: 50px; height: 35px"
        alt="logo"
        :src="siteConfig.favicon"
      >
      <span class="hidden md:inline">{{ siteConfig.title }}</span>
    </RouterLink>
    <div class="text-sm text-gray-500 leading-5">
      <template v-for="(item, i) in themeConfig.nav" :key="i">
        <AppLink
          :to="item.link"
          rel="noopener"
        >
          {{ item.text }}
        </AppLink>
        <span v-if="i !== themeConfig.nav.length - 1" class="mr-2 ml-2">·</span>
      </template>
    </div>

    <button type="button" aria-label="Toggle Dark Mode" @click="toggle">
      <div v-if="!isDark" i-ri-sun-line />
      <div v-else i-ri-moon-line />
    </button>
  </nav>
</template>
```

**Comment by YunYouJun** [comment]
@WRXinYue 

Maybe it doesn't have to be that complicated

Just like this:

```ts
import { useDark, useToggle } from '@vueuse/core'

const isDark = useDark({ disableTransition: false })
const toggleDark = useToggle(isDark)

// use toggleDark to toggle
// write your transition css
```

**Comment by hairyf** [comment]
Is it feasible before that? Because it has already been defined in Valaxy, theoretically, the code to disable the transition might have already been executed

**Comment by YunYouJun** [comment]
You're right. It seems to have been affected by the side effects.
It looks like I'll have to break change an api so that it won't be executed by default.
