### ISSUE TITLE
Feat: the calling order of config needs to be optimized.

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#41]
I think the final `ViteValaxyPlugins` method should be optimized to ensure that the three parties (userConfig > themeConfig > defaultConfig) are properly merged and called in sequence.

This is my irresponsible guess, but from the call flow of `ViteValaxyPlugins`, there is a high probability that there will still be problems

For example, using `markdown.config` in `theme` will invalidate or overwrite the `markdown.config` of a certain configuration

![image](https://user-images.githubusercontent.com/49724027/178136347-1ad3ea0c-9679-40a3-96fa-a2ab3535c56d.png)

**Comment by YunYouJun** [comment]
`markdown.config` is mssing, I think there should be no problem with other merged options.

**Comment by TuiMao233** [comment]
dude this is too bad you should test if it actually works when you commit

![image](https://user-images.githubusercontent.com/49724027/178137736-d695e413-4d70-44d4-ad7b-75df62a71683.png)

`configResolved` will not be called immediately, and the plugin configuration of md plugins has already been called, which means it will not take effect

![image](https://user-images.githubusercontent.com/49724027/178137777-9b010d73-5564-4721-99e4-e1c0decf66b3.png)
