### ISSUE TITLE
Markdown footnote tooltip

### ISSUE THREAD

**Issue by YunYouJun** [YunYouJun/valaxy#416]
### Clear and concise description of the problem

Markdown 默认的 footnote 为底部内容的跳转。

### Suggested solution

支持通过鼠标悬浮的方式直接展示脚标提示。

Supports the direct display of the footnote tooltip through the mouse hover.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by BlueGlassBlock** [comment]
I would like to try implement this.

IMO We can aim to get something like https://squidfunk.github.io/mkdocs-material/reference/footnotes/

**Comment by YunYouJun** [comment]
> I would like to try implement this.
> 
> IMO We can aim to get something like [squidfunk.github.io/mkdocs-material/reference/footnotes](https://squidfunk.github.io/mkdocs-material/reference/footnotes/)

That's cool. I think that's exactly what we wanted to do. Let’s do it.
