### ISSUE TITLE
node在新版本弃用了punycode模块

### ISSUE THREAD

**Issue by sgj123456** [YunYouJun/valaxy#417]
### Describe the bug

(node:33808) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

### Reproduction

https://gitee.com/maopaonew/maopaonew.git

### System Info

```Shell
System:
    OS: Linux 6.10 Arch Linux
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 10.17 GB / 15.21 GB
    Container: Yes
    Shell: 3.7.1 - /usr/bin/fish
  Binaries:
    Node: 22.5.1 - /usr/bin/node
    npm: 10.8.2 - /usr/bin/npm
    pnpm: 9.6.0 - /usr/bin/pnpm
    bun: 1.1.20 - /usr/bin/bun
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by WRXinYue** [comment]
At this moment, there's not much you can do since the ecosystem includes modules that rely on punycode, which is set to be deprecated in the future. 

For now, you can disregard that warning – it's not an error and doesn't pose any immediate concern.

You can track the related issue here:

- https://github.com/lupomontero/psl/issues/323

**Comment by sgj123456** [comment]
> There's little you can do right now – the ecosystem has modules that depend on punycode which will be deprecated sometime in the future.
> 
> For the time being, ignore that warning – it is not an error, and is not a cause for concern.
> 
> You can track the related issue here:
> 
> - https://github.com/lupomontero/psl/issues/323
> - https://github.com/jsdom/jsdom/issues/3613

Thanks

**Comment by YunYouJun** [comment]
<img width="257" alt="image" src="https://github.com/user-attachments/assets/1c07ac00-f3dc-4a6d-8062-f0faf4e97e3f">

`punycode` is the dependency of `markdown-it`.

When markdown updates, we will update it immediately.

Since it is an upstream issue and does not cause bugs, we will close it first.
