### ISSUE TITLE
Feature Request: 全文 RSS

### ISSUE THREAD

**Issue by j1g5awi** [YunYouJun/valaxy#419]
### Clear and concise description of the problem

迁移到 Valaxy 才发现生成的 RSS 就不是全文，希望能生成全文

### Suggested solution

在

```ts
feed: {
    name: string
    favicon: string
  }
```

处增加选项并在 https://github.com/YunYouJun/valaxy/blob/f2431d2d255519d5795a27a7584c7f8dfa8a3672/packages/valaxy/node/modules/rss.ts#L108 此处判断

### Additional context

另外，RSS 生成的 `访问 <a href="" target="_blank"></a> 阅读全文。</p>` 也不知为何实际没有链接，连 https://yunyoujun.cn/atom.xml 亦是如此。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
RSS 通常用于订阅更新，全文会导致 rss 非常大。
后续会添加开关，但并不推荐使用全文。

**Comment by YunYouJun** [comment]
Try `modules.rss.fullText: true`

**Comment by j1g5awi** [comment]
bug: 访问全文的提示在开启全文 RSS 后仍存在。



> RSS 通常用于订阅更新，全文会导致 rss 非常大。

這就是添加另一箇配置項的問題了：RSS 文章數量限制。
