### ISSUE TITLE
使用html添加的图片放大不正常

### ISSUE THREAD

**Issue by myp0402** [YunYouJun/valaxy#420]
### Describe the bug

如
```html
<img src="https://example.com/example.jpg" style="zoom:33%;" />
```
使用html设置图片缩放大小后的情况下 会导致点击后位置不正常 我博客的[这篇文章](https://myp0402.github.io/posts/%E5%8D%9A%E5%AE%A2%E5%A4%8D%E6%B4%BB%E8%AE%B0) 的第一张图片（那个meme）就是这种情况

### Reproduction

我博客的[这篇文章](https://myp0402.github.io/posts/%E5%8D%9A%E5%AE%A2%E5%A4%8D%E6%B4%BB%E8%AE%B0) 的第一张图片（那个meme）

### System Info

```Shell
System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1
    Memory: 136.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.5.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KazariEX** [comment]
看起来应该是上游插件 [medium-zoom](https://github.com/francoischalifour/medium-zoom) 的问题

**Comment by WRXinYue** [comment]
使用 zoom 会影响插件缩放的 transform 定位，请将 `zoom: 33%;` 修改为 `width: 33%;` 以达到类似效果

**Comment by YunYouJun** [comment]
Try `scale-33` or `w-1/3` instead of `zoom`.

```html
<img src="https://example.com/example.jpg" class="scale-33" />
<img src="https://example.com/example.jpg" class="w-1/3" />
```
