### ISSUE TITLE
打包后部署到iis刷新后出现403问题

### ISSUE THREAD

**Issue by ixhaos** [YunYouJun/valaxy#426]
### Describe the bug

正常是能打开的
![image](https://github.com/user-attachments/assets/c8840bf5-02b7-4156-89d6-0caff461a91a)
但是在这个页面刷新之后就出现403
![image](https://github.com/user-attachments/assets/6b36d592-6f1d-4b8d-9693-62302e3f74c2)

### Reproduction

打开后正常显示，刷新之后出现403

### System Info

```Shell
win10,google,使用pnpm build构建
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
403 是没有权限吧

**Comment by ixhaos** [comment]
> 403 是没有权限吧

权限应该是没问题的吧？第一次加载的时候可以正常显示，刷新的时候出现403

**Comment by YunYouJun** [comment]
第一次是因为是路由模拟，但是刷新的时候是需要真正访问到这个页面 html。
如果你使用其他平台部署不会复现这个问题，那所剩的可能就是你自己的权限问题了。

**Comment by ixhaos** [comment]
> 第一次是因为是路由模拟，但是刷新的时候是需要真正访问到这个页面 html。 如果你使用其他平台部署不会复现这个问题，那所剩的可能就是你自己的权限问题了。

但是在打开文章的时候，也会出现相同的问题，第一次没问题。第二次会出现404，跟其他页面的报错又不一样。

**Comment by YunYouJun** [comment]
这并不是框架层面的问题，而是你的部署问题。除非你可以在第三方平台上部署复现。
如果你不解决服务配置的问题，即便你使用其他框架也会出现相同问题。

**Comment by YunYouJun** [comment]
方案：

- 使用 netlify/vercel/cloudflare/gh-pages 等托管方案部署。
- 检查本地权限问题。
- 提供最小可复现环境与代码。

由于没有更多信息以复现，我将先关闭该 Issue。
