### ISSUE TITLE
fix: the calling order of config needs to be optimized. 

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#43]
Source #41, dude this is too bad you should test if it actually works when you commit

![image](https://user-images.githubusercontent.com/49724027/178137736-d695e413-4d70-44d4-ad7b-75df62a71683.png)

`configResolved` will not be called immediately, and the plugin configuration of md plugins has already been called, which means it will not take effect

And the subsequent configuration will still not be updated

![image](https://user-images.githubusercontent.com/49724027/178137777-9b010d73-5564-4721-99e4-e1c0decf66b3.png)

and all synchronous calls will not benefit from

![image](https://user-images.githubusercontent.com/49724027/178138988-e724f977-681e-4018-9f5c-181cbf8ea301.png)

_Originally posted by @TuiMao233 in https://github.com/YunYouJun/valaxy/issues/41#issuecomment-1179684961_

**Comment by TuiMao233** [comment]
I think the necessity of config process optimization can be illustrated in the form of a flow chart

![image](https://user-images.githubusercontent.com/49724027/178138208-51715815-9705-403d-a569-9efd095bacf2.png)

And the configuration room has the following characteristics

1. Should have deep merges, with higher priority overriding lower priority
2. Function class method, using chain call to ensure that each level can get benefits
3. The final result is correct. The above rules are assigned and adjusted so that third parties (vite-plugin-pages, markdown, vue, components, unocss) can be correctly integrated

**Comment by TuiMao233** [comment]
I can provide PRs, but I think it's the core functionality that should be dominated by you, so what's your opinion @YunYouJun

**Comment by YunYouJun** [comment]
I think we can `setupMarkdownPlugin` in/after `configResolved`.

`enforce: 'pre'` need be added in `'valaxy:config:resolved'`, i missed it.

`userConfig` is configed by `vite.config.ts` & `valaxy.config.ts`.
ThemePlugin config (`themeConfig` To avoid confusion) by `vite.config.ts` & `valaxy.config.ts` is merged.
`defaultConfig` is merged too.

For now, only ThemePlugin config need `config()`. Of course, it would be appropriate to combine them all.
This seems to be getting more and more complicated, And I was wondering if I could just extend it in `vite.config.ts`.
Then merge them. `config()` is no longer needed. We wouldn't have the sync async problem we have.

```ts
export default defineConfig({
  valaxy(options) {
    return {
       unocss: {} // xxx
    }
  }
})
```

Anyway, if you have a better idea, PR is welcome.

**Comment by TuiMao233** [comment]
Yes, I think the essential problem is that the configuration of the exposed config and userConfig in the theme is too different, and the actual merge time is not correct.

themeConfig should be the next process that should be merged when reading userConfig, but this process is now skipped

The result is that it is handled when config is finally used, resulting in various problems that follow

**Comment by TuiMao233** [comment]
I think at this stage, we should revisit and design the configuration items of theme config instead of working right away

**Comment by YunYouJun** [comment]
You are right. My previous job was a little thoughtless.

**Comment by YunYouJun** [comment]
I would like to know how you complete the `config()` merge process shown in flowchart.

**Comment by TuiMao233** [comment]
Ok, I think the processing of config (including theme config) should be separated into a separate processing module, which should be processed before `build`, `createServer`, `ssrBuild`

And in the theme, not only as a vite plugin, but a more comprehensive configuration

**Comment by TuiMao233** [comment]
I think the extension of the theme can refer to the process of vitepress

```ts
// user or theme or default
// valaxy.config.ts
const config = defineConfig({
  // valaxy config
  vite: {
    // vite config
  }
})

export config
```

**Comment by TuiMao233** [comment]
Of course, as a theme can have more options, the user's configuration as a downgrade configuration

user config
```ts
// valaxy.config.ts
import { defineConfig } from 'valaxy'
export default defineConfig({...})
```

theme config
```ts
// theme/node/index.ts
// Tentative defineThemeConfig
import { defineThemeConfig } from 'valaxy'
export default defineThemeConfig({...})
```

**Comment by TuiMao233** [comment]
> I would like to know how you complete the `config()` merge process shown in flowchart.

If it is implemented, I think it can be achieved by custom merge

Take lodash as an example: 

![image](https://user-images.githubusercontent.com/49724027/178143686-65571f76-e00a-4563-84ca-9b56ccb175d1.png)

**Comment by YunYouJun** [comment]
I think we do not need to merge the contents of `config()` since we already allow users to do this.

```ts
function themeYun(options){
  return {
    vite: {
      // vite config
    },
    vue: {
      // vite-plugin-vue config
    },
    pages: {
      // vite-plugins-pages config
    },
    components: {
      // vite-plugins-components config
    },
    markdown: {
      // md config
    },
    extendMd() {
      // extends md data
    }
  }
}
```

Although this may cause the `valaxy` to no longer be set in `config()`. 
But `config()` itself will be merged again by Vite, and since we have a cleaner way, there is no need to merge here.
I thought it would be more elegant to keep it simple as Vite native.

**Comment by TuiMao233** [comment]
> Although this may cause the `valaxy` to no longer be set in `config()`. But `config()` itself will be merged again by Vite, and since we have a cleaner way, there is no need to merge here. I thought it would be more elegant to keep it simple as Vite native.

In fact, you should look into `vite`'s `mergeConfig`, you will find that `mergeConfig` does not handle methods such as `function`

Why? `vite.config` itself does not have any callback properties, which `vitepress` does, but `vitepress` does not need to be processed, because `vitepress` config is unique

The speciality of `valaxy` is that it has multiple configs and functions, which are not taken into account by `vite` and `vitepress`
