### ISSUE TITLE
大佬，提个建议，图片预览功能增强

### ISSUE THREAD

**Issue by xulei131401** [YunYouJun/valaxy#436]
### Clear and concise description of the problem

valaxy 使用的medium-zoom 好像只能缩放，没有图片翻转功能。

### Suggested solution

希望集成 Element Plus的ElImage组件，提供图片翻转功能。

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by YunYouJun** [comment]
图片翻转功能并不长，为了 `ElImage` 集成，依赖太重了，没有必要作为默认功能。
独立的图片预览库没有找到更轻量简单的。

**Comment by xulei131401** [comment]
能否提供一个钩子或者别的方式，我想用自定义的组件覆盖框架的默认预览行为

**Comment by YunYouJun** [comment]
<img width="395" alt="image" src="https://github.com/user-attachments/assets/58080161-2aa4-496e-a276-f8d0ff0a632c">

`defineAppSetup` 自定义任意全局的副作用。

**Comment by YunYouJun** [comment]
你可以使用 `valaxy-addon-lightgallery` 作为替代。

https://github.com/YunYouJun/valaxy/tree/main/packages/valaxy-addon-lightgallery
