### ISSUE TITLE
valaxy-addon-meting 插件能否增加一个控制显示隐藏的属性

### ISSUE THREAD

**Issue by xulei131401** [YunYouJun/valaxy#437]
### Clear and concise description of the problem

经过测试发现，global属性设置为 true或者false，播放器始终在左下角，好像没效果。没太理解global的作用
而且文章的aplayer: true|false也不能控制左下角的播放器显示隐藏

作者大大有空的时候帮忙解答一下

### Suggested solution

设想：global为true,播放器始终在左下角，但具体的页面可以通过aplayer属性控制其显示隐藏
大部分页面都需要这个播放器，极个别的页面想隐藏这个播放器

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yixiaojiu** [comment]
我下午看看

**Comment by WRXinYue** [comment]
`frontmatter aplayer` 为弃用的配置项，早期 valaxy 内置 的 aplayer 功能。该配置与 `valaxy-addon-meting` 插件无关。考虑将此功能迁移至 `valaxy-addon-meting` 插件中

**Comment by xulei131401** [comment]
理解，我是照着文档上操作的，各种方法都尝试过了，然后来求助的。
辛苦作者大大了

**Comment by yixiaojiu** [comment]
已经添加了，但是没有发版

**Comment by xulei131401** [comment]
好的，不急，由衷感谢作者大大

**Comment by YunYouJun** [comment]
> 已经添加了，但是没有发版

Valaxy 需要发版吗？

**Comment by yixiaojiu** [comment]
> > 已经添加了，但是没有发版
> 
> Valaxy 需要发版吗？

valaxy不需要，直改动了插件的代码

**Comment by YunYouJun** [comment]
@yixiaojiu `valaxy-addon-meting` 包加你权限了，可以发一下。

**Comment by YunYouJun** [comment]
先发掉了。0.1.4  https://github.com/YunYouJun/valaxy/pull/452
