### ISSUE TITLE
categories 不能是中文吗？路径跳不过去

### ISSUE THREAD

**Issue by xulei131401** [YunYouJun/valaxy#438]
### Describe the bug

![微信图片_20240904221606](https://github.com/user-attachments/assets/fbe3bd1a-8e7c-4d83-a4e0-61b59fc18a6e)
![微信图片_20240904221702](https://github.com/user-attachments/assets/709e4a26-4d59-4c52-9a15-5f363ad06d51)

### Reproduction

markdown categories 设置多个级别的中文就可复现

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 2.37 GB / 15.67 GB
  Binaries:
    Node: 20.12.2 - E:\BlogCode\nodejs20.12.2\node.EXE
    npm: 10.5.0 - E:\BlogCode\nodejs20.12.2\npm.CMD
    pnpm: 9.0.6 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Markdown 原文怎么写的？

**Comment by xulei131401** [comment]
---
title: 异常
date: 2024-09-04
updated: 2024-09-04
categories:
  - java技术栈
  - java基础
  - 异常
tags:
  - java
top: 1
---

# {{ $frontmatter.title }}

类似这样

**Comment by xulei131401** [comment]
![微信图片_20240905124731](https://github.com/user-attachments/assets/d2bb2442-47c1-4007-8cdc-2c2d6f83987c)
类似这样

**Comment by qtqz** [comment]
刚才发现了，不需要设置多个级别的中文，小云的站也这样，我提了

**Comment by YunYouJun** [comment]
@WRXinYue 

https://github.com/YunYouJun/valaxy/blob/e68dea45ca95c397473751203dcef81a2fca4b8d/packages/valaxy/client/utils/time.ts#L19

`formatDate` 是一个 utils，不应该在内部使用 composable。

**Comment by WRXinYue** [comment]
> @WRXinYue
> 
> https://github.com/YunYouJun/valaxy/blob/e68dea45ca95c397473751203dcef81a2fca4b8d/packages/valaxy/client/utils/time.ts#L19
> 
> `formatDate` 是一个 utils，不应该在内部使用 composable。

有没有更好的方式，在切换语言的时候需要同时给日期时间语言进行切换，我不清楚为什么在这种情况下会出这个错误

**Comment by YunYouJun** [comment]
> > @WRXinYue
> > https://github.com/YunYouJun/valaxy/blob/e68dea45ca95c397473751203dcef81a2fca4b8d/packages/valaxy/client/utils/time.ts#L19
> > 
> > `formatDate` 是一个 utils，不应该在内部使用 composable。
> 
> 有没有更好的方式，在切换语言的时候需要同时给日期时间语言进行切换，我不清楚为什么在这种情况下会出这个错误

我已经通过全局变量修复了，utils 应当是一个函数，不能在内部执行 setup 的相关逻辑。
因为它可能被嵌套在模板、composable、watch 等中使用。
