### ISSUE TITLE
feat: post automatically reads the creation time

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#45]
post can automatically read the creation time instead of outputting a warning when the user does not specify a date

file: `valaxy/node/plugins/preset.ts`

![image](https://user-images.githubusercontent.com/49724027/178151195-1d523364-987a-4d18-8a63-01968e0c535f.png)

**Comment by YunYouJun** [comment]
It generally works, but the CI will always be up to date at the time.
So I thought it would be nice to have an exact date.

I'll add a default Git timestamp later as a complement.

**Comment by YunYouJun** [comment]
Emm, should provide a configuration for the user to decide.

**Comment by TuiMao233** [comment]
I think part of the logic can be boiled down to the theme, which allows our core to only handle the part it should be responsible for

**Comment by YunYouJun** [comment]
> https://hexo.io/zh-cn/docs/configuration#%E6%97%A5%E6%9C%9F-x2F-%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F

Like Hexo, I don't think this should be a theme to worry about again, but rather an optional feature provided by the framework.

**Comment by TuiMao233** [comment]
sounds good, maybe he is

```ts
  moment: {
    format: 'YYYY-MM-DD',
    mtime: 'git'
  },
```

I think ctime can be provided by default, mtime can be read file information, or use git timestamp

**Comment by TuiMao233** [comment]
> Format can be handled by theme. Different themes may display different styles, etc `Jul 8` `8/7/2022`.

This seems fine, but I think the user should still be able to decide the format he displays

**Comment by YunYouJun** [comment]
```ts
updated: {
  format: 'YYYY-MM-DD',
  type: 'git' | 'mtime' | 'date'
}
```

Emm also seems to provide the created date format.

**Comment by YunYouJun** [comment]
After thinking about, I think this is actually a bit redundant.

`Date` is used when use write `date: xxx`.
`Git` is used by default if the user has git information.
`Mtime` is used when the user only has the change time.

It is often not necessary to set them up.

As for the date format, we can provide config `date.format` as the default format, it is then up to the theme and the user to decide whether to use it.
