### ISSUE TITLE
[Bug] 标签与分类页面的文章显示异常

### ISSUE THREAD

**Issue by qtqz** [YunYouJun/valaxy#450]
### Describe the bug

进入标签或分类页面后，点一个标签，再点另一个标签，下面就无法显示任何文章了。dev 和构建后的异常好像不太一样。

你的网站也有这个问题，可以直接去看 ↓

### Reproduction

https://www.yunyoujun.cn/tags/

### System Info

```Shell
valaxy 0.19.9
EDGE 127.0.2651.74
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
应该和 https://github.com/YunYouJun/valaxy/issues/438 的原因一样。
