### ISSUE TITLE
waline 邮件、后台文章链接无法访问

### ISSUE THREAD

**Issue by HoronLee** [YunYouJun/valaxy#464]
### Describe the bug

waline 有新评论会发送邮件，其中包含了文章链接和博客链接，但是点击无任何响应，
<img width="2340" alt="image" src="https://github.com/user-attachments/assets/15bba884-0856-4724-9929-30b56741331d">
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/e8bd02a6-9c2c-4d09-96d8-ea3562506851">
waline 后台文章跳转链接点击跳转报错
![QQ_1729128107036](https://github.com/user-attachments/assets/bd3e2cb7-52a5-4cb6-a0c4-88c0ce51bb1c)
```json
{
    "errno": 404,
    "errmsg": "url `/posts/OpenStack-note` not found."
}
```

### Reproduction

waline 邮件、后台文章链接无法访问

### System Info

```Shell
vercel 部署
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
是否为 vercel 部署站点，需要添加 `cleanUrls` 配置。

参见：https://valaxy.site/guide/deploy#vercel

**Comment by HoronLee** [comment]
已解决，通过使用[kotodama 言灵](https://github.com/YunYouJun/kotodama)作为waline的管理后台即可，且界面很友好。
登录的时候url填写已有的waline域名，邮箱密码填写waline管理员的即可。
