### ISSUE TITLE
希望增添中英文按钮隐藏的配置项

### ISSUE THREAD

**Issue by wzdxslzgzbdm** [YunYouJun/valaxy#465]
### Clear and concise description of the problem

我的站点暂时还没有双语的需求 所以那个中英文切换按钮放在那完全没有任何用处
![4dc78544dc334ee23f9daeaf357a011a](https://github.com/user-attachments/assets/8c5cc0d5-dc94-41ba-9b02-d5ae82032409)

### Suggested solution

 希望是能在配置文件中对此按钮进行隐藏

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by WRXinYue** [comment]
只需在 `components` 文件夹中创建与 `YunToggleLocale` 同名的组件，进行替换即可，如

```vue
<template>
  <div />
</template>
```

**Comment by YunYouJun** [comment]
你可以通过设置 `site.config.ts` 中的 `languages: ['zh-CN']` 来指定只使用一种语言。
