### ISSUE TITLE
docker build失败

### ISSUE THREAD

**Issue by skret028** [YunYouJun/valaxy#475]
### Describe the bug

使用文档的docker构建方法报错，开启了代理以下载资源。
ERROR  ENOENT: no such file or directory, lstat '/app/packages'
缺少这个文件夹，应该修改哪个配置文件呢？

server:/xx/valaxy-blog$ sudo docker build -t xxxx/valaxy-blog:v1.0 .
[+] Building 468.3s (14/15)                                                                              docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 637B                                                                               0.0s
 => [internal] load metadata for docker.io/library/nginx:stable-alpine                                             2.5s
 => [internal] load metadata for docker.io/library/node:20-alpine                                                  2.5s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [production-stage 1/3] FROM docker.io/library/nginx:stable-alpine@sha256:d6f8c6b38edf2b7c6619718ad7a00caa4ed4  0.0s
 => [build-stage 1/7] FROM docker.io/library/node:20-alpine@sha256:b1e0880c3af955867bc2f1944b49d20187beb7afa3f301  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 1.02kB                                                                                0.0s
 => CACHED [build-stage 2/7] WORKDIR /app                                                                          0.0s
 => CACHED [build-stage 3/7] RUN corepack enable                                                                   0.0s
 => CACHED [build-stage 4/7] COPY .npmrc package.json pnpm-lock.yaml ./                                            0.0s
 => CACHED [production-stage 2/3] COPY nginx.conf /etc/nginx/nginx.conf                                            0.0s
 => [build-stage 5/7] RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store     pnpm install --no-froze  462.2s
 => [build-stage 6/7] COPY . .                                                                                     0.4s
 => ERROR [build-stage 7/7] RUN pnpm build                                                                         2.7s
------
 > [build-stage 7/7] RUN pnpm build:
0.992
0.992 > @valaxyjs/monorepo@0.20.4 build /app
0.992 > pnpm run build:@valaxyjs/utils && pnpm run build:valaxy && pnpm run build:devtools
0.992
1.377
1.377 > @valaxyjs/monorepo@0.20.4 build:@valaxyjs/utils /app
1.377 > pnpm -C packages/@valaxyjs/utils run build
1.377
1.747  ERROR  ENOENT: no such file or directory, lstat '/app/packages'
1.748 For help, run: pnpm help run
1.761  ELIFECYCLE  Command failed with exit code 1.
1.786  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:14
--------------------
  12 |
  13 |     COPY . .
  14 | >>> RUN pnpm build
  15 |
  16 |     FROM nginx:stable-alpine as production-stage
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm build" did not complete successfully: exit code: 1

### Reproduction

下载这里的.npmrc package.json pnpm-lock.yaml ，Dockerfile中配置代理，并运行docker built -t valaxy-blog:v1.0 .

### System Info

```Shell
4790K 32G 飞牛OS中使用docker built
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
```bash
RUN corepack enable
```

启用  corepack，并添加 package.json `packageManager: "pnpm@9.14.1"` 以自动安装 pnpm。

**Comment by skret028** [comment]
> ```shell
> RUN corepack enable
> ```
> 
> 启用 corepack，并添加 package.json `packageManager: "pnpm@9.14.1"` 以自动安装 pnpm。

修改了package.json里的   "packageManager": "pnpm@9.13.2",   -->    "packageManager": "pnpm@9.14.1",

还是一样的报错，Dockerfile用的文档里的示例：
```
FROM node:20-alpine as build-stage

WORKDIR /app
ENV HTTP_PROXY=http://192.168.1.1:7890
ENV HTTPS_PROXY=http://192.168.1.1:7890
RUN corepack enable

COPY .npmrc package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

FROM nginx:stable-alpine as production-stage

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
```

**Comment by YunYouJun** [comment]
<img width="709" alt="image" src="https://github.com/user-attachments/assets/993812e4-1158-4255-85de-5d3c22276d69">

显然你使用的是 `valaxy` 源代码项目，而非 `pnpm create valaxy` 初始化的博客项目代码。

源代码项目包括构建工具、脚手架、库等多种代码，`Dockerfile` 旨在构建 valaxy-blog 的站点而非构建源代码开发环境。
