### ISSUE TITLE
Problems for the new prologue screen when resizing / aligning social icons

### ISSUE THREAD

**Issue by BlueGlassBlock** [YunYouJun/valaxy#476]
### Describe the bug

After resizing, YunAEFrame still fits one screen yet other components don't change their location, causing underflow / overflow 
![image](https://github.com/user-attachments/assets/9b81e256-13de-4cf2-a328-6e639c0ba173)

Also PrologueSocialIcons don't always align perfectly on horizonal directions:
![ebca7495e7c569c949e4df63a55d4cf8](https://github.com/user-attachments/assets/632d86a6-c725-4edc-bcef-37e1d0370fce)

### Reproduction

pnpm demo on f18df81 (main)

### System Info

```Shell
Irrelevant
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
New design had changed.
