### ISSUE TITLE
press主题的 nav配置 不支持分组

### ISSUE THREAD

**Issue by xulei131401** [YunYouJun/valaxy#477]
### Describe the bug

press主题的 nav配置 不支持分组，以下是vitepress官网的示例代码，渲染不出来。。。
```js
themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide' },
      {
        text: 'Dropdown Menu',
        items: [
          {
            // Title for the section.
            text: 'Section A Title',
            items: [
              { text: 'Section A Item A', link: '...' },
              { text: 'Section B Item B', link: '...' }
            ]
          }
        ]
      },
      {
        text: 'Dropdown Menu',
        items: [
          {
            // You may also omit the title.
            items: [
              { text: 'Section A Item A', link: '...' },
              { text: 'Section B Item B', link: '...' }
            ]
          }
        ]
      }
    ]
  }
```

### Reproduction

press主题的 nav配置 不支持分组，以下是vitepress官网的示例代码，渲染不出来

### System Info

```Shell
Browsers
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
Press 是一个 eat dog food 的主题，它参考了 vitepress 并进行了一些自定义。
对于文档无其他自定义需要，推荐直接使用 VitePress。

它建于早期，VitePress 可能存在一些 API 变更，并未兼容跟进，将在之后修复。

**Comment by YunYouJun** [comment]
Released in v0.22.5.
