### ISSUE TITLE
bug: dev theme hot update unocss.config.ts invalid

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#48]
![image](https://user-images.githubusercontent.com/49724027/178704433-853abec0-2d81-48d2-9b53-694772ba8e45.png)

**Comment by YunYouJun** [comment]
https://github.com/unocss/unocss/blob/9fd1583aff3be2ff04a775458cf023e080f23c5c/packages/vite/src/config-hmr.ts#L24

Since I can't get the ctx of unocss, I haven't figured out a good way to hot reload it at the moment.

**Comment by TuiMao233** [comment]
Is there a way we can trigger `change`, and pass `if (!sources.includes(p))`

**Comment by YunYouJun** [comment]
> Oops, After reading the source code, I found that it also supports a `configDeps` configuration, which I will see if I can implement with it.

Not work. I can not re-pass my config to init UnoCSS plugins.

**Comment by YunYouJun** [comment]
Unfortunately, we have not received feedback from unocss so far, and corresponding functions cannot be realized from valaxy's perspective.
