### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by wyyaa123** [YunYouJun/valaxy#484]
### Describe the bug

你好，我在Windows上想部署该博客，在执行`npm init valaxy`或`pnpm create valaxy`过程中, 会分别抛出以下错误:
#1 nmp
```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "catalog:": catalog:
npm error A complete log of this run can be found in: C:\Users\86311\AppData\Local\npm-cache\_logs\2024-12-12T08_15_49_108Z-debug-0.log
```
#1 pnpm
```
 ERR_PNPM_CATALOG_ENTRY_NOT_FOUND_FOR_SPEC  No catalog entry 'typescript' was found for catalog 'default'.
```
在issue内也没发现有人题此问题.

### Reproduction

Windows11

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 14.87 GB / 23.35 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (131.0.2903.70)
    Internet Explorer: 11.0.26100.1882
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
`catalog` 是 pnpm 的一个新特性，模板并不要求 pnpm 的版本，我将尽快回退修复。
