### ISSUE TITLE
Optimize time format, remove luxon

### ISSUE THREAD

**Issue by YunYouJun** [YunYouJun/valaxy#486]
### Clear and concise description of the problem

Luxon introduced in https://github.com/YunYouJun/valaxy/pull/428

After manual chunks, I found that they were up to 100kb in volume.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/a30254c8-171c-41b4-9781-0ef5d567b6c7" />

### Suggested solution

Needs to be simplified and luxon should be removed.

### Alternative

We sacrifice so much for time zones that are rarely used.

### Additional context

If there are too many problems with date-fns, we can consider returning to dayjs. Although it does not support the esm.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by WRXinYue** [comment]
I'm fine with it. If needed, I can change this feature into a separate cross-timezone date plugin.

**Comment by YunYouJun** [comment]
I've fallen back to dayjs and written e2e and unit tests, and they seem to be working fine.

It's about a sixth of the size of `date-format` + `luxon`.
