### ISSUE TITLE
feat: Support custom icons configs

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#50]
it should work for user or theme

![image](https://user-images.githubusercontent.com/49724027/178889730-758511bf-68ca-4dce-80eb-b246de3ce809.png)

related information:

https://github.com/unocss/unocss/tree/main/packages/preset-icons#nodejs

**Comment by TuiMao233** [comment]
and we should process and optimize the incoming icon content

![image](https://user-images.githubusercontent.com/49724027/178890944-57b15b58-0f54-440d-82b8-1137e343b674.png)

**Comment by YunYouJun** [comment]
We can expose config of `presetIcons()`.

The rest content, I think, should be done by the user themselves (via `presetIcons`).

**Comment by YunYouJun** [comment]
I will expose `preseIcons`, but SVG helper for clean which I don't think is very cost-effective. (Frequency of use vs cost of implementation)

**Comment by TuiMao233** [comment]
Maybe we can do it as a plugin, it's pluggable

**Comment by YunYouJun** [comment]
What is its form of implementation?

**Comment by TuiMao233** [comment]
Actually I really like the design of iles plugins, it is very simple and can carry parameters for users to use

https://iles.pages.dev/guide/plugins

**Comment by TuiMao233** [comment]
We should also provide a plugin system, which allows our actual code to be better organized and users to use a specific function more specifically.

**Comment by TuiMao233** [comment]
I have some ideas, I can submit some packages about the pugin part, what do you think?

**Comment by TuiMao233** [comment]
In fact, using vite as a plugin side has great limitations, which makes me feel that it will become more and more complicated to use, and our internal code will become more and more bloated

I think that a downgraded plugin configuration is needed for users, and we should try to put more details of independent modules on the plugin.

**Comment by TuiMao233** [comment]
I have also developed some libraries before, it was very simple at first, I just piled a bunch of functions together

But slowly I needed more features, and my previous code made me unable to do anything, finally I refactored the project, added the plugins system, and everything became better

There are many similarities between the current valaxy, I always feel that the core code is responsible for too many tasks, it should be more decentralized and let plugins handle the details

**Comment by YunYouJun** [comment]
OK. If a plugin exists, I think it should be similiar as the form of Slidev addons.

> https://sli.dev/addons/write-an-addon.html

---

> I have some ideas, I can submit some packages about the plugins part, what do you think?

I'm currently working on its website and documentation, which I think are a higher priority.
If you are interested, you are welcome to submit PR.
But I may not be able to focus on that in the short term.

**Comment by TuiMao233** [comment]
> OK. If a plugin exists, I think it should be similiar as the form of Slidev addons.

This is a good suggestion. I will open a new issue in the future as a constructive discussion on the api of plugins, which is somewhat similar to the rfc of vue

**Comment by LoTwT** [comment]
> In fact, using vite as a plugin side has great limitations, which makes me feel that it will become more and more complicated to use, and our internal code will become more and more bloated, eventually it becomes difficult to scale
> 
> I think that a downgraded plugin configuration is needed for users, and we should try to put more details of independent modules on the plugin.

Can you describe the limitations that make you feel complicated to use vite plugins ? 

Valaxy needs a plugin system. I think the plugin system of Vite seems to be a not bad choice. If there are some problems that vite plugins can't solve ?

 A self-designed plugin system may cost much more time and lack of testing by more users . With the new one, Valaxy will manage two plugin systems at the same time, it is not necessary and may cause more problems for cooperation between the two plugin systems .
