### ISSUE TITLE
question: how to use icons other than remix icon

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#51]
https://icones.netlify.app/ has a lot of icons, but it looks like we can only use the remix icon

**Comment by TuiMao233** [comment]
![image](https://user-images.githubusercontent.com/49724027/178922624-54939a3f-f752-4c0c-adee-1e8a3e307405.png)

**Comment by TuiMao233** [comment]
![image](https://user-images.githubusercontent.com/49724027/178922736-f1ae30d8-d6b5-4761-8041-6b48a72d85f6.png)

**Comment by YunYouJun** [comment]
```bash
pnpm i @iconify-json/carbon
```

Install collections what you need.
