### ISSUE TITLE
feat: configuration change handling

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#56]
related: #56

- `user/valaxy.config.ts` > `user/site.config.ts`
- `user/vite.config.ts` > `user/valaxy.config.ts`
- remove `vite.valaxy`
- handling details and hot load config

other:

- `user/vite.config.ts`
- `theme/vite.config.ts`
- `theme/valaxy.config.ts`
- doc update(part)

**Comment by YunYouJun** [comment]
For Single-file obsessive user:

```ts
// valaxy.config.ts
export default defineConfig({
  // site info config
  site: {},
  // all vite config
  vite: {},
  // markdown plugin
  markdown: {}
  // other internal plugin
  // ...
})
```

For beginner:

```ts
// site.config.ts for site info
export default defineSite({})
```

For users who like categorization:

- `vite.config.ts` for vite
- `valaxy.config.ts` for internal plugin
- `site.config.ts` for site info config

**Comment by TuiMao233** [comment]
I think we should switch between different identities at will for the convenience of all users

![image](https://user-images.githubusercontent.com/49724027/179340136-a5a1145e-874d-4aac-8f2b-7575e9f06c7b.png)

This will happen if mixed together, users and themes cannot be switched at will, and theme valaxy needs to be handled separately

![ab79949e8ce2b5989ea8cb659047b92](https://user-images.githubusercontent.com/49724027/179340169-4375f1d5-7e9d-4b5d-b53a-727b0e1076c7.png)

**Comment by TuiMao233** [comment]
We should try our best to meet the low switching cost, which can make our users and theme development more convenient, make our themes more, and everyone can become a theme developer. As long as it wants to be, we should be as contented as possible.

![image](https://user-images.githubusercontent.com/49724027/179340354-1aec9629-4e64-431f-a20d-f332b923d0cd.png)
