### ISSUE TITLE
question: category total should be the total of all categories

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#63]
![image](https://user-images.githubusercontent.com/49724027/179881123-db0d0e7c-5722-4180-8b67-a37fe9d94fb8.png)

If the user needs the total number of primary categories, he can use `category.children.size`

`category.total` should be all statistics

```ts
const category = useCategory()
category.children.size
category.total // all total
```

**Comment by YunYouJun** [comment]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/25154432/179885129-c3f4cd0c-a74c-4eb0-9ec2-75e1eea6c6e7.png">

In fact, total is the number of posts.

**Comment by YunYouJun** [comment]
Maybe there's something wrong with the statistics. I'll check.

**Comment by YunYouJun** [comment]
Fixed.
