### ISSUE TITLE
feat: plan to upgrade vite 3 version

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#64]
The official version of vite 3 has been released

related: [/vite/CHANGELOG](https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md)、[vite-blog](https://vitejs.dev/blog/announcing-vite3.html)

**Comment by YunYouJun** [comment]
When i upgraded `@vitejs/plugin-vue` to `v3`, It will get stuck.
I still can't find out why.

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/valaxy/commit/7fb9cf456c95665f9b2bc9a9c2135d88b167fdfb.
Seems related to `<YunFooter />` `<slot />`.
