### ISSUE TITLE
bug: theme unspecified layout ssg build exception

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#65]
related: https://github.com/antfu/vite-ssg/issues/168

![image](https://user-images.githubusercontent.com/49724027/180167385-3c28ffcd-772c-4e18-b727-c4ad398246ba.png)

After setting the layout

![image](https://user-images.githubusercontent.com/49724027/180167520-cab10c31-86ac-434d-a302-553d6bcc8eb0.png)

**Comment by YunYouJun** [comment]
I think it is fixed in `v0.10.3`.
