### ISSUE TITLE
question: how to get page toc config

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#73]
![image](https://user-images.githubusercontent.com/49724027/180356663-bd8a9fda-4e79-46d6-abc7-171515f2eea5.png)

![image](https://user-images.githubusercontent.com/49724027/180356763-23f2f479-6f24-45a1-b0c6-203c3b603b09.png)

![image](https://user-images.githubusercontent.com/49724027/180356782-35e4679a-2a79-46ac-9158-025d267a71e2.png)

**Comment by Rotten-LKZ** [comment]
So `data.headers` is TOC, isn't it?

**Comment by YunYouJun** [comment]
Check to see if you are using `async` content in the API associated with `vite-plugin-pages`.

I have encountered this problem with `extendRoute` and raised an issue https://github.com/hannoeru/vite-plugin-pages/issues/257.
