### ISSUE TITLE
bug: useData is an empty object whenever

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#74]
![image](https://user-images.githubusercontent.com/49724027/180358319-753e2bef-0081-4195-ab3c-0059acd940a3.png)

The point of the problem was not found..., reproduce the repo

https://github.com/TuiMao233/valaxy-theme-hairy

**Comment by YunYouJun** [comment]
I think it works well in https://github.com/YunYouJun/valaxy/blob/main/packages/valaxy-theme-press/components/PressDocFooterLastUpdated.vue.

If possible, I would prefer that we avoid this api as much as possible.
