### ISSUE TITLE
bug: `` in .md is not being parsed correctly

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#75]
![image](https://user-images.githubusercontent.com/49724027/180359432-5f8d89cd-a132-4572-ac14-f5691502e2f3.png)
![image](https://user-images.githubusercontent.com/49724027/180359454-952fdc15-e3f8-4a65-87bd-75e8c58a35d2.png)

**Comment by Rotten-LKZ** [comment]
It seems to be working normally.
![source](https://user-images.githubusercontent.com/54099603/188294926-d5b35690-fa9a-4cc6-bbe6-9e51bee5f3dc.png)
![theme press](https://user-images.githubusercontent.com/54099603/188294905-ca56fc6f-4958-4d7e-9214-67bce0da6920.png)
![theme yun](https://user-images.githubusercontent.com/54099603/188294910-a51abeea-51e4-427a-8c48-0cab9e9a1ef9.png)

**Comment by TuiMao233** [comment]
The bug appears in custom themes

**Comment by YunYouJun** [comment]
Same with #109.
