### ISSUE TITLE
question: internal server error: Failed to resolve import "@waline/client/dist/waline.css"

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#77]
![``6U2F2B (765BB7 }~ZXNQ](https://user-images.githubusercontent.com/49724027/180488849-a057e1f1-9feb-4018-8a12-b554d122a89e.png)

Solved after installing @waline/client, if it is not installed by default, the documentation should be marked

**Comment by YunYouJun** [comment]
`valaxy-addon-waline` sepearted in https://github.com/YunYouJun/valaxy/commit/7b334c7270aeb384ee1c716f1b1f6f060a30cd83.
