### ISSUE TITLE
bug: useWaline is not exported by default

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#78]
![image](https://user-images.githubusercontent.com/49724027/180489324-1c666ec6-67ee-4d4b-8a7b-0a0f31e0b0b9.png)

Solution

![image](https://user-images.githubusercontent.com/49724027/180489389-7c99f2af-4b8d-485b-a9a7-192edc67a289.png)

I think this is an open issue, at least we shouldn't import like this

**Comment by YunYouJun** [comment]
#77
