### ISSUE TITLE
what about the CSS-i18n in Valaxy to be an independent project

### ISSUE THREAD

**Issue by LoTwT** [YunYouJun/valaxy#82]
I think it's interesting . I want to try myself to make CSS-i18n better though I'm not a good FE development and not good at CSS.
~~你能帮帮我吗，求求你了，求求你了~~

**Comment by YunYouJun** [comment]
I simply extracted a css-i18n package, let's move the discussion here.

> https://github.com/valaxyjs/css-i18n
