### ISSUE TITLE
css style of docs/pages/guide/i18n.md on mobile is incorrect

### ISSUE THREAD

**Issue by LoTwT** [YunYouJun/valaxy#84]
The i18n page's css style is incorrect.
When using <https://valaxy.site/>, it will be correct after refreshing, but in dev it has no change.
![image](https://user-images.githubusercontent.com/50254496/180587487-4fbb71a8-503f-4b1d-ab46-3840d80b68bc.png)

**Comment by Rotten-LKZ** [comment]
I solved this problem in #115.
Now it looks like this:
![Now](https://user-images.githubusercontent.com/54099603/188296035-d3daa782-44c5-4730-b9bd-833d242e7a33.png)
