### ISSUE TITLE
how tip/warning blocks to use CSS-i18n, is it still WIP ?

### ISSUE THREAD

**Issue by LoTwT** [YunYouJun/valaxy#85]
In docs/page/guide/i18n.md, tip block is always using zh-CN.

**Comment by Rotten-LKZ** [comment]
![Source](https://user-images.githubusercontent.com/54099603/188296317-691c9865-4c4d-48d4-85e6-9991eb7bbd9d.png)
![Chinese Tip](https://user-images.githubusercontent.com/54099603/188296339-d1f3ad29-375a-411e-b8b0-d14427aade78.png)
![English Tip](https://user-images.githubusercontent.com/54099603/188296342-57beaac2-80ae-4c41-a3ff-81971c31fb8b.png)
You can use tip/warning blocks now with CSS-i18n. However, it isn't parsed very well.

**Comment by YunYouJun** [comment]
Set i18n for tips:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/25154432/188323762-6ef44a52-510d-4fdd-9330-30f7ae422913.png">

To avoid conflicts, use `<div lang="zh-CN">` for `block` i18n:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/25154432/188323782-cf0c2228-4f39-43e6-abb1-bcf9b034c7fb.png">
