### ISSUE TITLE
bug: In extendMd, the modification of ctx.data is invalid

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#87]
![image](https://user-images.githubusercontent.com/49724027/180678555-e0efdb58-73c2-461a-831b-232e2d322dcc.png)

**Comment by YunYouJun** [comment]
`data` 解析自 Markdown frontmatter，将会被合并至 `route.meta.frontmatter: {}` 中。
因此 `data` 是原始数据，不可变。
