### ISSUE TITLE
i18n for toc

### ISSUE THREAD

**Issue by Rotten-LKZ** [YunYouJun/valaxy#9]
Here is the content of an article:

```markdown
---
title: Valaxy Test 文章内容测试
date: 2022-03-23
categories:
  - AAA
  - BBB
  - CCC
tags:
  - valaxy
  - 测试
  - test
---

:::zh-CN
[[toc]]

标题是一级标题

## 二级标题

### 三级标题

#### 四级标题

##### 五级标题

###### 六级标题

## 标题

## 列表测试

- AAA
- BBB
- CCC
  - DDD
    - EEE

### Checkbox

- [ ] FLAG
- [x] FLAG
:::

:::en
[[toc]]

The title is a primary title

## Secondary title

### Tertiary title

#### Level four title

##### Level five title

###### Level six title

## Title

## List title

- AAA
- BBB
- CCC
  - DDD
    - EEE

### Checkbox

- [ ] FLAG
- [x] FLAG
:::
```

It seems that when I type ``[[toc]]`` in article, Valaxy will render the table of contents.

But if this articles is internationlized, Valaxy will render like this:

![Table of Contents](https://github.com/Rotten-LKZ/cdn/blob/main/images/issue/valaxy-toc.png?raw=true)

However, I expect Valaxy can render the table of contents in language which I used.

**Comment by YunYouJun** [comment]
I'm going to try to add the lang attribute to the header when parsing it to solve this problem, but it hasn't been done.

**Comment by YunYouJun** [comment]
https://user-images.githubusercontent.com/25154432/166158689-47600421-6cd9-4b33-84fd-19294011882c.mov

Now, valaxy support it!

From general table of contents to sub-categories to article content to comments, all i18n refreshless switching is supported.
