### ISSUE TITLE
bug: unable to find package for addons

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#90]
![image](https://user-images.githubusercontent.com/49724027/180689827-edc05e94-94e8-4304-a12d-58d67de9e6ae.png)

问题由上一个分支 commit 导致

![image](https://user-images.githubusercontent.com/49724027/180690346-870ec45a-3820-4a9d-956b-23254cd5c06e.png)

**Comment by YunYouJun** [comment]
When use `monorepo`, we need add it to root `package.json`.

`basedir` can solve it when user add it to package.json, but doesn't work when the theme uses it.
