### ISSUE TITLE
bug: unable to use valaxy addons in theme in any form

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#91]
![image](https://user-images.githubusercontent.com/49724027/180691589-9f085526-a81f-44e0-ab53-02e95a9b1380.png)

**Comment by TuiMao233** [comment]
emm, this is a temporary solution

![image](https://user-images.githubusercontent.com/49724027/180693536-cf45d77d-f029-4274-b232-68cdaa783f96.png)

**Comment by YunYouJun** [comment]
Now, it works.

```ts
export default defineTheme<ThemeConfig>((options) => {
  return {
    themeConfig: defaultThemeConfig,
    vite: {
      plugins: [ThemeVitePlugin(options)],
    },
    unocss: {
      safelist: generateSafelist(options),
    },
    addons: ['valaxy-addon-waline'],
  }
})
```
