### ISSUE TITLE
bug: usePostList type cannot be overridden by declare

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#95]
![image](https://user-images.githubusercontent.com/49724027/180740788-9fd8590e-fe34-4fd3-aebb-3eaf37ec83c9.png)

this is correct

```ts
import { Post } from 'valaxy'
```

this is wrong

```ts
import { usePostList } from 'valaxy'
const posts = usePostList()
posts.value[0]
```

**Comment by YunYouJun** [comment]
I didn't find a good way to cover it. Is there an example can refer to?

**Comment by YunYouJun** [comment]
Got it. If i import if from root and then export, it will works.
