### ISSUE TITLE
bug: after the console error is reported, the error is repaired and the error is not restored

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#96]
![image](https://user-images.githubusercontent.com/49724027/180745649-1e9c8899-faa5-46e7-8d42-4582edc59ee7.png)

**Comment by YunYouJun** [comment]
I can't understand what you mean, valaxy doesn't have these content.

**Comment by TuiMao233** [comment]
I'm talking about the console not returning to normal

**Comment by YunYouJun** [comment]
This should be because there is no prompt after hot update, I will add a new prompt.

**Comment by YunYouJun** [comment]
Now,  it works well. Will show log when hot reload.
