### ISSUE TITLE
feat: allow router instance in js/ts

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#97]
Currently, to use the router, you must pass the component's useRouter

I think we can export router instance for those who need

```ts
import { router } from 'valaxy/client'
router.push('...')
```

**Comment by YunYouJun** [comment]
`router` is from `vue-router`.

They behave exactly the same, and I think it's always correct to import from `vue-router`.

```ts
import { router } from 'vue-router'
```

**Comment by TuiMao233** [comment]
I think yes, as long as we can get it, but it doesn't seem to be supported at the moment

![image](https://user-images.githubusercontent.com/49724027/180906908-96c0d526-edd3-496c-ba71-705ab85a38c7.png)

**Comment by YunYouJun** [comment]
Use it like this.

```ts
import { useRouter } from 'vue-router'
const router = useRouter()
```

**Comment by TuiMao233** [comment]
No, we can't get the router outside the component via useRouter, it only works during setup

**Comment by YunYouJun** [comment]
`useRouter` need and should only works durint setup.

Even if we export from Valaxy, it needs to be initialized in Setup.

**Comment by YunYouJun** [comment]
If you want to a instance, `this.$router` can be achieved in Vue.

> https://router.vuejs.org/guide/#javascript
